### ISSUE TITLE
Mimicing Zsh behavior of nsearch (non-incremental prefix search)

### ISSUE THREAD

**Issue by rashil2000** [akinomyoga/ble.sh#101]
Hi, 
Thanks for the great project!

I'd like to move away from Zsh, so ble.sh sounds very promising. However, I would like to mimic Zsh's default history searching behavior in ble.sh. See below:

![zsh](https://user-images.githubusercontent.com/46838874/116003200-a73bb280-a61a-11eb-967c-df0931495298.gif)

(type the beginning of your command, and press Up/Down to browse the history lines that _begin_ with the substring I type)

Below is the default behavior of ble.sh in bash:

![bash](https://user-images.githubusercontent.com/46838874/116003255-dfdb8c00-a61a-11eb-9311-3c3241487312.gif)

I would like to make it like Zsh. Specifically, I would like to:
1. Remove/hide the `nsearch` info below my prompt
2. I would like the cursor to move to the end of line while searching with Up/Down.
3. If I don't find what I'm looking for in the history, I press Down key the same number of times I have pressed Up key. This brings me back to the string that I had typed (like 'pacman' in the GIF of Zsh above). But in ble.sh/bash, the whole line remains even after pressing Down key repeatedly.

I have put the following lines in my .bashrc
```bash
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'
```

Any help would be appreciated. 
Thanks in advance!!!

**Comment by akinomyoga** [comment]
> Remove/hide the `nsearch` info below my prompt

Thank you for your suggestion! This is related to the discussion in #80 with @Alyetama yesterday. I'm now thinking of adding a new bleopt option `bleopt nsearch_opts` which is a colon-separated list of, e.g.,

- `hide-status` (always hide the `nsearch` status of ``'(nsearch#COUNT: << !POS >>) `NEEDLE'``)
- `hide-status-on-empty` (hide the status when the search string is empty)
- `move-on-empty` (when the search string is empty, just move to the previous line instead of starting the non-incremental search)
- `move-on-single-key-empty` (when the nsearch is called by a single-key binding and the search string is empty, just move to the previous line)

> I would like the cursor to move to the end of line while searching with Up/Down.

OK, I'll consider an option for it. Actually, the purple "matched part" is highlighted as the current *selection*, so if the cursor position is simply moved to the end of the line, the entire line would be highlighted while `nsearch`. But maybe I can add a special selection so that the matched part is correctly highlighted. Which behavior do you prefer? 1) Highlight the entire line 2) Highlight only the matched part (the initial terminal content).

> If I don't find what I'm looking for in the history, I press Down key the same number of times I have pressed Up key. This brings me back to the string that I had typed (like 'pacman' in the GIF of Zsh above). But in ble.sh/bash, the whole line remains even after pressing Down key repeatedly.

Actually, the current behavior is the imitation of Bash's behavior, but I agree that the behavior is not so friendly, so I'll consider the change.

I'm recently a kind of busy, so may take some time. There are several pending fixes of `ble.sh`, but I think I first try to support this one before the others. Thank you for your understanding.

**Comment by rashil2000** [comment]
> I'm now thinking of adding a new bleopt option bleopt nsearch_opts which is a colon-separated list of...

That sounds like a great idea (I personally prefer the 3rd and 4th opts).

> Which behavior do you prefer? 1) Highlight the entire line 2) Highlight only the matched part (the initial terminal content).

I think highlighting only the matched part would be more preferable. Highlighting the entire line would give the (false) impression that the entire line is being used in the search. Actually, I sometimes use PowerShell too, and PowerShell's behavior exactly matches Zsh's behavior - searching using only the substring upto the current cursor position, but also moving the cursor to the end when browsing through the matches.

> Actually, the current behavior is the imitation of Bash's behavior, but I agree that the behavior is not so friendly, so I'll consider the change.

Thank you, that'll be awesome!

> I'm recently a kind of busy, so may take some time. There are several pending fixes of ble.sh, but I think I first try to support this one before the others.

Please take your time! There's no hurry (from my side 😊). Good things do take time. Thanks again for ble.sh!!!

**Comment by rashil2000** [comment]
I don't know if it's apparent from the Zsh GIF, but there's one more tiny detail: pressing Enter on any search item in Zsh straight up runs that command, whereas on ble.sh you have to press Enter twice (one to accept the search item, one to run it).

**Comment by akinomyoga** [comment]
> whereas on ble.sh you have to press Enter twice (one to accept the search item, one to run it

That's also discussed in https://github.com/akinomyoga/ble.sh/issues/80#issuecomment-826162400, but it's intentional. If you want to immediately run the command, you can press <kbd>C-j</kbd> or <kbd>C-RET</kbd>. You can change the keybinding using `ble-bind`. I don't currently have a plan to change the current default behavior unless there is a convincing reason to change. Maybe I can instead add some description in in Q&A or add an explicit bleopt option to change the behavior.

**Comment by rashil2000** [comment]
`ble-bind -m 'nsearch' -f 'RET' 'nsearch/accept-line'` 

I tried to issue this command but it didn't work, am I doing this wrong?

**Comment by akinomyoga** [comment]
As written in [Manual §3.1](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A73-Key-Binding#31-key-specifier-kspec--keyseq-specifier-kspecs)/¶5,

> *Quoted from Manual §3.1/¶5*: [...] These control characters (originally received as characters) are converted to keys <kbd>C-@</kbd>, <kbd>C-a</kbd>...<kbd>C-z</kbd>, <kbd>C-[</kbd>, <kbd>C-\\</kbd>, <kbd>C-]</kbd>, <kbd>C-^</kbd>, <kbd>C-_</kbd> during decoding to key sequences, so normally they cannot appear directly in key sequences.

In terminals, raw bytes \000-\037 are used to encode <kbd>C-@</kbd>-<kbd>C-_</kbd>, so the "key <kbd>RET</kbd>" is usually transferred as <kbd>C-m</kbd> by the terminal unless your terminal explicitly encodes <kbd>RET</kbd> using the special key sequences of `CSI ... u` or `CSI 2 7 ; ... ~`. Similarly "key <kbd>ESC</kbd>" is transferred as <kbd>C-[</kbd>. "key <kbd>TAB</kbd>" is <kbd>C-i</kbd>. So you first want to try to bind them to <kbd>C-m</kbd> and <kbd>C-[</kbd>. For some rich terminals that distinguish <kbd>RET</kbd>/<kbd>ESC</kbd> from <kbd>C-m</kbd>/<kbd>C-[</kbd>, you could additionally set up the same keybindings for `RET` and `ESC`.

```bash
ble-bind -m 'nsearch' -f 'C-m' 'nsearch/accept-line'
ble-bind -m 'nsearch' -f 'RET' 'nsearch/accept-line'
ble-bind -m 'nsearch' -f 'C-[' 'nsearch/cancel'
ble-bind -m 'nsearch' -f 'ESC' 'nsearch/cancel'
```

When you want to bind a widget to <kbd>C-[</kbd> (`ESC`), I recommend you to read [§3.5](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A73-Key-Binding#35-reception-and-interpretation-of-esc). The byte `ESC` is also used to represent the Meta modifier of a key in terminals so is essentially ambiguous. `ble.sh` takes some heuristic approach to determine the role of `ESC`. You may want to also check [`bleopt decode_isolated_esc`](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A73-Key-Binding#user-content-bleopt-decode_isolated_esc).

If you want to distinguish <kbd>RET</kbd> from <kbd>C-m</kbd> and assign different keybindings, you may use a terminal  that sends distinct sequences of <kbd>RET</kbd> in [§3.6 `modifyOtherKeys`](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A73-Key-Binding#36-settings-for-modifyotherkeys) mode. Or, if your terminal allows you to manually configure the escape sequence of each key by yourself, you may let it send `\e[13;1u` for <kbd>RET</kbd>, `\e[27;1u` for <kbd>ESC</kbd>, `\e[9;1u` for <kbd>TAB</kbd>, etc. (see also [§3.6.3](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A73-Key-Binding#363-settings-for-terminals-without-modifyotherkeys-feature)).

**Comment by rashil2000** [comment]
Wow, thanks for such a detailed answer. `C-m` and `C-[` work like a charm. 

> The byte ESC is also used to represent the Meta modifier of a key in terminals so is essentially ambiguous.

Thanks, will keep that in mind. 

> ...you may use a terminal that sends distinct sequences of RET in §3.6 `modifyOtherKeys` mode...

For the most part, I'm using Windows Terminal, and as far as I know, there's no way to set key sequences in it yet.

**Comment by akinomyoga** [comment]
## New options for `nsearch` widgets

@rashil2000 @Alyetama @carv-silva In the commit 9125795, I've implemented options of nsearch as an argument of `nsearch` widgets.

```bash
ble-bind -f up 'history-search-forward OPTS'
ble-bind -f down 'history-search-backward OPTS'
```

where OPTS is a colon-separated list of the following options:

- `hide-status` ... do not show the `nsearch` status of ``(nsearch #N: << !M >>) `NEEDLE'`` (requested by @carv-silva (?) and @rashil2000)
- `immediate-accept` ... the widget `nsearch/exit`---which is defautly bound to <kbd>C-m</kbd> and <kbd>RET</kbd>---immediately runs the command (requested by @Alyetama and @rashil2000)
- `action=ACTION` ... specifies the type of action taken when the search string is matched to a history entry. ACTION is one of the following values:
  - `goto` (default) ... go to the history entry
  - `load` ... load the text of the history entry without moving the current history position. This is Bash's default behavior.
- `point=POINT` ... specifies the cursor position after the action. POINT is one of the following values:
  - `begin` ... the beginning of the command line
  - `end` ... the end of the command line (@rashil2000's request)
  - `match-begin` ... the beginning of the matched part
  - `match-end` (default) ... the end of the matched part
- `empty=EMPTY` ... specifies the special treatment on the empty command search
  - `empty-search` (default) ... starts `nsearch` with an empty string
  - `hide-status` ... starts `nsearch` with an empty string but do not show the nsearch status
  - `previous-search` ... starts `nsearch` with the previous search string
  - `history-move` ... just go to the previous/next history entry without starting the `nsearch`. The cursor position is set to the beginning of the command line to keep the string before the cursor empty.
 
Compared to the previous behavior the following two points are changed:
- Now the default action on the match is changed from `action=load` (Bash-like) to `action=goto` (Zsh-like).
- When the user presses <kbd>down</kbd> the same number of times as <kbd>up</kbd> (including the one used to enter the `nsearch` mode), it recovers the original command line (when it matches with the search string). (@rashil2000's suggestion)

### nsearch of ble.sh default keybindings

For the default keybindings in `ble.sh`, <kbd>C-x up</kbd>, <kbd>C-x C-p</kbd>, <kbd>C-x p</kbd>, <kbd>C-x \<</kbd>, etc., OPTS is empty.

### nsearch from Readline user settings

```bash
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'
```

The above Readline settings are now interpreted as the following ble.sh settings:

```bash
ble-bind -f up 'history-search-backward empty=history-move'
ble-bind -f down 'history-search-forward empty=history-move'
```

It seems that (naive) users are confused by the old behavior that `ble.sh` starts a non-incremental search for the empty string, I have changed the default behavior so that it just moves the history entries forward/backward when there is no string before the cursor.

If one would like to make the behavior as close to Bash's as possible, one can explicitly use the following keybindings:

```bash
ble-bind -f up 'history-search-backward hide-status:immediate-accept:action=load'
ble-bind -f down 'history-search-forward hide-status:immediate-accept:action=load'
```

### @rashil2000 

You can use the following keybindings:

```bash
ble-bind -f up 'history-search-backward hide-status:immediate-accept:point=end'
ble-bind -f down 'history-search-forward hide-status:immediate-accept:point=end'
```

Now with the option `immediate-accept`, you don't have to rebind <kbd>C-m</kbd> and <kbd>RET</kbd>.

> https://github.com/akinomyoga/ble.sh/issues/101#issuecomment-828175533 by @rashil2000 
> `ble-bind -m 'nsearch' -f 'RET' 'nsearch/accept-line'` 
> 
> I tried to issue this command but it didn't work, am I doing this wrong?
> 
> I also tried `ble-bind -m 'nsearch' -f 'ESC' 'nsearch/cancel'` to map Esc key for clearing search, but this also doesn't seem to work. Is there any other way to do this?

I have added a subsection in [Manual §3.1.1](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A73-Key-Binding#311-representation-of-ret-esc-tab-bs-and-del). It's basically the same as the explanation in [my previous reply](https://github.com/akinomyoga/ble.sh/issues/101#issuecomment-828260472).

### @Alyetama

> https://github.com/akinomyoga/ble.sh/issues/80#issuecomment-826129833 by @Alyetama
> I would like to know if there is a way to bypass this and instead just hit <kbd>up</kbd> then <kbd>enter</kbd> to run the previous line (the normal bash behavior)?

Now you can use the option `immediate-accept`. I'm not sure exactly how you set up `nsearch`, but for example, you can use the following settings. Now you don't have to rebind <kbd>C-m</kbd> and <kbd>RET</kbd> in `nsearch` keymap.

```bash
ble-bind -f up 'history-search-backward immediate-accept'
ble-bind -f down 'history-search-forward immediate-accept'
```

You may also add other options if you want to change the detailed behavior.

> https://github.com/akinomyoga/ble.sh/issues/80#issuecomment-826194833 by @Alyetama
> I have been looking for a configuration before I posted my comment, but have found none. If there is one, then I would have just used it.

I have added a description in Manual [§4.10.1](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A74-Editing#user-content-widget-history-search). I also added examples in [`blerc`](https://github.com/akinomyoga/ble.sh/blob/912579585a0fde8980a69bc60a2ec962050b8511/blerc#L624-L634).

### @carv-silva

> https://github.com/akinomyoga/ble.sh/issues/80#issue-778549281 by @carv-silva
> **How to turn off the nsearch ``(nsearch#1: << !1170 ) `'``?**
> Theres one workaround like `exec_errexit_mark=` to hide ``(nsearch#1: << !1170 ) `'``?

Finally, I'm not sure if this is what you wanted, and also I'm not sure how you set up `nsearch`. But if I take your request literally and if I assume that you have set up the nsearch for <kbd>up</kbd> and <kbd>down</kbd> through e.g. `oh-my-bash`, you may add the following settings in `~/.blerc`:

```bash
ble-bind -f up 'history-search-backward hide-status'
ble-bind -f down 'history-search-forward hide-status'
```

But I think this setting is confusing. Maybe you can also add `immediate-accept` option:

```bash
ble-bind -f up 'history-search-backward hide-status:immediate-accept'
ble-bind -f down 'history-search-forward hide-status:immediate-accept'
```

**Comment by rashil2000** [comment]
Beautiful! Can't thank you enough...

Should I close this then?

**Comment by akinomyoga** [comment]
OK! Thank you! I'll close it.
