### ISSUE TITLE
ble modifies PS0

### ISSUE THREAD

**Issue by tycho-kirchner** [akinomyoga/ble.sh#107]
**ble version**: 0.4.0-devel3+c257299
**Bash version**: 5.0.11(1)-release, x86_64-pc-linux-gnu

The title says it all: sourcing ble modifies bash's PS0-prompt, which some users use. 

Thank you

Tycho

~~~
tycho@d:~$ PS0='$(echo ps0  >&2)'
tycho@d:~$ echo ok
ps0
ok
tycho@d:~$ source ~/tmp/ble.sh/ble.sh/out/ble.sh
ps0
tycho@d:~$ echo ok two
ok two
 tycho@d:~$
~~~

**Comment by akinomyoga** [comment]
Thank you for the report! Hmm, actually I intentionally kill `stderr` in evaluating `PS0`. This is to suppress debug messages on `set -x`. May I ask why don't you just let the shell output the results?

```bash
PS0=$'ps0\n'

# or
PS0=$(echo ps0 >&2)
```

**Comment by akinomyoga** [comment]
I'll try to allow `stderr` in `PS0`. Nevertheless, I don't think it is a good idea to bypassing the mechanism of `PS0`. But, if you want to really output something to the terminal, you can actually redirect it to `>/dev/tty`. Something like

```bash
    PS0="$PS0"'$(_shournal_ps0 \# 2>/dev/tty)'
    PS1="$PS1"'$(_shournal_ps1 \# 2>/dev/tty)'
```

**Comment by tycho-kirchner** [comment]
Thanks. 
And wow, you found my _shournal_ps0 really quick ^_^
What do you mean by "bypassing the mechanism of `PS0`"?

**Comment by akinomyoga** [comment]
> What do you mean by "bypassing the mechanism of PS0"?

Ah, OK. I meant that the idea of `PS0` is to output the **expanded result** of `PS0` to the terminal. If one provides something to output as the expanded result of `PS0`, the shell will output it. But it seems that you try to output something directly to the terminal without passing it to `PS0` expanded result, which appeared to me like *bypassing*.

**Comment by tycho-kirchner** [comment]
Nice. stderr now works as expected and in fact we're getting closer to the real issue.
ble seems to change the command-sequence counter `\#`:
test.sh:
~~~
ps0(){
    echo "ps0 seq $1" >&2
}

ps1(){
    echo "ps1 seq $1" >&2
}

PS0='$(ps0 \#)'
PS1="$PS1"'$(ps1 \#)'
~~~
_______________________________________
~~~
tycho@d:~$ source test.sh
ps1 seq 2
tycho@d:~$ echo ok
ps0 seq 2
ok
ps1 seq 3
tycho@d:~$ echo ok2
ps0 seq 3
ok2
ps1 seq 4
tycho@d:~$ source ~/tmp/ble.sh/ble.sh/out/ble.sh 
ps0 seq 4
ps1 seq 4
tycho@d:~$ echo ok3
ps0 seq 5
ok3
ps1 seq 5
tycho@d:~$
~~~

**Comment by akinomyoga** [comment]
Ah, good point. For this one, I need to rethink the structure of the execution model...

**Comment by akinomyoga** [comment]
I added a fix 8b0257e for `\#`, etc. Finally, I didn't need to change the execution model but just added a small constraints.

----

**Details**: `ble.sh` separates the command editing module (A) and the command execution module (B). When the user requests the execution of the command, (A) sends a command data to the queue of (B). (B) would run the received commands when `ble.sh` is idle. This means that (B) might run multiple commands at the same time when `ble.sh` is busy, where the execution might become
```
$ COMMAND1
$ COMMAND2
[PS0]
COMMAND1
[PS0]
COMMAND2
[PS1]
PROMPT$ 
```

I thought this can complicate the updates of `\#` if we try to update it after `PS0`, but I have changed so that (B) will try to run the command soon even when it is not idle. Now basically the above case will not happen (unless a user writes a custom editing function that sends multiple commands for one keystroke).

Actually, I noticed that the above `[PS0]COMMAND1[PS0]COMMAND2[PS1]` can happen even in the normal Bash when the user input multiline commands using <kbd>C-v</kbd><kbd>C-j</kbd>, so I decided not to make too much efforts to completely exclude such cases.

I also noticed that the command execution count `\#` is the information only available in prompts, so I could easily change the update rule of `\#` without affecting other parts.

----

I'm not sure what `shournal` expects exactly, but if it expects that `PS0` and `PS1` are always paired around each command, <code><a href="https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A71-Introduction#user-content-fn-blehook">blehook</a> PREEXEC</code> and `blehook POSTEXEC` are actually more clean and reliable for that purpose. Maybe you can instead use them when `ble.sh` is loaded.

**Comment by tycho-kirchner** [comment]
Thanks for these detailed instructions, which I was able to reproduce. However, you seem to imply that PS1 is not **executed** between `Command 1` and `Command 2`, however, what really happens is that the `stdout` of PS1 is **supressed** but it is still executed.:
<pre>
<b>PS0='$(echo ps0 out; echo ps0 err >&2)\n' PS1='$(echo ps1 out; echo ps1 err >&2)\n'</b><kbd>RET</kbd>
ps0 err
ps0 out
ps1 err
ps1 out
<b>echo Command 1</b> <kbd>C-v C-j</kbd>
<b>echo Command 2</b> <kbd>RET</kbd>
ps0 err
ps0 out
Command 1
ps1 err
ps0 err
ps0 out
Command 2
ps1 err
ps1 out
</pre>

**Comment by akinomyoga** [comment]
> however, what really happens is that the stdout of PS1 is supressed but it is still executed.:

Oh, I see! It is surprising to me that `PS1` was actually evaluated in the middle of the execution of multiline commands. I didn't know that until now!

Anyway, `ble.sh` treats the multiline commands as a single execution as a whole, so it only evaluates `PS0` once before all the commands and `PS1` once after all the commands:

<pre>
<i>/* In a ble.sh session */</i>
[murase@chatoyancy 0 ~]$ <b>PS0='$(echo "[PS0]">&2)' PS1='$(echo "[PS1]">&2)\$ '</b><kbd>RET</kbd>
[PS1]
$ <kbd>C-q C-j</kbd>
<b>echo Command1</b><kbd>RET</kbd>
<b>echo Command2</b><kbd>C-j</kbd>
[PS0]
Command1
Command2
[PS1]
$
</pre>

## In ble.sh

I think the current behavior of `ble.sh` is basically enough for `shournal`, but in theory, the following case might still happen in ble.sh (when the user inputs many commands in a row very fast but at some specific speed in very slow machiine), but the probability should be very low:

<pre>
$ <b>echo Command1</b><kbd>RET</kbd>
$ <b>echo Command2</b><kbd>RET</kbd>
[PS0]
Command1
[PS0]
Command2
[PS1]
$
</pre>

And also, `ble.sh` occasionally re-evaluates `PS1` in other situations. For example, when it received `SIGWINCH`, when the editing mode is changed, when the prompt setting has been changed in the widget (editing function), when other plugins (such as `fzf-marks`) requested the update of the prompt, etc.

I will not change this behavior in order to make `PS1` useful to detect the end of the command because it is the necessary calculation to update the prompt and also because the purpose of `PS1` is to enable the customization of the prompt and not to provide the way to detect the end of the command. Using `PS1` for the command-end detection is just a hack. The same for `PS0`. If you want a more reliable way to detect the beginning and end of the command execution in `ble.sh`, could you use the afore-mentioned `PREEXEC` and `POSTEXEC` in the presence of `ble.sh`? `PREEXEC` and `POSTEXEC` are exactly introduced for such kind of purpose and are ensured to be executed once for one command execution in any situation.

<pre>
[murase@chatoyancy 0 ble.sh]$ blehook POSTEXEC+='echo POSTEXEC >&2'
POSTEXEC
[murase@chatoyancy 0 ble.sh]$ blehook PREEXEC+='echo PREEXEC >&2'
POSTEXEC
[murase@chatoyancy 0 ble.sh]$ echo yes
PREEXEC
yes
POSTEXEC
</pre>

If you have any questions on the usage or any problems in using them, please feel free to ask me for the detail!

**Comment by akinomyoga** [comment]
@tycho-kirchner Hi, how are you doing? if you don't have further issues related to `shournal`, may I close this issue?

**Comment by tycho-kirchner** [comment]
Sorry, I did not dig furhter into this due to lack of time (homeschooling, etc). If you want, we can close this for now.
Once I have more time I'll take a closer look into *ble*'s PREEXEC and POSTEXEC hooks. Basically *shournal* requires `history 1` to be set to the current command-string in PS0 and the last exitcode `$?` in PS1. In fact *shournal* could even drop PS1 altogether and use the `PROMPT_COMMAND` instead, but I don't know how *ble.sh* deals with that one. 
Anyway, thank you so far (:

**Comment by akinomyoga** [comment]
OK. Thank you for your reply!

> Once I have more time I'll take a closer look into _ble_'s PREEXEC and POSTEXEC hooks. Basically _shournal_ requires `history 1` to be set to the current command-string in PS0 and the last exitcode `$?` in PS1.

In `ble.sh`, `history 1` cannot be reliably used to retrieve the current command inside `PS0`, but if you set a function name to `PREEXEC`, you can get the command string as a first argument of the function. You can access the exit code of the previous user command through `$?` in both `POSTEXEC` and `PS1` in `ble.sh` (but of course `$?` needs to be saved by the first command inside the hook because it will be overwritten after the first command).

```bash
$ function preexec1 { echo "$FUNCNAME: command = $1"; }
$ function postexec1 { echo "$FUNCNAME: exit code = $?"; }
$ blehook PREEXEC+='preexec1' POSTEXEC+='postexec1'
$ (echo hello; exit 123)
preexec1: command = (echo hello; exit 123)
hello
postexec1: exit code = 123
```

> In fact _shournal_ could even drop PS1 altogether and use the `PROMPT_COMMAND` instead, but I don't know how _ble.sh_ deals with that one.

The timing of `PROMPT_COMMAND` execution is the same as `PS1` evaluation in `ble.sh` so is neither reliable in `ble.sh` for the detection of the end of user commands.

> Anyway, thank you so far (:

You're welcome! Please feel free to create a new issue or reopen this issue when you are to try `PREEXEC` and `POSTEXEC`. I close the issue for now. Thank you again for the information on the behavior of `PS0`!
