### ISSUE TITLE
blesh changes default behaviour of bash

### ISSUE THREAD

**Issue by RakibFiha** [akinomyoga/ble.sh#124]
**ble version**: `0.4.0-devel3+750ca38`
**Bash version**:  `5.0.17(1)-release (x86_64-pc-linux-gnu)` 

Default bash behaviour:
```
bash --norc
bash-5.0$ echo hi && echo $_
hi
hi
```
In blesh
```
○ → echo hello && echo $_
hello
```

However, bash functions behaves correctly:
```
○ → type mkcd
mkcd is a function
mkcd () 
{ 
    case "$1" in 
        -p)
            mkdir -p "$2" && cd "$_"
        ;;
        *)
            mkdir "$1" && cd "$_"
        ;;
    esac
}
```

Not exactly sure why $_ is not expanding correctly when executed interectively.

**Comment by akinomyoga** [comment]
Thank you for the report, but it seems I cannot reproduce the problem. In my environment, `$_` is expanded to `hi` or `hello` as expected.

- **Q1** Is your problem reproduced in a plain ble.sh session?

```bash
$ bash --norc
$ source /path/to/ble.sh --norc --noinputrc
$ echo hello && echo $_
```

**Comment by RakibFiha** [comment]
right, something wrong with my dotfiles. Thank you for your quick help.

**Comment by akinomyoga** [comment]
Thank you for checking! If the problem doesn't happen with the same dotfiles but without ble.sh, it means that the problem is caused by the interference between ble.sh and other settings in the dotfiles, thus it is somehow related to the behavior of ble.sh. If you found the additional information and is related to the detailed behavior of ble.sh, please feel free to reopen the issue! Thank you very much!
