### ISSUE TITLE
Does bash-it and ble.sh conflict?

### ISSUE THREAD

**Issue by SolarAquarion** [akinomyoga/ble.sh#125]
ble.sh (bind): unsupported readline function 'vi-bword' for keymap 'emacs'.

I'm getting this whenever i load bash

**Comment by akinomyoga** [comment]
Thank you for the feedback! That was actually just because ble.sh has never supported `vi` editing functions in `emacs` mode. Now in commit 21d636a, I have newly supported the following readline bindable functions in `emacs` and `vi_imap` keymaps:
- `vi-prev-word`
- `vi-bword`
- `vi-bWord`
- `vi-backward-word`
- `vi-backward-bigword`
- `vi-next-word`
- `vi-forward-word`
- `vi-forward-bigword`
- `vi-fword`
- `vi-fWord`
- `vi-end-word`
- `vi-end-bigword`
- `vi-eword`
- `vi-eWord`

Now in the latest version in `master` branch, there should be no error messages related to this. Thank you!

**Comment by SolarAquarion** [comment]
@akinomyoga i use "bash-it" to do theming, and the theming disappears when i use ble.sh

**Comment by akinomyoga** [comment]
Could you describe in more detail how it *disappears*? Also, how do you set up `bash-it` and `ble.sh`?

**Comment by SolarAquarion** [comment]
I try to use powerline-multiline and ble.sh, and ble.sh takes the whole thing over https://github.com/Bash-it/bash-it/tree/master/themes/powerline-multiline

**Comment by akinomyoga** [comment]
Thank you, but I had already tried `powerline-multiline` but couldn't reproduce the problem.

- Could you describe how you set up your `.bashrc` to load bash-it and ble.sh?
- Also, what is the result of the following command in a ble.sh session?

```bash
$ echo "$BASH_VERSION"
$ echo "$BLE_VERSION"
```
