### ISSUE TITLE
`Keypad Enter` does not work as `Return/Enter` does

### ISSUE THREAD

**Issue by Nudin** [akinomyoga/ble.sh#127]
**ble version**: 0.4.0-devel3+a034c91
**Bash version**: 5.1.8(1)-release (x86_64-pc-linux-gnu)

When I press the Return-Key the typed command will be executed as expected. But when I press Enter what seems to be a whitespace is inserted instead. When I write this to a file and look at it, it is actually: `EE 81 86` (in hex).

My terminal is kitty.

**Comment by akinomyoga** [comment]
Thank you. `EE 81 86` corresponds to the private character code 57414 (U+E046). This seems like a kitty's special key sequence `\e[57414u` ([Functional key definitions — kitty 0.21.2 documentation](https://sw.kovidgoyal.net/kitty/keyboard-protocol.html#functional-key-definitions)) for keypad enter. This special kitty sequence conflicts with the existing implementation of xterm for `modifyOtherKeys`[^1], so I decided to support them only in kitty terminal. In commit 27c80f9,

I have added a fix. Could you check if the problem has been solved in the latest version? You can update ble.sh by running `ble-update` command in a ble.sh session.

- [^1] Note: It conflicts with the private character U+E046. kitty has been caused many troubles in ble.sh so far since kitty introduces many conflicting features in a way that it changes the behavior of existing terminal features rather than to introduce new control sequences. One should know that kitty is a non-standard terminal. ]

**Comment by Nudin** [comment]
After a `ble-update` it works.

**Comment by akinomyoga** [comment]
Thank you for the check!
