### ISSUE TITLE
Autocomplete in Normal mode 

### ISSUE THREAD

**Issue by zim0369** [akinomyoga/ble.sh#130]
I've been a user of ohmyzsh stuff for a long time and I only used it for vi-mode, autosuggest, and autocomplete, And very surprised to get all of these three things in ble.sh. Thanks! 
But, one feature that existed in one of the ohmyzsh [plugin](https://github.com/zsh-users/zsh-autosuggestions.git $ZSH_CUSTOM/plugins/zsh-autosuggestions) would be great to have in ble.sh as well. So basically when I'm typing something like 'sudo gr...' then it does show me autocomplete suggestion like 'sudo gr[ub-mkconfig...]' but now I have to hit the tab key which would open up different choices infront of me which I have to navigate through by tabs but what if I just want to autocomplete the suggestion regardless of what the other choices are so in zsh I would press escape to go into normal mode and then press 'l'(l for left/lion), which would then autocomplete the whole thing depending on the current suggestion. 

2nd feature request :
Also if I've typed something like 'sudo pacman..' and then if I go to normal mode and press 'k' to see previously ran commands then zsh would show my only the commands that begin with 'sudo pacman..' because that's what I've typed in but ble.sh doesn't do that, rather it just goes through every last command.

**Comment by akinomyoga** [comment]
Thank you for your feedback! Not sure if I correctly understand what you are describing, but they seem to be already available with user configurations.

> what if I just want to autocomplete the suggestion regardless of what the other choices are so in zsh

This is by default available with <kbd>C-e</kbd>, <kbd>end</kbd>, <kbd>C-f</kbd>, or <kbd>right</kbd>. You can read [`auto-complete` - blesh Wiki](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A77-Completion#user-content-sec-auto-complete) for the summary and configurations for `auto-complete`. If you want to accept the suggested text through <kbd>TAB</kbd> key, you can put the following settings in your `blerc`.

```bash
# blerc

ble-bind -m auto_complete -f C-i auto_complete/insert
ble-bind -m auto_complete -f TAB auto_complete/insert
```

If you want to accept only the first word in the suggested text, you may use <kbd>M-f</kbd> or <kbd>M-right</kbd>. If you want to do it with <kbd>TAB</kbd>, you may instead put the following settings.

```bash
# blerc

ble-bind -m auto_complete -f C-i auto_complete/insert-word
ble-bind -m auto_complete -f TAB auto_complete/insert-word
```

> I would press escape to go into normal mode and then press 'l'

It's not so simple with the current implementation, and I don't think it's worth changing the current implementation, nor it's useful. The feature auto-complete is implemented as a sub-mode, so if you want to switch major modes (i.e., from the insert mode to the normal mode), auto-complete needs to be terminated once.

If you instead want to complete the suggested text by just pressing <kbd>l</kbd> when auto-complete is active, you may put the following setting:

```bash
# blerc

ble-bind -m auto_complete -f l auto_complete/insert
```

But this is actually not useful because we cannot insert <kbd>l</kbd> with this setting when auto-complete is activated.


----

> Also if I've typed something like 'sudo pacman..' and then if I go to normal mode and press 'k' to see previously ran commands then zsh would show my only the commands that begin with 'sudo pacman..'

This can also be configured by `ble-bind`

```bash
# blerc

ble-bind -m vi_nmap -f k history-search-backward
ble-bind -m vi_nmap -f j history-search-forward
ble-bind -m nsearch -f k nsearch/backward
ble-bind -m nsearch -f j nsearch/forward
```

If you don't want to show the current history position while searching, you may specify `hide-status` option to history-search widgets:

```
# blerc

ble-bind -m vi_nmap -f k 'history-search-backward hide-status'
ble-bind -m vi_nmap -f j 'history-search-forward hide-status'
ble-bind -m nsearch -f k nsearch/backward
ble-bind -m nsearch -f j nsearch/forward
```

You can find other useful options at [`history-search` - blesh Wiki](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A74-Editing#user-content-widget-history-search)

**Comment by zim0369** [comment]
That blerc config was what I actually needed. Thanks! It's actually better to use c-e instead of going to normal mode and pressing 'l'. 
Closing this issue.
