### ISSUE TITLE
unknown csi escape sequence in simpleTerminal

### ISSUE THREAD

**Issue by Shahabaz-Bagwan** [akinomyoga/ble.sh#132]
**ble version**: 0.4.0-devel3+a860769
**Bash version**: 4.4.20(1)-release

![image](https://user-images.githubusercontent.com/4272320/129849444-9c685dda-369c-462c-890c-38d74b15a7a1.png)
I am getting the csi error in my st terminal 0.8.4 if i open `st bash --norc` there is no error and I have also tried to comment out ble.sh line from bashrc and the error is not reported after that
![image](https://user-images.githubusercontent.com/4272320/129849527-def1aa52-0840-4803-9ad5-7ad965624cb7.png)

**Comment by akinomyoga** [comment]
Thank you for the report! But this is actually expected behavior of `st` telling that `st` doesn't support the terminal features `modifyOtherKeys` (<kbd>CSI &gt; m</kbd>) and `DA2` (<kbd>CSI &gt; c</kbd>). `ble.sh` works correctly without these terminal features, so you can safely ignore these messages. If you don't like these error messages or want to make these terminal features work, you should basically implement them in your `st` by yourself, apply related patches made by others, or request them in suckless' `dev` mailing list. Users of `st` are supposed to customize their terminal by implementing features by themselves, but I think `DA2` should be primarily implemented in the upstream because `DA2` is used to identify the terminal.

**Comment by akinomyoga** [comment]
@Shahabaz-Bagwan I decided to disable both `modifyOtherKeys` and `DA2` for `st`. We can use `TERM` environment variable to identify `st` because `st` sets `TERM=st-256color` so don't need to request `DA2` for `st`. I've checked the source code of `st`, and I think `modifyOtherKeys` will never be supported in future `st` looking at the structure of `st`, so I just disable it in `st` terminal. I have pushed the changes to the `master` branch.

Could you check the latest version by `ble-update`? Now there should be no messages of unknown CSI sequences.

**Comment by Shahabaz-Bagwan** [comment]
![image](https://user-images.githubusercontent.com/4272320/130188555-8806769b-c532-4377-bcb4-4edaab2fed56.png)

Thank you, I can confirm that the changes in master removes the issue I had.

**Comment by akinomyoga** [comment]
OK! Thank you for your checking!

**Comment by akinomyoga** [comment]
@Shahabaz-Bagwan I watched your video on YouTube! Thank you for mentioning ble.sh in the video!

- As for the option description, actually the plain ble.sh shows them in the menu by default, but unfortunately, the behavior would be overwritten if the user loads an external completion framework such as `bash-completion`, which will never provide us with the description of each completion.

  This is the result with plain ble.sh (though I noticed now that some options are generated more than once...):
  ![image](https://user-images.githubusercontent.com/8982192/131330254-39f3ba52-98bd-4efd-9e97-674274abdda8.png)

  Actually, `bash-completion` is so useful that I also enable it by default. Maybe I need to think about integrating both results from the external completions and ble.sh built-in option completions.

- Currently there is no feature to expand the aliases by completion, but maybe I can consider showing the alias information in the completion menu. There is a configuration to always show the description of each completion in the menu, but currently the description of aliases are just a single word `alias`:

  ![image](https://user-images.githubusercontent.com/8982192/131331221-6f3a0caf-2bb4-47bf-88ad-2453697f69e9.png)

  I think I'll add the definition of the alias in the description later.

**Comment by akinomyoga** [comment]
> Maybe I need to think about integrating both results from the external completions and ble.sh built-in option completions.

FYI, I have implemented this in commit c1cd666.

> I think I'll add the definition of the alias in the description later.

I've implemented this in commit 4de1b45, which is available with the setting `bleopt complete_menu_style=desc`  [ Note: `desc-raw` has been renamed to `desc` ].
