### ISSUE TITLE
[make 3.81] failed to install on macos

### ISSUE THREAD

**Issue by laoshaw** [akinomyoga/ble.sh#145]
version:  git master
default bash on macos

```
make -C ble.sh/ install PREFIX=~/.local
cp -p contrib/LICENSE.md out/doc/contrib/LICENSE.md
cp: out/doc/contrib/LICENSE.md: No such file or directory
make: *** [out/doc/contrib/LICENSE.md] Error 1
```

**Comment by akinomyoga** [comment]
### Re: Make error

> I `brew install make` and upgrade it from 3.81 to 4.3

Thank you! I have installed `make-3.81` in my local machine and confirmed that the problem reproduces. It turned out to be a bug of make-3.81. The problem doesn't exist in make-3.82. I have added a workaround for this at https://github.com/akinomyoga/blesh-contrib/commit/6dbe63dd3d48fa51b519cfb458991eb50f2acd4f.

### Re: Error messages on `decode.inputrc.adict.*`

> but blesh still not working fully.
>
> 1. if I add `source path/to/ble.sh` at the end of .bashrc, my iTerm2 will report some emacs and vi imap warnings.
> 2. if I use the trick1.3 on the README with .bashrc, I did not see those emacs/vi mapping warnings, which is what I'm using now. the errors are:
>
> ```
> -bash: /Users/user1/.cache/blesh/0.4/decode.inputrc.adict.xterm-256color.emacs: No such file or directory
> -bash: /Users/user1/.cache/blesh/0.4/decode.inputrc.adict.xterm-256color.vi_imap: No such file or directory
> -bash: /Users/user1/.cache/blesh/0.4/decode.inputrc.adict.xterm-256color.vi_nmap: No such file or directory
> ```

OK, I confirmed the problem in bash-3.2. I have added a fix 61705bf. You can update `ble.sh` by the `ble-update` command.

### Re: TAB completion problem

> if I do cd my and hit TAB it will show a menu to choose, if I choose 'mypaththen it becomescd mymypathinstead ofcd mypath`, so TAB is not working as expected.

I cannot reproduce this behavior, but this maybe caused by the combination of the above error and your settings, could you check if this problem is solved by `ble-update`?

### Re: No auto-complete

> and there is no hints when I do `cd` or other commands, ble.sh is smart to provide suggestions on my linux machine, but not on iTerm2.

The autosuggestions (which is called `auto-complete` in ble.sh) is only supported with Bash 4.0 and later.

> Just updated to bash version 5.1.8(1)-release (x86_64-apple-darwin20.3.0), same problem

Did you really tried with the newly installed Bash 5.1.8? I suspect you are still using bash-3.2. This is also consistent with the error messages of `decode.inputrc.adict.*` which are actually the bug of ble.sh with bash-3. To check the version of Bash that you are now using, you can input <kbd>C-x C-v</kbd> (Control+X and thn Control+V) or print `$BASH_VERSION`. If you want to check the path and the version of the current Bash binary, you can print "$BASH" and check the output.of `"$BASH" --version`.

This is the example in my host:

```bash
$      # <- type "C-x C-v"
GNU bash, version 5.0.11(1)-release (x86_64-redhat-linux-gnu)
ble.sh, version 0.4.0-devel3+12b067f (noarch)
$ echo "$BASH_VERSION"
5.0.11(1)-release
$ echo "$BASH"
/bin/bash
$ "$BASH" --version
GNU bash, バージョン 5.0.11(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
ライセンス GPLv3+: GNU GPL バージョン 3 またはそれ以降 <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
If you want to use the newly installed Bash as the login shell, you need to append the path to the new Bash to `/etc/shells` and then change your default shell using the `chsh` command. You can also check out [this StackoverExchange question and the answer](https://apple.stackexchange.com/a/232983/437969).

**Comment by laoshaw** [comment]
It all works now. You're correct I was stilling using the old bash, being new macos user here :(

Thank you so much. ble.sh becomes a must-have tool for me these days.

**Comment by akinomyoga** [comment]
Thank you for the confirmation! Also, thank you again for the report and replies!
