### ISSUE TITLE
ble.sh: owner of '' is not correct.

### ISSUE THREAD

**Issue by zim0369** [akinomyoga/ble.sh#163]
```
ble.sh: owner of '' is not correct.
```
I get this error whenever I switch to the root user.
I have installed ble.sh for both root and normal user.

**Comment by akinomyoga** [comment]
Thank you for the report. There seems to be a problem in the initialization stage, but it seems I cannot reproduce the problem in my environment.

- **Q1** Which operating system do you use?
- **Q2** How do you switch to the root user? For example, do you use `su` or `sudo` command? Which options/arguments do you specify?
- **Q3** I have fixed the error message (commit b547a41). Actually, the directory name is supposed to be shown between these `''` in the error message but was not shown because of another bug. After updating ble.sh using `ble-update`, what is shown between `''` in the error message when you switch to the root user?

**Comment by zim0369** [comment]
- Arch linux
- `su` - no arguments OR `su root`
- ```


~
  ❤ ble-update
cd into /opt/ble.sh...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 4 (delta 3), reused 4 (delta 3), pack-reused 0
Unpacking objects: 100% (4/4), 1.12 KiB | 34.00 KiB/s, done.
From https://github.com/akinomyoga/ble.sh
   144ea5d..b547a41  master     -> origin/master
Updating 144ea5d..b547a41
Fast-forward
 ble.pp   |  4 ++--
 note.txt | 23 +++++++++++++++++++++++
 2 files changed, 25 insertions(+), 2 deletions(-)
DEPENDENCIES_PHONY=1 DEPENDENCIES_OUTPUT=out/ble.dep DEPENDENCIES_TARGET=out/ble.sh FULLVER=0.4.0-devel3 \
  /usr/bin/gawk -f make/mwg_pp.awk ble.pp >/dev/null
bash make_command.sh install "out/ble.sh" "/home/zim/.local/share/blesh/ble.sh"
[ble: reload]
~
  ❤ su
Password:
ble.sh: owner of '' is not correct.
/home/zim
  ❤
-- INSERT --
```

**Comment by akinomyoga** [comment]
Thank you for the information.

> su - no arguments OR su root

- **Q4** Does the problem reproduce when you switch the user by `sudo -i` (assuming the user is one of sudoers)?


> ```
> ❤ su
> Password:
> ble.sh: owner of '' is not correct.
> /home/zim
>   ❤
> -- INSERT -
> ```

- **Q5** Do you source `/home/zim/.local/share/blesh/ble.sh` also from the root user? If Bash of the root user sources another `ble.sh` (e.g., `/root/.local/share/blesh/ble.sh`), could you please update that `ble.sh` (i.e., the one sourced from the root user) and try again `su`?

**Comment by zim0369** [comment]
Thank you!
- `sudo -i` works flawlessly
- I'm so dumb. I should've done `ble-update` as the root user. I did it now tho:
```
ble.sh: owner of '/run/user/1000/blesh' is not correct.
```

**Comment by akinomyoga** [comment]
> ```
> ble.sh: owner of '/run/user/1000/blesh' is not correct.
> ```

Hmm, OK! I think the problem is caused by the environment variable `XDG_RUNTIME_DIR=/run/user/1000` whose value was set up for the user `zim` but not updated for the root user. I confirmed the same behavior also with `sudo -E bash` in my Fedora.

I have searched about the behavior of `su` and found the following page:

- [753882 – pam_systemd should not use loginuid (at least not when used by su)](https://bugzilla.redhat.com/show_bug.cgi?id=753882#c104)

```
# Jeff Blaine 2020-07-09 22:28:20 UTC
Hitting this still in 2020 under RHEL 7.8.

# Michael McNamara 2021-09-13 17:27:48 UTC
For those poor souls that get here and see that it will never be
fixed:

Workaround: Add a line to the startup script of users that you
might like to su to, which removes the offending environment
variable XDG_RUNTIME_DIR

bash users:
unset XDG_RUNTIME_DIR

csh users:
unsetenv XDG_RUNTIME_DIR
```

This seems like a general issue with `su` and is unlikely to be fixed.

I added a workaround 8d37048. Now, ble.sh just ignores the wrongly set-up `XDG_RUNTIME_DIR` rather than showing proper warning messages. Can you again update ble.sh (by `ble-update` in the root user) and check the behavior? Thank you.

**Comment by zim0369** [comment]
> > ```
> > ble.sh: owner of '/run/user/1000/blesh' is not correct.
> > ```
> 
> Hmm, OK! I think the problem is caused by the environment variable `XDG_RUNTIME_DIR=/run/user/1000` whose value was set up for the user `zim` but not updated for the root user. I confirmed the same behavior also with `sudo -E bash` in my Fedora.
> 
> I have searched about the behavior of `su` and found the following page:
> 
> * [753882 – pam_systemd should not use loginuid (at least not when used by su)](https://bugzilla.redhat.com/show_bug.cgi?id=753882#c104)
> 
> ```
> # Jeff Blaine 2020-07-09 22:28:20 UTC
> Hitting this still in 2020 under RHEL 7.8.
> 
> # Michael McNamara 2021-09-13 17:27:48 UTC
> For those poor souls that get here and see that it will never be
> fixed:
> 
> Workaround: Add a line to the startup script of users that you
> might like to su to, which removes the offending environment
> variable XDG_RUNTIME_DIR
> 
> bash users:
> unset XDG_RUNTIME_DIR
> 
> csh users:
> unsetenv XDG_RUNTIME_DIR
> ```
> 
> I do NOT recommend the above workaround (`unset XDG_RUNTIME_DIR`). This seems like a general issue with `su` and is unlikely to be fixed.
> 
> I added a workaround [8d37048](https://github.com/akinomyoga/ble.sh/commit/8d370486d64b5eae25e2d0ac9d0611f5223b7904). Now, ble.sh just ignores the wrongly set-up `XDG_RUNTIME_DIR` rather than showing proper warning messages. Can you again update ble.sh (by `ble-update` in the root user) and check the behavior? Thank you.

The issue is now fixed. Thank you!

**Comment by akinomyoga** [comment]
OK! Thank you again for reporting the issue!
