### ISSUE TITLE
Shit-S prints a space when `bind Space:magic-space` is present in `.bahshrc`

### ISSUE THREAD

**Issue by returntrip** [akinomyoga/ble.sh#165]
**ble version**: 0.4.0-devel3+01643fa
**Bash version**: 5.1.8(1)-release (x86_64-redhat-linux-gnu)

When I comment out `bind Space:magic-space` in `.bashrc` I can then type uppercase "S" character.

I have tried creating a minimal `.bashrc` file containing only the below but the issue is still there. I have also tried changing terminal from alacritty to gnome-terminal but that does not help.

```
[[ $- == *i* ]] && source ~/.local/share/blesh/ble.sh --noattach
bind Space:magic-space
[[ ${BLE_VERSION-} ]] && ble-attach
```

**Comment by akinomyoga** [comment]
Thank you for the report! This was actually a regression of [`b6fc4f0`](https://github.com/akinomyoga/ble.sh/commit/b6fc4f03e5d6449e7976cb9fc4f360aed6e943ec#diff-3f46dca95427790dbbb364d92371c62104b8e571682dcb8817f3eeac9b697217R3390). I fixed it in commits a67458e and e363f1b and also added tests there. Could you update ble.sh using `ble-update` and check if the problem is solved?

**Comment by returntrip** [comment]
Confirming that it is working now. Thanks you for fixing it!

I forgot to add that as a workaround this would have also worked in `.inputrc`:

```
$if Bash
    Space: magic-space
$endif
```

**Comment by akinomyoga** [comment]
OK! Thank you again for the report!
