### ISSUE TITLE
Autocomplete bug

### ISSUE THREAD

**Issue by telometto** [akinomyoga/ble.sh#166]
**ble version**: 0.4.0-devel3+01643fa 
**Bash version**: 5.1.8
**OS and version:** Fedora 35

It seems like there is a bug of sorts when trying to autocomplete certain commands by hitting `TAB`. I stumbled across this when I hit `TAB` by accident before having entered the first letter of the package I was going to install. So far, the `pip` (`pip3` etc.) commands seem to be the only commands affected, but I will update if I notice other commands acting up.

**Steps to reproduce:**
1. Enter `pip3 install` (leave trailing space after `install`).
![k1](https://user-images.githubusercontent.com/65364211/148610371-3c38053a-8cae-4b8d-ba9d-3e540fb5ed46.png)

2. Hit `TAB`.
![k2](https://user-images.githubusercontent.com/65364211/148610881-9a73d217-4bf0-420e-ba32-2d3857a84378.png)

3. Press `BACKSPACE`.
![k3](https://user-images.githubusercontent.com/65364211/148611204-fe141f6c-426f-4ffd-a11e-daf9855b571a.png)

4. Press `BACKSPACE` again.
![k4](https://user-images.githubusercontent.com/65364211/148611273-41310065-4e8b-49b6-ab1e-76aee19b1c1d.png)

**Comment by akinomyoga** [comment]
Thank you for the report! OK, I could reproduce the behavior in GNOME terminal / Fedora 35.

----

This turned out to be related to the terminal behavior for the escape sequence <kbd>ESC [ *Ps* D</kbd> (the control function <kbd>CUB</kbd>) at the end of the line. Terminals can be classified into two classes using the result of the following command:

```bash
$ printf '%*s\e[10DX\n' $COLUMNS 0123456789
                                                                     X0123456789 <-- Class A
                                                                      X123456789 <-- Class B
```

- **Class A** xterm, vte (GNOME, terminator, xfce4, lxterminal), terminology, alacritty, urxvt, RLogin, mlterm, mintty, Cygwin console (pcon), Windows Terminal, Linux console, contour, VSCode terminal (xterm.js)
- **Class B** screen, tmux, kitty, konsole, contra, Poderosa, termit

One character shift is caused by this difference between terminals.

In commit 3e136a6, I decided to reduce the width of the completion menu by one character so that the cursor doesn't reach the end of the line (except for the terminals in a white list for Class B). @telometto Could you update ble.sh by `ble-update` and check the behavior? Thank you.

**Comment by telometto** [comment]
@akinomyoga Can confirm that updating fixes this behaviour.

Many thanks 🎉

**Comment by akinomyoga** [comment]
Thank you!
