### ISSUE TITLE
Breaks some bash-completions

### ISSUE THREAD

**Issue by SuperSandro2000** [akinomyoga/ble.sh#171]
**ble version**: 0.4.0-devel3+7d05a28
**Bash version**: 5.1.8(1)-release (x86_64-pc-linux-gnu)

Some tab completions are broken with ble.sh. For example ``nix-build -A``<kbd>Tab</kbd> does not work at all and ``ssh ho``<kbd>Tab</kbd> prefers files which contain the partial hostname instead of the parsed ssh_config results like bash_completions does.
I currently have `bleopt complete_auto_complete=` set to work around this but I would like to know if this is the right solutions or those are bugs.
Also sometimes directories no longer append a trailing slash even if not ambiguous which makes completing paths a lot harder since you manually need to append a slash every time.

You can find the source for the nix-build completion script here https://github.com/hedning/nix-bash-completions/blob/master/_nix plus I am using this PR https://github.com/hedning/nix-bash-completions/pull/17/files.

**Comment by akinomyoga** [comment]
> Some tab completions are broken with ble.sh. For example `nix-build -A`Tab does not work at all

I haven't tried the completion setting you have specified because it seems to depend on the actual binary `nix`, so I guess I need to get the actual NixOS system in order to reproduce the issue. I'm now busy so I think I cannot soon prepare a NixOS system. Could you dig it down at your side to see what is happening inside ble.sh until I find some time?

> `ssh ho`Tab prefers files which contain the partial hostname instead of the parsed ssh_config results like bash_completions does.

The problem doesn't seem to reproduce in my environment. It correctly parses my `ssh_config` and show the hostnames. I'm using the latest `master` of [`bash-completion`](https://github.com/scop/bash-completion). Which version of `bash-completion` do you use for the `ssh` completion setting? Or are you actually talking about the completion for `nixops ssh`?

> I currently have `bleopt complete_auto_complete=` set to work around this but I would like to know if this is the right solutions or those are bugs.

Hm. That's weird. The TAB completion and auto-completion are completely independent, so the setting of `complete_auto_complete` shouldn't affect the behavior of TAB completion. Could you really work around the problem by that setting?



> Also sometimes directories no longer append a trailing slash even if not ambiguous which makes completing paths a lot harder since you manually need to append a slash every time.

This also doesn't reproduce in my environment. If you are loading `bash-completion`, the completions are written for each command so we need to know with whcih command the problem reproduces. Could you provide us with the actual command that reproduces the above behavior?

**Comment by SuperSandro2000** [comment]
> I guess I need to get the actual NixOS system in order to reproduce the issue.

You just need the nix package manager for that. The docker image should already be enough. But I can try later try to debug this further.

> Which version of bash-completion do you use for the ssh completion setting?

A version from November last year. I try updating and let you know if that changes something.

Edit: I am on commit 9357f35eeb36797bbfd5ff95c6261d1d04f84a6f and still the same.

I noticed something after updating that this only happens for the first time I try to complete for ssh. The second time everything works like it should. The output of ``complete -p`` is ``complete -o bashdefault -o default -F _fzf_host_completion ssh``. I know that `_fzf_host_completion` is just shimming ``_ssh`` which is only loaded when a command is attempted to be completed for the first time.

> Or are you actually talking about the completion for nixops ssh?

No, normal openssh ssh.

> Could you really work around the problem by that setting?

Yeah, since setting I think all problems I described are solved. Not sure from where this is coming. Maybe something about my environment is very special or half broken? Not sure where to start searching though.

> Could you provide us with the actual command that reproduces the above behavior?

I could just reproduce it with directories which are symlinks. This is very common for nixpkgs. I have https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A77-Completion#user-content-rlvar-mark-symlinked-directories set. No matter how often I press <kbd>Tab</kbd> here nothing happens other than that the text blinks.

![image](https://user-images.githubusercontent.com/7258858/151009409-13f12ddf-d18c-435a-b01c-ec09e4484f5a.png)

**Comment by akinomyoga** [comment]
> > I guess I need to get the actual NixOS system in order to reproduce the issue.
> 
> You just need the nix package manager for that. The docker image should already be enough. But I can try later try to debug this further.

I'm currently thinking that I install it in a Linux instance in one of my virtual machines. Currently simply running the instruction on the NixOS page fails with the error of `sudo systemctl link /.../nix-daemon.service`.

> I noticed something after updating that this only happens for the first time I try to complete for ssh. The second time everything works like it should. The output of `complete -p` is `complete -o bashdefault -o default -F _fzf_host_completion ssh`. I know that `_fzf_host_completion` is just shimming `_ssh` which is only loaded when a command is attempted to be completed for the first time.

I see. I guess this is related to the fzf's completion settings which tries to rewrite the completion in the completion function itself. I'll later try it if the behavior reproduces with fzf completion settings.

> > Could you really work around the problem by that setting?
> 
> Yeah, since setting I think all problems I described are solved. Not sure from where this is coming. Maybe something about my environment is very special or half broken? Not sure where to start searching though.

OK, then I need to look at it after I set nix packages up.

> > Could you provide us with the actual command that reproduces the above behavior?
> 
> I could just reproduce it with directories which are symlinks.

Thank you! I could reproduce the behavior. I'll look at it later. Something strange is that, in one of my computers, the slashes are inserted after the symbolic links to directories as expected while another computer with exactly the same version of Bash and ble.sh doesn't insert the slashes.

**Comment by SuperSandro2000** [comment]
> Can't NixOS used with SELinux?

I don't know. Never used it. NixOS can be over installed over another OS but it makes it his home. You can install nix, the package manager, on any other OS and it is pretty easy to remove it again.

> Something strange is that, in one of my computers, the slashes are inserted after the symbolic links to directories as expected while another computer with exactly the same version of Bash and ble.sh doesn't insert the slashes.

I know this feeling. My terminal has bugs with tmux which only occur on one machine.

**Comment by akinomyoga** [comment]
Hi, thanks for your reply. I'm busy this week so will look at them next week. Thanks

**Comment by akinomyoga** [comment]
## Re: nix-build -A [TAB] does not work

I've finally set nix up in one of my Linux host and tried the above completion. However, it doesn't seem to work even without ble.sh. Is there any additional settings to make it work? I have tried it with the following commands.

```bash
$ bash --norc
$ source ~/.mwg/git/scop/bash-completion/bash_completion
$ source _nix
$ nix-build -A [TAB]
```

- I'm using the latest commit of bash-completion [afe81d3](https://github.com/scop/bash-completion/commit/afe81d35d4309599573586437e3e7803afbb6649)
- As for `_nix`, I've tried [the latest master](https://github.com/hedning/nix-bash-completions/blob/e6db3081fe1f221470a26e345a96855e5f09ddec/_nix) and [your customized version](https://github.com/hedning/nix-bash-completions/blob/5d28f3de9244ccf679630770b90448a22a65aced/_nix), but both didn't work.
- I'm running the above command in the terminal of the host Linux system, but do I need to try the completion to reproduce the problem within some special environment provided by nix? I actually don't know how to use nix correctly.

## Re: ssh ho[Tab]

I have fixed it in commit 82b9c01. This reproduces when both `bash-completion` and `fzf/completion.bash` are loaded. The  Bash progcomp system allows completion functions to exit with 124, which instructs Bash to retry the programmable completion from the beginning. In Bash Manual, the feature of exit status 124 is described as useful for the default completion settings. I have been misunderstood as this special treatment of exit status 124 is only present for the default completion, but today I realized that the exit status 124 is processed for the other specific completions as well.

## Re: suffixing symlinked directories with a slash

I have written that in some systems a slash is suffixed and in some other systems it's not suffixed. I've identified that the difference between these two sets of systems is actually caused by the readline setting [`mark-symlinked-directories`](https://bash.cyberciti.biz/bash-reference-manual/Readline-Init-File-Syntax.html). 

In ble.sh, when `mark-symlinked-directories` is turned off, it will never suffix symlinked directory names with a slash. However, I today noticed that Readline actually suffix the directory names with a slash even if `mark-symlinked-directories` is turned off but the word that is already input by the user is already a complete symbolic name. I've followed the behavior of Readline in commit 397ac1f.

## Re: About the workaround `bleopt complete_auto_complete=`

I still don't think that this could change the behavior if you are using ble.sh with the default values for the other settings. However, I came up with a possibility that you would actually have a custom keybinding to <kbd>TAB</kbd> in `auto_complete` keymap? Anyway, if all the problems are solved in the latest master, we can forget about this unexpected workaround.

Thank you.

**Comment by SuperSandro2000** [comment]
> Is there any additional settings to make it work?

I always forget that you are not that familiar with nix. `-A` is used when building packages from a local checkout of nixpkgs. I should have mentioned that. If you clone https://github.com/nixos/nixpkgs/ and do in the root directory ``nix-build -A hello`` something should happen.

> Re: ssh ho[Tab]

I can confirm that this is now fixed. Thank you very much.

> Re: suffixing symlinked directories with a slash

I think that is not working as intended yet. When I try to complete symlink to and normal directories for example after `cat` I now never get the directory slash. I have ``set mark-symlinked-directories on`` in m ``.inputrc``.

> Re: About the workaround bleopt complete_auto_complete=


I think that was related to loading the completion. When I now do ``nix-build -A hell`` <kbd>Tab</kbd> I get the completion.

**Comment by akinomyoga** [comment]
> > Is there any additional settings to make it work?
> 
> I always forget that you are not that familiar with nix. `-A` is used when building packages from a local checkout of nixpkgs. I should have mentioned that. If you clone https://github.com/nixos/nixpkgs/ and do in the root directory `nix-build -A hello` something should happen.
>
> > Re: About the workaround bleopt complete_auto_complete=
> 
> I think that was related to loading the completion. When I now do `nix-build -A hell` Tab I get the completion.

OK, I have tried it. It seems to work.

> > Re: ssh ho[Tab]
> 
> I can confirm that this is now fixed. Thank you very much.

Thank you for the check!

> > Re: suffixing symlinked directories with a slash
> 
> I think that is not working as intended yet. When I try to complete symlink to and normal directories for example after `cat` I now never get the directory slash. I have `set mark-symlinked-directories on` in m `.inputrc`.

It works in my environment. What is the output of the following command in a ble.sh session in your environment?

```console
$ bind -v | grep mark
set mark-directories on
set mark-modified-lines off
set mark-symlinked-directories on
```

**Comment by SuperSandro2000** [comment]
```ShellSession
$ bind -v | grep mark
set mark-directories on
set mark-modified-lines off
set mark-symlinked-directories on
```

**Comment by akinomyoga** [comment]
Thank you. I think I need to ask many questions to identify the cause. Anyway, this is the first round:

- **Q0** Can you provide me with an example directory contents where the slash is not inserted for the subdirectories and the symbolic links? I'd like to check the possibility that other filenames inhibits the completion. For example,

  ```bash
  $ echo subdir[TAB] # <-- slash is not inserted in this directory
  $ ls
  file subdir symlink # <-- this is an example
  ```

- **Q1** Does the problem reproduce with the plain Bash + ble.sh? You can start it by the following command:

  ```bash
  $ INPUTRC=/dev/null bash --norc --noprofile
  $ source /path/to/ble.sh --norc
  ```

  If it doesn't reproduce, some settings in the system profile `/etc/profile`, a user inputrc `~/.inputrc`, or a `~/.bashrc` / `~/.bash_profile` causes the problem. Could you identify which setting causes the problem?
- **Q2** Does the problem reproduce when `auto-complete` and related features are turned off?

  ```bash
  bleopt complete_auto_complete=
  bleopt complete_menu_filter=
  bleopt complete_auto_menu=
  ```

**Comment by SuperSandro2000** [comment]
Nope. I tried your above examples and cannot reproduce it anymore. Could it be that it was related to the bash-completions not loading? I should really write down how I produced a bug in the first place because I can no longer remember or reproduce it.

**Comment by SuperSandro2000** [comment]
Nope. I tried your above examples and cannot reproduce it anymore. Could it be that it was related to the bash-completions not loading? I should really write down how I produced a bug in the first place because I can no longer remember or reproduce it.

**Comment by akinomyoga** [comment]
OK, fine. I have actually tested it locally with/without `bash-completion` and with/without `fzf/completion.bash`+`contrib/fzf-completion`, and it seems to be working in any combination. Maybe you have been using an older version of `ble.sh` mistakenly while you could reproduce it last time. We can wait for a while for whether the problem arises again in your environment. If it doesn't reproduce anymore, I guess we can close the issue.

**Comment by SuperSandro2000** [comment]
The bug just found me again!

When I do ``cat ~/.config``<kbd>Tab</kbd> nothing happens. That is not the case for ``echo ~/.config``<kbd>Tab</kbd>.

```ShellSession
$ complete -p cat
complete -F _fzf_path_completion cat
```

```ShellSession
$ type cat
cat is a function
cat() {
  if [[ -p /dev/stdout || ! -t 1 || $* =~ --help ]]; then
    command cat "$@"
  else
    _bat "$@"
  fi
}
cat is /usr/bin/cat
cat is /bin/cat
```

After doing `ble-detach` everything works again. I tried removing the function but that did not change something

```ShellSession
$ type cat
cat is /usr/bin/cat
cat is /bin/ca
```

I think the culprit is `~`. When changing to `~` and doing ``cat .config``<kbd>Tab</kbd> the `/`is ammended.

**Comment by akinomyoga** [comment]
Great! I could reproduce it. This is again caused by some interaction with `fzf` completion. I'll later look at it.

**Comment by akinomyoga** [comment]
@SuperSandro2000 This was caused by how the candidates generated by the `fzf` completion are processed and also related to some workarounds in `contrib/fzf-completion.bash`. I have improved the treatment of the generated candidates in commit 0a42299.

**Comment by SuperSandro2000** [comment]
Works now. Thank you very much!

**Comment by akinomyoga** [comment]
Thank you!

**Comment by ferdinandyb** [comment]
Sorry for writing in a closed issue, but it is not clear from here, that should fzf work with ble.sh out of the box, or is there something I would need to do? If it should I'll open a new issue with what is broken for me.

**Comment by ferdinandyb** [comment]
Never mind, I found it in contrib.

**Comment by akinomyoga** [comment]
xref #206
