### ISSUE TITLE
blesh tries to open files which do not exist

### ISSUE THREAD

**Issue by SuperSandro2000** [akinomyoga/ble.sh#179]
**ble version**: 0.4.0-devel3+398e404
**Bash version**: 5.1.12(1)-release (x86_64-pc-linux-gnu)

ble.sh tries to open some files which do not exist when opening a nix-shell.

```ShellSession
$ nix-shell -p hello
bash: ble-edit/exec/save-BASH_REMATCH: No such file or directory
bash: ble-edit/exec/restore-BASH_REMATCH: No such file or directory
```

**Comment by akinomyoga** [comment]
Thank you for the report! I have pushed a fix 689534d. This was an issue with the initialization order. I have moved related functions and refactored them. Could you check it?

**Comment by SuperSandro2000** [comment]
Thanks! That fixed it.

I noticed another thing: When exiting the shell blesh is exited twice. Not very important and I am not sure if there are actually two shells nested.

```ShellSession
$ nix-shell -p hello
$ exit
[ble: exit]
[ble: exit]
```

**Comment by akinomyoga** [comment]
> I noticed another thing: When exiting the shell blesh is exited twice. Not very important and I am not sure if there are actually two shells nested.

Hmm, interesting. It doesn't reproduce outside `nix-shell`.

OK, I found that the `EXIT` trap set by `nix-shell` actually calls `exit` again.

```bash
[nix-shell:~]$ trap -p EXIT
trap -- 'exitHandler' EXIT

[nix-shell:~]$ type exitHandler
exitHandler is a function
exitHandler ()
{
    exitCode="$?";
    set +e;
    if [ -n "${showBuildStats:-}" ]; then
        read -r -d '' -a buildTimes < <(times);
        echo "build times:";
        echo "user time for the shell             ${buildTimes[0]}";
        echo "system time for the shell           ${buildTimes[1]}";
        echo "user time for all child processes   ${buildTimes[2]}";
        echo "system time for all child processes ${buildTimes[3]}";
    fi;
    if (( "$exitCode" != 0 )); then
        runHook failureHook;
        if [ -n "${succeedOnFailure:-}" ]; then
            echo "build failed with exit code $exitCode (ignored)";
            mkdir -p "$out/nix-support";
            printf "%s" "$exitCode" > "$out/nix-support/failed";
            exit 0;
        fi;
    else
        runHook exitHook;
    fi;
    exit "$exitCode"
}
```

But I wonder why it would need to run `exit` again inside the `EXIT` trap. This will unexpectedly terminate `ble.sh`'s internal cleanup codes. I think this is a general problem. For example, when another configuration appends its cleanup code as `trap -- "$original_handler; __another_cleanup__" EXIT` where `$original_handler` contains `exitHook`, the appended cleanup code will never be executed because `exitHook` terminates the shell in the middle of the `EXIT` trap. Shouldn't the last line be `return "$exitCode"`?

**Comment by SuperSandro2000** [comment]
I have created to https://github.com/NixOS/nixpkgs/pull/161079 change that behavior but it will take a while until it hits master because it will require a rebuild of everything.

**Comment by akinomyoga** [comment]
@SuperSandro2000 Thank you for opening the PR!

Nevertheless, maybe there are other user configurations that call `exit` in trap `EXIT`. In commit f62fc04, I changed `exit` (which is overridden by `ble/builtin/exit`) not to output `[ble: exit]` when it is processing the previous `exit`.

Also, in f62fc04 and 6fdabf3, I changed the behavior of `exit` (`ble/builtin/exit`) to defer exiting the shell until all the trap handlers are processed. Now, even when multiple cleanup codes are registered to blehook `EXIT` and trap `EXIT` and some of them explicitly execute `exit`, it doesn't prevent other cleanup codes from running, so that all the cleanup codes are still correctly executed. The final exit status of the Bash process will be that of the last invocation of `exit`. This is an example:

```bash
$ bash-dev
$ blehook EXIT+='echo "cleanup (1) in blehook EXIT";exit 1;echo NOT_REACHED'
$ blehook EXIT+='echo "cleanup (2) in blehook EXIT";exit 2;echo NOT_REACHED'
$ blehook EXIT+='echo "cleanup (3) in blehook EXIT";exit 3;echo NOT_REACHED'
$ trap 'echo "cleanup in trap EXIT";exit 5;echo NOT_REACHED' EXIT
$ exit
[ble: exit]
cleanup (1) in blehook EXIT
cleanup (2) in blehook EXIT
cleanup (3) in blehook EXIT
cleanup in trap EXIT
[ble: exit 5, elapsed 52.822s, CPU 27.5% (self)usr1ms/sys3ms+(child)usr13.691/sys842ms] bash-dev
$
```

**Comment by akinomyoga** [comment]
@SuperSandro2000 It seems https://github.com/NixOS/nixpkgs/pull/161079 has been already merged. Can I close the issue?

**Comment by SuperSandro2000** [comment]
So far it didn't hit master so I couldn't fully test it but your other work around already fixed the problem.

**Comment by akinomyoga** [comment]
Thank you.
