### ISSUE TITLE
freebsd

### ISSUE THREAD

**Issue by lu9dce** [akinomyoga/ble.sh#184]
tested on freebsd 13 (ok)
is needed to compile
have gmake and gawk installed

create a bash link
ln -s /usr/local/bin/bash /bin/bash

**Comment by SuperSandro2000** [comment]
@akinomyoga Can we replace the shebangs with `#/usr/bin/env bash`?

**Comment by lu9dce** [comment]
yes .. !! 
#/usr/bin/env bash 
it would be correct

**Comment by akinomyoga** [comment]
> create a bash link
> ln -s /usr/local/bin/bash /bin/bash

These shebangs are actually **not used** because all the ble.sh files are sourced instead to be run by `exec`, so the above settings should not be needed. Or have you experienced any actual problems? At least ble.sh just works in FreeBSD in my environment.

I put these shebangs just for some old text editors not correctly recognizing the language of the files. Even that dummy shebangs will be stripped in the installation phase. The only script run in the installation phase is `make_command.sh`, but you can see that I set the shebang of that file to `#!/usr/bin/env bash`.

**Comment by akinomyoga** [comment]
> It doesn't reproduce in my environment.
> 
> > make -C ble.sh
> > gives error because it cannot locate the bash
> 
> That gives an error because it is not gmake (GNU make) in BSD by default, but it is BSD make. You need to run `gmake -C ble.sh`. Ah, OK. I have mentioned that in [the later section in README](https://github.com/akinomyoga/ble.sh#generate), but didn't mentioned it in the quick instructions at the beginning.

**Comment by akinomyoga** [comment]
(Ah, sorry. I have mistakenly closed the issue. I have reopened it.)

> in my case it didn't work until I create the bash link

Didn't you change other configurations (such as the installation of gmake or the PATH settings for make) at the same time?

> the scripts that are inside with extension .sh contain #!/bin/bash and that path is wrong for freebsd bash on freebsd is in /usr/local/bin
> the files that are in ble.sh/lib with extension sh also indicate the path with /bin/bash

As explained, these are dummies and **not actually used** so shouldn't affect the behavior.

If you are really sure that the problem is caused by these shebangs, could you provide us with the error message produced by `make -C ble.sh`?

**Comment by lu9dce** [comment]
ok can't reproduce the error
also my post was to comment
what's on freebsd

I congratulate you, it's very good
We'll see in a few weeks if I can add it
to the official freebsd repository

**Comment by akinomyoga** [comment]
Thanks, I'll later consider adding a fallback Makefile for BSD make to explicitly delegate the processing to gmake.

**Comment by akinomyoga** [comment]
I have added a fallback `Makefile` for BSD make in commit e5d8d00.
