### ISSUE TITLE
Trying for first time

### ISSUE THREAD

**Issue by jw-miaem** [akinomyoga/ble.sh#188]
Hello been jealous of zsh-autocomplete for ages but never made the switch. I've been trying this out today and noticed a couple things that are possible bugs but might be possibly something else as my bash profile has become over crowded

The couple things that might be worth looking into and/or I possibly need help with (On mac laptop 2019 Monterey iTerm2 Build 3.4.15):

I have a reload alias "source ~/.bash_profile". For some reason whenever I run this I get [ble: reload] and end up with a floating cursor

![Screenshot 2022-04-24 at 6 03 14 pm](https://user-images.githubusercontent.com/778991/164987943-72011676-603e-40ee-bedc-8fd9c9752614.png)

and log file:
[24/04/2022, 6:02:56.576 pm] ❯  rreloadeloadloadoadaddd
[24/04/2022, 6:03:00.357 pm] [ble: reload]
[24/04/2022, 6:03:03.469 pm] xxxx
[24/04/2022, 6:03:03.473 pm] Sun Apr 24 18:03:03 BST 2022

[24/04/2022, 6:03:03.717 pm] ~ 
[24/04/2022, 6:03:03.717 pm] ❯  
[24/04/2022, 6:03:03.832 pm] ~ 
[24/04/2022, 6:03:03.832 pm] ❯    
[24/04/2022, 6:03:03.854 pm] ble: TERM has changed. rebinding...

Second issue is inconsistent behaviour when opening a split pane in iTerm2

I cd into a directory and then split pane I'm back in home directory. I go back to previous pane and try again and end up in correct/expected directory

~~I've just switched of oh-my-bash and while the floating cursor still exists the split pane issue doesn't?~~

~~split pane seems to have disappeared and switching to bash-it seems to work fine~~

from more tinkering I think I have conflicts somewhere but not sure where at the moment

**Comment by jw-miaem** [comment]
think I have this working now - thanks loads for getting this to work 🙌

**Comment by akinomyoga** [comment]
Thank you for the report. Maybe you have already fixed the problem, but here are my replies. First of all, I don't have macOS, so I'm sorry that I cannot locally try iTerm2 to see what's happening.

> I have a reload alias "source ~/.bash_profile". For some reason whenever I run this I get [ble: reload]

This message is expected. `ble.sh` outputs `[ble: reload]` when it is loaded for the second or more times in a Bash session. It depends on the setup, but typically `/.bash_profile` internally sources `~/.bashrc`, and `~/.bashrc` sources `ble.sh`, so the message is shown

> and end up with a floating cursor

This is not expected behavior. I think this is caused by interference between `ble.sh` and other configurations.
- First, have you already tried the setup described in [README §1.3](https://github.com/akinomyoga/ble.sh#13-set-up-bashrc)? `ble-attach` needs to be placed at the very end of `~/.bashrc` (but not in another file sourced from `~/.bashrc`, etc.).
- Also, `ble.sh` assumes `PROMPT_COMMAND` doesn't output anything to stdout/stderr, which is actually expected also by Bash/Readline.

> Second issue is inconsistent behaviour when opening a split pane in iTerm2
> 
> I cd into a directory and then split pane I'm back in home directory. I go back to previous pane and try again and end up in correct/expected directory
> 
> ~I've just switched of oh-my-bash and while the floating cursor still exists the split pane issue doesn't?~
> 
> ~split pane seems to have disappeared and switching to bash-it seems to work fine~
> 
> from more tinkering I think I have conflicts somewhere but not sure where at the moment

It might be related to the iTerm2 shell-integration. To identify the problem, maybe you could try turning off the shell integration and see if the problem persists.

Anyway, if you have solved the problem, that's fine. Thank you!
