### ISSUE TITLE
How does the readline replacement work?

### ISSUE THREAD

**Issue by xAspirus** [akinomyoga/ble.sh#191]
how is it able to replace the readline library

**Comment by akinomyoga** [comment]
Is this a question or do you have an actual problem in the replacement by `ble.sh`? `ble.sh` uses `bind -x`. You may find it by the following command.

```bash
$ builtin bind -X
```

**Comment by xAspirus** [comment]
i want to write my own readline replacement for bash but in python

**Comment by akinomyoga** [comment]
It depends on the use case. I think the standard way is to re-implement the C API of Readline in your line editor and link Bash with that line editor at the build time, which is a completely different approach from that of `ble.sh`. Or it might also be possible to build Bash linked with shared Readline and replace it using `LD_RELOAD` (but I'm not sure if it is actually possible). I don't know if it is a good idea or not, but if you would use the same approach as `ble.sh` (which is written in a Bash script), you would first need to write a Bash script that bridges between Bash and Python.

**Comment by akinomyoga** [comment]
@xAspirus Do you have further questions about this? If not, can I close the issue?

**Comment by xAspirus** [comment]
i don't get how ble.sh does it

**Comment by akinomyoga** [comment]
Thanks. So, what can I help you? What is the question? I have explained the idea in https://github.com/akinomyoga/ble.sh/issues/191#issuecomment-1114926472. Have you read the description of `bind -x` in Bash Reference Manual, or have searched for the explanation on `bind -x` of Bash? When you have questions on the usage of `bind -x` or you have problems using `bind -x`, maybe you can ask it here.

**Comment by xAspirus** [comment]
```
-x keyseq:shell-command

    Cause shell-command to be executed whenever keyseq is entered. When shell-command is executed, the shell sets the READLINE_LINE variable to the contents of the Readline line buffer and the READLINE_POINT and READLINE_MARK variables to the current location of the insertion point and the saved insertion point (the mark), respectively. If the executed command changes the value of any of READLINE_LINE, READLINE_POINT, or READLINE_MARK, those new values will be reflected in the editing state.
```

**Comment by akinomyoga** [comment]
What is the question?

**Comment by dualbus** [comment]
@xAspirus If you need further assistance, consider asking in help-bash@gnu.org. That would be the right place to ask this sort of question.

Although as @akinomyoga explained previously, if your goal is to replace the readline library, then you'll need to write your own shared library and link bash against it. This is much easier said than done.

If you want to change what readline does for specific sequence of keys, you can use `bind -x`. This will allow you to call an external command (python if you want) in response to a sequence of keys. But you will still need to have a Bash function wrapping your python command, so that you can interact with the magic readline shell variables (READLINE_LINE, READLINE_POINT, or READLINE_MARK).

I'm curious as to why you'd want to do something like this. It's much easier to customize what readline does than it is to replace it completely.

**Comment by akinomyoga** [comment]
@xAspirus Can I close the issue?
