### ISSUE TITLE
Bash 4.4 crashes upon sourcing ble.sh/out

### ISSUE THREAD

**Issue by notmike-5** [akinomyoga/ble.sh#195]
**ble version**: 
https://github.com/akinomyoga/ble.sh/commit/a4a779e45d4a8b1037ed49fb5953db94b07e5715

**Bash version**: 
4.4.0(1)-release (x86_64-unknown-linux-gnu)

I get to this point:

git clone --recursive https://github.com/akinomyoga/ble.sh.git
make -C ble.sh
source ble.sh/out/ble.sh

and then I receive the error:

Warning: Program '/path/to/my/bin/bash' crashed.

Then its lights out for my terminal. I have to close the frame and begin again. However, the make seemed to work fine.

**Comment by akinomyoga** [comment]
Thank you for the report! Currently, it seems I do not experience the problem with Bash 4.4.23.

- Could you check the behavior for [CHK0004](https://github.com/akinomyoga/ble.sh/wiki/Questions-for-bug-reports#chk0004) and [CHK0005](https://github.com/akinomyoga/ble.sh/wiki/Questions-for-bug-reports#chk0005)?
- Also, I would appreciate it if you could copy and paste the result of pressing <kbd>C-x C-v</kbd> (i.e., prss Control+X and then Control-V) in the ble.sh session.
- What is your Linux distribution?

**Comment by akinomyoga** [comment]
I have locally built and tried Bash 4.4.0, but it seems to work with ble.sh in my environment (Fedora 36).

On the other hand, I'm not sure if this is related, but I found that the `scp` completion from the latest version of bash-completion causes the crash of Bash 4.2..4.4 due to the corrupted malloc/free invocation. This reproduces without ble.sh.

> source ble.sh/out/ble.sh
> 
> and then I receive the error:
> 
> Warning: Program '/path/to/my/bin/bash' crashed.

- **Q4** Does this happen immediately after the source of `ble.sh`? Or does it happen after you type something?
- **Q5** What is your terminal?
- **Q6** Could you check the error message by the following sequence?

1. Open a terminal
2. Run `bash` to enter a child Bash session
3. Run `source ble.sh/out/ble.sh` to source `ble.sh` in the child session. This is supposed to make the child session crash. I think the error message will remain in the terminal.

**Comment by akinomyoga** [comment]
ping @notmike-5

**Comment by akinomyoga** [comment]
@notmike-5 Hi, have you already solved the problem? If you are busy, maybe you could just tell me which Linux distribution you have been using when the problem arose so I can try to reproduce the problem by setting up the same Linux distribution in a virtual machine on my side. Thank you.

**Comment by akinomyoga** [comment]
@notmike-5 Recently, in #202, we found that some broken timestamps in `~/.bash_history` causes a segmentation fault with Bash 4.4 or lower. I have added a workaround for #202 in commit 5ef28eb. I'm not sure if it is related to the crash that you observed, but maybe you can try the latest version of ble.sh.

**Comment by akinomyoga** [comment]
ping @notmike-5

**Comment by akinomyoga** [comment]
@notmike-5
