### ISSUE TITLE
bind: warning: line editing not enabled

### ISSUE THREAD

**Issue by wukuan405** [akinomyoga/ble.sh#200]
```bash
$ echo $BLE_VERSION
0.4.0-devel3+e4afb5a

$ echo "$BASH_VERSION ($MACHTYPE)"
5.1.4(1)-release (x86_64-pc-linux-gnu)
```

問題報告
```
bash ~/.local/share/blesh/ble.sh --update
~/.local/share/blesh/ble.sh: line 3670: bind: warning: line editing not enabled
~/.local/share/blesh/ble.sh: line 5333: bind: warning: line editing not enabled
~/.local/share/blesh/ble.sh: line 3670: bind: warning: line editing not enabled
~/.local/share/blesh/ble.sh: line 5333: bind: warning: line editing not enabled
~/.local/share/blesh/ble.sh: line 5333: bind: warning: line editing not enabled
~/.local/share/blesh/ble.sh: line 5333: bind: warning: line editing not enabled
```

**Comment by akinomyoga** [comment]
Thank you for the report! I've confirmed the problem. I'll fix it later. These are just warning so you can continue to use `ble.sh` until I fix the problem.

ご報告ありがとうございます。問題を手許で再現することができましたので後はこちらで対応いたします。警告メッセージは出ていますが動作自体に問題はないはずですので、こちらで修正するまでそのままお使いいただいて問題ありません。以降、日本語でのサポートをご希望でしたらその旨お知らせくださいませ。

**Comment by akinomyoga** [comment]
The problem has been caused by a recent commit 6d20f51. I've pushed a fix 1e19a67.

Could you check if the problem is fixed? Note that the first trial of `bash .../ble.sh --update` will still produce the warning because it is still in the older version. After updating to 1e19a67, you can try again `bash out/ble.sh --update` to see if the warning has disappeared in the latest version. Thank you!

**Comment by wukuan405** [comment]
Thanx
