### ISSUE TITLE
Incomplete history scanning (up arrow)

### ISSUE THREAD

**Issue by johnyaku** [akinomyoga/ble.sh#202]
お世話になっております。

**ble version**:  0.4.0-devel3+1e19a67
**Bash version**: 4.2.46(2)-release

After (re)installing ble.sh the up arrow no longer gives me the most recent command. Instead, it seems to get stuck on a particular command. New commands continue to be added to `~/.bash_history`

History related settings:
HISTCONTROL=ignoredups
HISTFILESIZE=
HISTSIZE=
PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

I'm working in a cluster environment with sometimes multiple sessions over multiple nodes. But this also happens when only connected to the login node.

Ble.sh is activate by a simple `source` in my `.bashrc`, as I found that the more elaborate invocation caused all commands to hang.

**Comment by akinomyoga** [comment]
Thank you for the report! I've tried your settings of the history but It seems I cannot reproduce it in my environment with Bash 4.2 [4.2.53(2)-release (x86_64-unknown-linux-gnu) in Fedora 36].

> ```bash
> PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"
> ```

Could you try `bleopt history_share=1` instead of the above setting to see if the situation changes? `bleopt history_share` is a more efficient implementation of `history -a && history -c && history -r`.

**Comment by johnyaku** [comment]
Thank you.

I commented out the `PROMPT_COMMAND` settings and enabled `bleopt history_share=1`. Interestingly when I first `ssh` in to the cluster I get the same odd behaviour as before. That is, the up arrow brings up a history entry about 20,000 items old. However,  once I type a new command, the up arrow starts behaving as expected, so within any session the up arrow now works as expected. If I log out and back in again, I see the same old history item again. But new items are again available for scrolling via the up and down arrows.

Slightly odd behaviour, but working well enough to be useful again.

In the process of editing the `share_history` option I discovered that I was using a very old `.blerc` from an older version. After swapping out for a `.blerc` file based on the latest template, I discovered a lot of new options that I am looking forward to exploring!

**Comment by akinomyoga** [comment]
Thank you for the information! Then, I think the problem is not completely solved. First, I would like to make it work with typical `history -a && history -c && history -r`. Also, even without it, it seems the problem is still present before you run a command. Can I ask more questions to identify the problem? First of all, I would like to know the result of [CHK0004](https://github.com/akinomyoga/ble.sh/wiki/Questions-for-bug-reports#chk0004) [Note: this might truncate your history file, so please back up your history file (`~/.bash_history` by default) before trying CHK0004].

**Comment by johnyaku** [comment]
Thanks for following up.

The problem still occurred after CHK0004.  I forgot to backup `.bash_history` but it survived intact. Stranglely `history | tail` ends with the problem record (the one that appears when I press the up arrow key) even though `tail .bash_history` shows the last few commands entered. 

I suspect the problem might have more to do with the `history` command than the `.bash_history` file. Although I had always assumed that the `history` command was just `cat .bash_history` under the hood.

Happy to run other checks to help get to the bottom of this.

**Comment by akinomyoga** [comment]
Thank you! Hmm, it is interesting that `history` does not produce the expected result.
- Can you check the value of `HISTFILE` at the beginning of `.bashrc`?
- Can you also check the behavior with [CHK0005](https://github.com/akinomyoga/ble.sh/wiki/Questions-for-bug-reports#chk0005)? This time, please do not forget about backing up the history!
- Which operating system (and the distribution if it is Linux) do you use? Do you use NixOS, which does something non-trivial using the system bashrc/profile?

**Comment by johnyaku** [comment]
Problem fixed! I inspected `$HOME/.bash_history` and found that the hash tag timestamp for the record that kept on being displayed whenever I first pressed the up arrow was twice as long as all the other timestamps for some reason. I'm not sure how this happened -- perhaps the file became corrupted? In any case, deleting the offending record and its timestamp fixed the problem :) 

So not strictly a `ble.sh` problem, although the problem only surfaces when I enable ble.sh. 

Working through your questions helped me to get to the bottom of this, so I will include the answers below for completeness:

===

`HISTFILE` is reported as being at `$HOME/.bash_history` as expected, at both the beginning and end of `.bashrc`.

When I do CHK0005, the up arrow works as expected immediately after I run `PS1='$ ' INPUTRC=/dev/null bash --norc --noprofile` but reverts back to the odd behaviour as soon as I source `ble.sh`

The operating system is CentOS Linux release 7.9.2009 (Core)
The kernel is 3.10.0-1160.42.2.el7.x86_64

My `.bashrc` also activates `conda` and [apparix](https://github.com/micans/apparix) but deactivating these does not fix the problem.

**Comment by akinomyoga** [comment]
Thank you!

> I inspected `$HOME/.bash_history` and found that the hash tag timestamp for the record that kept on being displayed whenever I first pressed the up arrow was twice as long as all the other timestamps for some reason. I'm not sure how this happened -- perhaps the file became corrupted? In any case, deleting the offending record and its timestamp fixed the problem :)

Ah, OK. Maybe there is a certain trouble when `ble.sh` analyzes the unexpected format of `history`, though I'm not either sure what was happening here exactly.

- Do you still have the offending history-timestamp line in some backup? If it is still reproducible, could you provide me with the offending line?
- If my guess is correct, it might be related to the multiline support of `ble.sh`. If the problem is still reproducible, could you check if the situation changes by partially turning off the feature by putting the following line after the `source` of `ble.sh`?

```bash
ble/function#push ble/history:bash/resolve-multiline true
```

**Comment by johnyaku** [comment]
Luckily my history was backed up! 

Here are the offending f lines:
```
vim .bashrc           <--- an example of a normal record
#1656625044           <--- an example of a normal time stamp
gs                    <--- this is just an alias for 'git status'
#1647948811646449694  <--- this time stamp seems to be causing the problem
```

Re-inserting the offending lines back into `.bash_history` and then following your suggestion _does_ fix the problem. And when I re-examine `.bash_history` after logging out and then back in again I see that the offending timestamp has been truncated to be the same length as the others.

Still not sure how this odd time stamp was generated in the first place, but your suggestions have fixed the problem!

Thank you for your persistence! お疲れ様でした！

**Comment by akinomyoga** [comment]
Thank you very much! I could reproduce the problem at my side. Interestingly, I found that Bash crashes by the command `HISTTIMEFORMAT=%s history` with the history containing the offending line (even without ble.sh).

```bash
$ cat D                           <--- I have put the offending timestamp in a manually created history file "D"
#1656625044
echo 1
#1656625044
echo 2
#1647948811646449694
echo a
#1656625044
echo b
#1656625044
echo c
$ HISTFILE=D bash-4.2 --norc      <--- start a plain Bash with the history file D
$ HISTTIMEFORMAT=%s history       <--- this command causes the segfault
    1  1656625044echo 1
    2  1656625044echo 2
Segmentation fault (core dumped)
```

Bash 5.0+ doesn't seem to result in the segmentation fault but instead outputs some error messages. I guess this was fixed by https://lists.gnu.org/archive/html/bug-bash/2018-06/msg00033.html

I'll later consider workarounds for these Bash behavior with broken history timestamps. Anyway, thanks for your report and quick responses! ご丁寧に数々の質問に対応いただきましてこちらこそありがとうございます! また他に何かありましたら何なりとお申し付けくださいませ。

**Comment by akinomyoga** [comment]
> ```shell
> ble/function#push ble/history:bash/resolve-multiline true
> ```

Ah, I forgot to tell that the above line is just a temporary setting for debugging, so please remove it after the testing. I haven't carefully designed `ble.sh` so that the above command works properly in every case, so it might cause other problems in other edge cases.

**Comment by johnyaku** [comment]
I've deleted the line.
Thanks again for following up on this.

**Comment by akinomyoga** [comment]
I have added a workaround for this issue in commit 5ef28eb. It seems to be impossible to robustly get the current history in a way that the multiline history entries are preserved with the old versions of Bash that fails with the segmentation violation when there is a broken timestamp. Now, with Bash 4.4 or below, `ble.sh` still cannot load the entire history but instead shows the warning about the broken timestamps.
