### ISSUE TITLE
[starship] `$_` does not match the last argument of the previous command

### ISSUE THREAD

**Issue by aiotter** [akinomyoga/ble.sh#215]
**ble version**: 0.4.0-devel3+a450775
**Bash version**: 5.1.16(1)-release (x86_64-apple-darwin17.7.0)

```
GNU bash, version 5.1.16(1)-release (x86_64-apple-darwin17.7.0)
ble.sh, version 0.4.0-devel3+a450775 (noarch)
bash-completion, version 2.11 (hash:994f7fc2c6b882b1824292e24ab548c975647e0c, 76390 bytes) (noarch)
starship, version 1.9.1 (rustc 1.61.0, 1980-01-01 00:00:00 +00:00)
locale: LANG=en_US.UTF-8 LC_COLLATE=C
terminal: TERM=screen-256color wcwidth=14.0-west/14.0-2+ri, tmux:0 (84;0;0)
```

According to `man bash`, special parameter `_` refers to the last argument to the previous command.
However, it changes to some ble.sh command after sourcing it.

```bash
$ echo hello
hello
$ echo $_
ble/util/setexit "$_ble_edit_exec_TRAPDEBUG_lastexit" "$_ble_edit_exec_TRAPDEBUG_lastarg";LINENO=$_ble_edit_LINENO builtin eval 'starship_preexec "$_"'
```

This breaks my favourite sequence of commands like `mkdir test; cd $_`.

Sorry if it is an already reported behaviour. I checked the closed and opened issues carefully, but `$_` is too difficult to search because it consists only of symbols.

**Comment by akinomyoga** [comment]
This is caused by a conflict on the `DEBUG` trap with `starship`. Both ble.sh and starship want to use the DEBUG trap, so one that sets the DEBUG trap needs to emulate the behavior of the DEBUG trap for the other. This poses some limitations in exactly reproducing the behavior of the DEBUG trap. `$_` is one of them.

I actually implemented a partial workaround for this problem for the other traps but hadn't for the DEBUG trap. I've pushed commit 0b95d5d where I have applied the partial fix to the DEBUG trap, but this is still a partial fix. With the current implementation, we cannot still restore multiline `$_`. If `$_` contains newlines, currently only the first line is restored. I'm not even sure if there is a perfect solution that works with arbitrary third-party DEBUG traps.

In the case of `starship`, a perfect solution would be to let starship use `blehook PREEXEC` instead of `DEBUG`. Starship utilizes the DEBUG trap to mimic the behavior of Zsh's preexec, which is actually provided as `blehook PREEXEC` by ble.sh. I think the easiest way is to put the following setting in `.blerc` since [starship seems to use bash-preexec, if it is present, instead of DEBUG](https://github.com/starship/starship/blob/018b077630bd6eb6dc858e65c04bbfd19b40198c/src/init/starship.bash#L69-L73) (For this workaround to work, the initialization of starship needs to be put after the `source` of ble.sh).

```
# blerc
ble-import contrib/bash-preexec
```

Another solution without the `bash-preexec` interface is to add a code for `blehook` in `starship` just like the code for bash-preexec.

**Comment by aiotter** [comment]
I added `contrib/bash-preexec` and now it seems to work nicely! I really appreciate your clear description and quick solution.
I'll close this issue. Please reopen it if you need. Thanks again🙏
