### ISSUE TITLE
[Bash 5.0] Incomplete if, for, and while constructs in multi-line mode cause the shell to exit on ctrl-j

### ISSUE THREAD

**Issue by kjkuan** [akinomyoga/ble.sh#218]
**ble version**:  0.4.0-devel3+0b95d5d
**Bash version**: 5.0.17(1)-release (x86_64-pc-linux-gnu)

Typing any of these in the command line and hit `Enter` enters multi-line mode, but then crashes if one immediately hits `ctrl-j` to execute the incomplete command:
- `if :; then`
- `while :; do`
- `for i in a; do`

**Comment by akinomyoga** [comment]
Thank you for the report! But this is a bug of Bash 5.0, which [I have reported to the upstream Bash two years ago](https://lists.gnu.org/archive/html/bug-bash/2020-08/msg00152.html) and fixed in [commit c261f9b8 in Bash's `devel` branch](https://git.savannah.gnu.org/cgit/bash.git/commit/?id=c261f9b80c421e90407ecebde7077fbd54c61d9b). As far as I know, there is no workaround. You need to be careful when you run multiline commands, or you need to update your Bash to Bash 5.1 to avoid the problem.

**Comment by kjkuan** [comment]
ah, I see. I didn't know that. I'll close the issue then. Thanks!

**Comment by akinomyoga** [comment]
Anyway, thank you for reporting the issue!
