### ISSUE TITLE
Multiline mode in Octopi

### ISSUE THREAD

**Issue by throwaway36493** [akinomyoga/ble.sh#220]
**ble version**: 0.4.0-devel3+a450775
**Bash version**: 5.1.16
 
Great project, except one annoyance: whenever I run [Octopi](https://github.com/aarnt/octopi) (A Pacman frontend for ArchLinux) and try to install or upgrade from its terminal, I got a multiline mode input before asking me for the password, so I need each time to press C-j:
![Screenshot_20220731_202918-1](https://user-images.githubusercontent.com/110353910/182043395-3c77813d-b339-40a3-85cb-4e96d1826340.png)
It should be like this:
![Screenshot_20220731_203326](https://user-images.githubusercontent.com/110353910/182043461-fa404b25-18da-49ce-8c68-1b4870c653a5.png)

Is there a way to disable/bypass the multiline mode in this case?

**Comment by akinomyoga** [comment]
I think this is because Octopi writes multiline commands to the terminal, though I have never used Octopi. By default, ble.sh detects multiline write and enters the multiline editing mode. You can configure the behavior by the option [`bleopt accept_line_threshold`](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A74-Editing#user-content-bleopt-accept_line_threshold). To run the command even when the multiline commands are written at the same time, you can use the following setting:

```bash
# ~/.blerc

bleopt accept_line_threshold=-1
```

**Comment by throwaway36493** [comment]
ありがとうございました!

**Comment by akinomyoga** [comment]
Thanks! こちらこそ問い合わせいただきありがとうございます!
