### ISSUE TITLE
Cannot copy text

### ISSUE THREAD

**Issue by atimeofday** [akinomyoga/ble.sh#228]
Blesh version: 0.4.0-devel3+793dfad
Bash version: 5.1.16(1)-release (x86_64-pc-linux-gnu)

I am unable to copy to the system clipboard with keyboard shortcuts.

**Comment by akinomyoga** [comment]
Right. The *kill ring* of the line editor and the *clipboard* of X Window System, etc. are independent, so the keybindings that operate on the former do not affect the latter.

If you want to send the selected part to the clipboard, you need to set up the keybindings by yourself using the system-dependent commands that can be used to manipulate the clipboard. **It depends on the detailed setup and also what behavior you exactly expect**, but, for example, suppose your system has `xsel` and you are using the emacs editing mode in ble.sh, you may add the following keybinding:

```bash
function ble/widget/atimeofday/copy {
  ble/widget/copy-region-or copy-backward-uword
  xsel -bi <<< "${_ble_edit_kill_ring[0]}"
}
ble-bind -f M-w atimeofday/copy
```

**Comment by atimeofday** [comment]
This worked beautifully, thank you! 

The only minor issue with it is that it seems to copy a newline (\n?) with whatever I select, but that should be manageable if it can't be tweaked. 

I'd like to bind it to C-c, but M-c is infinitely better than not being able to copy, and opening up C-c wouldn't be a job for ble.sh as far as I know.

**Comment by akinomyoga** [comment]
> The only minor issue with it is that it seems to copy a newline (\n?) with whatever I select, but that should be manageable if it can't be tweaked.

Ah, OK. You can write as follows if you don't need the newline.

```bash
function ble/widget/atimeofday/copy {
  ble/widget/copy-region-or copy-backward-uword
  ble/util/put "${_ble_edit_kill_ring[0]}" | xsel -bi
}
ble-bind -f M-w atimeofday/copy
```

> I'd like to bind it to C-c, but M-c is infinitely better than not being able to copy, and opening up C-c wouldn't be a job for ble.sh as far as I know.

In the emacs editing mode, <kbd>C-c</kbd> can be used to clear the current line. Also, in the vim editing mode, it has other meanings. Nevertheless, as you don't seem to use it usually, you can go ahead and bind it to <kbd>C-c</kbd> instead of <kbd>M-w</kbd>. (Do I need to explain how to do that? You can just replace `M-w` with `C-c` in the line `ble-bind ...`.)

**Comment by atimeofday** [comment]
Thank you for the detailed response! I had assumed the newline was an unavoidable quirk; that works even better. Good to know that C-c should work, but it's treated/intercepted as a SIGINT, which I haven't been able to change. From what I've researched/heard, stty intr [new binding] should do it, but it doesn't work. If I find a way to do that, I'll remember to rebind it here.

**Comment by akinomyoga** [comment]
> Good to know that C-c should work, but it's treated/intercepted as a SIGINT, which I haven't been able to change.

Have you actually tried it?

Binding it to `C-c` should work regardless of whether it is treated as SIGINT in running the user commands. This is because <kbd>C-c</kbd> is translated to SIGINT only while user commands are running. When the command line is edited, the translation from <kbd>C-c</kbd> to SIGINT is turned off by line editors. In fact, just binding to <kbd>C-c</kbd> works in my environment.

If you actually tried the keybinding to <kbd>C-c</kbd> and confirmed that it doesn't really work in your environment, I think that is a bug that I need to fix. In that case, could you provide me with your detailed setup of blerc (ble.sh init file)?

**Comment by akinomyoga** [comment]
@atimeofday Can I close the issue?

**Comment by atimeofday** [comment]
I have indeed tried binding all forms of copy / copy-region-or copy-backward-uword to C-c. For some reason SIGINT only works on C-S-c, even though it's supposedly bound to C-c.

I think I actually figured out the issue. I had to bind the terminal copy shortcut to something ELSE. The terminal copy shortcut doesn't work and prevents other things from working. I'm using Guake but I saw the same behavior on several other terminals. With Guake's copy shortcut set to M-c (or something else) and the Blesh copy script you gave me bound to C-c, it seems to be working. It seems I can finally copy and paste everywhere with the same shortcuts again. I'm not sure exactly why it works, but it does... Thank you for the help!

**Comment by akinomyoga** [comment]
Ah, OK. That makes sense. The terminal keybindings are processed first before the terminal sends the key input information to the terminal application, which means that the key input C-c will not be sent to the terminal applications including ble.sh when C-c is set to a "copy" at the terminal side.

**Comment by atimeofday** [comment]
Good to know. Thanks again for the help! I've been quite enjoying several things ble.sh can do, and I'm glad things are working smoothly again with it!

**Comment by akinomyoga** [comment]
Thanks!
