### ISSUE TITLE
Cannot limit to use basic colours

### ISSUE THREAD

**Issue by StavromulaBeta** [akinomyoga/ble.sh#233]
**ble version**: 
0.4.0-devel3+793dfad
**Bash version**: 
5.2.0(1)-rc2 (x86_64-pc-linux-gnu)

I would like Ble.sh to only use the 16 basic terminal colours, since those are the colours of my preferred theme. However, setting the config option `bleopt term_index_colors=0` as the documentation suggests does not change this, as (for example) file paths are still shown in colour #26.

**Comment by akinomyoga** [comment]
`bleopt term_index_colors` is used to tell ble.sh about the color support of the terminal that you use, so if you specify *a value inconsistent with the actual color support of your terminal*, the resulting behavior is not necessarily the one you expect. In fact, ble.sh combines several ways to detect the color support of the terminal, and if ble.sh detects the support for the indexed colors in another way, ble.sh still tries to use the indexed colors.

Maybe I can adjust the behavior so that `bleopt term_index_colors` overrides the other detection mechanisms.

**Comment by StavromulaBeta** [comment]
That makes sense. Maybe not have `bleopt term_index_colors` override but instead have that as the maximum number of colours to use(?)

**Comment by akinomyoga** [comment]
Thanks, I'm currently thinking of making `term_index_colors=auto` (or `-1`) default, with which the other detection is used, and let it override the other detection only when `term_index_colors` is set to an integer value.

**Comment by StavromulaBeta** [comment]
Yes that seems like sensible behavior

**Comment by akinomyoga** [comment]
I have supported it in 7d238c0. Could you update ble.sh by running `ble-update` in a ble.sh session and see if it works as you expect? Thank you!

**Comment by StavromulaBeta** [comment]
Oops sorry only just got the notification for this. I updated it and it worked perfectly!! Thanks again!

**Comment by akinomyoga** [comment]
OK! Thank you for checking!
