### ISSUE TITLE
Completion of type `complete -C keg keg`

### ISSUE THREAD

**Issue by BuddhiLW** [akinomyoga/ble.sh#255]
**ble version**: 0.3.3+7fa584c
**Bash version**: 5.1.16(1)-release (x86_64-pc-linux-gnu)

## Context
I'm using some programs written in `Go`, which handle the completion by themselves, instead to delegate to bash-builtin `complete` etc. `keg` is one of these programs[^1].

So, in `.bashrc`, I only state:
```bash
complete -C keg keg
```

## Example and Issue
If I run a bash terminal (using `st`, `xterm`), **without ble.sh** and press 
```sh
keg <TAB> <TAB>
``` 
I have the following:
![ArcoLinux_2022-12-01_17-36-37](https://user-images.githubusercontent.com/59554283/205154400-39d4f4f8-e033-4e20-844f-1de185c607ac.png)

With `ble.sh`, I have a completion of the current directory (I/O type), instead:
![ArcoLinux_2022-12-01_17-38-16](https://user-images.githubusercontent.com/59554283/205154678-f8778c4e-9b5d-4e22-9b5b-eee277b5fd03.png)

[^1]:[https://github.com/rwxrob/keg](https://github.com/rwxrob/keg)

**Comment by akinomyoga** [comment]
Thank you for your report! You seem to be using ble-0.3. Could you try ble-0.4 to see if the problem persists there? There are many fixes and improvements in the programmable-completion system. Currently, I'm not planning to port a fix to 0.3 because the structure has been largely changed, and the porting is not possible unless we replace the entire code of programmable completion in 0.3 with that of 0.4.

**Comment by BuddhiLW** [comment]
Just installed the latest version; it works wonderfully!

Thanks, so that has to do with version 0.3.

It's a awesome piece of software. Really greateful for it.

**Comment by akinomyoga** [comment]
Thank you for checking!
