### ISSUE TITLE
Muted or black and white colors

### ISSUE THREAD

**Issue by auwsom** [akinomyoga/ble.sh#258]
I'm happy to find this great Auto-suggestion utility.

Is there anyway to get less colorful output? Either more muted colors lie Gruvbox theme, or just black and white?

I used the following to get more Fish-like colors:
`ble-color-setface auto_complete fg=242,bg=235`

I realize this might lose information about the various states the suggestions is in, but it would be less visually distracting.

Thank you!

**Comment by akinomyoga** [comment]
Thank you for trying ble.sh! First, which version of ble do you use? If you are using 0.3, I think it is useful to switch to 0.4 in which there are additional color configurations.

Have you checked the first item in [README §2.2](https://github.com/akinomyoga/ble.sh#22-disable-features)? There are color settings for different levels in ble.sh, but I think it is useful to first check README §2.2.

```bash
# blerc

bleopt highlight_syntax=
```

If that is not what you want, there are other options:

If you want to turn off all the colors used by ble.sh, you can put the following lines in `~/.blerc`:

```bash
# blerc

bleopt term_index_colors=2
_ble_term_colors=2
```

If you want to change the settings of all the faces at once, you may find [the answer in #223](https://github.com/akinomyoga/ble.sh/discussions/223#discussioncomment-3494599) useful.

```bash
# blerc

eval "$(ble-face | sed -En '/=ref:|(^|,)bold(,|$)/!s/$/,bold/p')"
```

Or, of course, you can always configure the faces (listed by `ble-face`) one by one to a less colorful one.

```bash
$ ble-face     # <-- You can list faces by this command.
```

In that case, I'm also welcome for new themes, which configure colors using a set of calls of `ble-face` (a new name of `ble-color-setface`) as discussed in #210.

Also, if your terminal has a support for the 24-bit terminal colors, you might be interested in [the `contrib/colorglass` module](https://github.com/akinomyoga/blesh-contrib/tree/a2c0ee084d5eb144d543ff03a7530e9f7d306631#pencil-colorglass).

If these are all not what you want, I would appreciate it if you could explain what you exactly would like to achieve and how it is different from the above settings in order to help improve ble.sh. Thank you!

**Comment by akinomyoga** [comment]
> Also, if your terminal has a support for the 24-bit terminal colors, you might be interested in [the `contrib/colorglass` module](https://github.com/akinomyoga/blesh-contrib/tree/a2c0ee084d5eb144d543ff03a7530e9f7d306631#pencil-colorglass).

I have newly added options `bleopt colorglass_saturation` and `bleopt colorglass_brightness` to the `contrib/colorglass` module. If your terminal has support for the 24-bit terminal colors, another option is to configure ble.sh in the following way:

```bash
# blerc

ble-import contrib/colorglass
bleopt colorglass_saturation=-50     # <-- decrease saturation by 50%
```

If you would like to get the grayscale theme, another possible configuration is this:

```bash
# blerc

ble-import contrib/colorglass
bleopt colorglass_saturation=-100     # <-- decrease saturation by 100%
```

**Comment by auwsom** [comment]
That is great 👍. I will try that.

I'm really enjoying this utility. I've been telling a bunch of people about it on twitch. A couple mentioned the bright colors, so I think this will really help. Cheers

**Comment by akinomyoga** [comment]
Can I close the issue? Thank you.

**Comment by auwsom** [comment]
Yes, thanks.

**Comment by akinomyoga** [comment]
Thank you!

**Comment by auwsom** [comment]
@akinomyoga hi, when I use `ble-color-setface auto_complete fg=242,bg=235`, it removed the colors, however, I cant seem to get them back, even after setting `ble-color-setface auto_complete=`. 

Where are these settings stored? in a config file? Thanks

**Comment by akinomyoga** [comment]
I might not understand the question. Are you asking for a way to restore the default colors? Or are you asking for a way to configure the color for all the sessions (instead of the temporary setting for the current session)?

----

In the former case, do you still use ble-0.3? If you have switched to ble-0.4, you can restore the original setting by

```bash
$ ble-face -r auto_complete
```

I recommend you switch to ble-0.4, but if you still use ble-0.3, there is no way to automatically restore the default setting by a command. You can directly specify the default setting (which is described in README):

```bash
$ ble-color-setface auto_complete fg=238,bg=254
```

---

In the latter case, you can put the setting in your `~/.blerc` (or `~/.config/blesh/init.sh`).

**Comment by auwsom** [comment]
@akinomyoga  thanks for the quick reply. I'm trying to restore colors. I've used ble-update to the newest version. Unfortunately,the `$ ble-face -r auto_complete` command doesnt work.. the colors are still just black and white.

I just commented out the lines in my .blerc and the colors are back. That must have been it. Thanks
```
#bleopt term_index_colors=2
#_ble_term_colors=2
#ble-bind -m 'auto_complete' -f TAB auto_complete/insert-on-end
#ble-bind -m 'auto_complete' -f C-i auto_complete/insert-on-end
```

**Comment by auwsom** [comment]
sorry that was a silly question.. i skimmed past the ~/.blerc in the main GH page and in the Manual.

Quick question though.. since Blesh is autosuggesting some history, is there a way to get a tab-completion menu of just history? I see options for filenames, hostnames, username, commands and variable, but history would be awesome. It would likely be so much faster than ctrl-R search history line by line.

**Comment by akinomyoga** [comment]
> since Blesh is autosuggesting some history, is there a way to get a tab-completion menu of just history?

I once thought about it, but haven't yet implemented it. I'll put it on the to-do list.

**Comment by auwsom** [comment]
That's great :+1: 

One more question.. I have a Bash Trap DEBUG line to add `--help` to a command with `help` after it. However, Blesh seems to break that function. Possibly because of other Bash Trap usage?
