### ISSUE TITLE
Recipe R4: git subdirectory case

### ISSUE THREAD

**Issue by lcpz** [akinomyoga/ble.sh#267]
Hi Koichi, thank you for `ble.sh`!

I am using your recipe [R4](https://github.com/akinomyoga/ble.sh/wiki/Recipes#r4-show-current-working-directory-and-git-branch-in-right-prompt). However, when I `cd` to a subdirectory which is itself a Git repository, the right prompt will still show the current branch and commit of the parent Git directory.

I'd like to see this info for the *current* directory. Can you please show me how? Thanks in advance.

**Comment by akinomyoga** [comment]
Hi, thank you for using `ble.sh`!

The reason that the configuration doesn't detect the submodule git directory is related to the following part of the recipe:

```bash
    if [[ -f $path/.git/HEAD ]]; then
      git_base=$path
      return 0
    fi
```

The above code only recognizes the git directory that has a subdirectory `.git` containing a file `HEAD`. This fails for the submodule git directories or other special types of git repositories because such a git directory instead has a regular file `.git` whose text content specifies the path to the actual `.git` directory of the submodule.

So if you are interested in supporting it by yourself, you can update the above part of the code in the recipe so that it additionally detects a regular file `$path/.git` and reads the content of the file.

If you are fine to just use an existing one, an upgraded version of the recipe is actually provided as [`contrib/prompt-git`](https://github.com/akinomyoga/blesh-contrib/blob/4fc0bf65458c45c5619902160d30ee3631fdf6bb/prompt-git.bash#L18-L43). For example, you can rewrite the recipe in the following way:

```bash
ble-import contrib/prompt-git

function ble/prompt/backslash:X {
  ble/prompt/backslash:contrib/git-info ||
    ble/prompt/process-prompt-string '\w'
  return 0
}
bleopt prompt_rps1='\X'
```

The detailed explanations for the other `ble/prompt/backslash:contrib/git-*` are found in [the corredponding section of `README` of `contrib`](https://github.com/akinomyoga/blesh-contrib/tree/4fc0bf65458c45c5619902160d30ee3631fdf6bb#pencil-contribprompt-git).

**Comment by lcpz** [comment]
The `contrib/prompt-git` version is exactly what I was looking for, thanks!

**Comment by akinomyoga** [comment]
Thanks!
