### ISSUE TITLE
redraw of prompt on resize of window

### ISSUE THREAD

**Issue by EryX666** [akinomyoga/ble.sh#276]
**ble version**:  0.4.0-devel3+a144ffa
**Bash version**:  5.2.2(1)-release (x86_64-pc-linux-gnu)

A video example of the problem:
https://imgur.com/sBtro3a

the culprit of this bug is that ble.sh is shipped with 
`#bleopt canvas_winch_action=redraw-here`
by default instead of value `clear` by default
this is more of a suggestion then a bug/ problem but i think more people will find this as a problem more then a suggestion because this behavior is not really normal and with combination with oh-my-posh / oh-my-zsh will cause a lot of problem.
the redraw also happens on lose focus and focus of the terminal as well as re-sizing of the window.

tested in Gnome terminal and in Alacritty - same behavior.

----

**Edit** by @akinomyoga: Refs:

- [Terminal resize causes redraw of shell : linux4noobs](https://www.reddit.com/r/linux4noobs/comments/10w5gx2/terminal_resize_causes_redraw_of_shell/)

**Comment by bkerin** [comment]
I tried with =clear in pursuit of another small issue and it results in a bad behavior for me because I flood terminal with blanks to ensure input area is always at bottom of shell (and near the status bar).  =clear breaks this by putting me back at the top

**Comment by EryX666** [comment]
> I tried with =clear in pursuit of another small issue and it results in a bad behavior for me because I flood terminal with blanks to ensure input area is always at bottom of shell (and near the status bar). =clear breaks this by putting me back at the top

have you tried `redraw-prev`?

**Comment by akinomyoga** [comment]
Thank you for the report. I receive many reports about this behavior, but I don't know what I really can do. I find Readline's default behavior (`redraw-prev`) more problematic, while I understand that ble.sh's default (`redraw-here`) doesn't really *look* good. The problem of `redraw-prev` is explained in https://github.com/akinomyoga/ble.sh/issues/142#issuecomment-950036015, where `bleopt canvas_winch_action` is first introduced. Consider the case that one runs a command that takes a long time to calculate something and outputs a bit long text unfitting in the current terminal window, and then one tries to expand the terminal window to find that the last part of the output is lost forever by `redraw-prev`.

> with oh-my-posh / oh-my-zsh will cause a lot of problem.

I understand that replicating the prompts is ugly, but I'm curious what are the other problems. I believe that the loss of the previous command results by `redraw-prev` is more serious than the ugly looking, but if there are real problems with `redraw-here`, I need to think about another solution.

The root cause of this problem is that the terminal text reflowing really depends on the terminal. I would say not a single terminal behaves exactly the same as another terminal. It is unpredictable on the side of the terminal application unless we implement an algorithm for each version of each terminal emulator. The discussion of text reflowing is also found in [README of powerlevel10k (which is a Zsh plugin)](https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window).

**Comment by EryX666** [comment]
> Thank you for the report. I receive many reports about this behavior, but I don't know what I really can do. I find Readline's default behavior (`redraw-prev`) more problematic, while I understand that ble.sh's default (`redraw-here`) doesn't really _look_ good. The problem of `redraw-prev` is explained in [#142 (comment)](https://github.com/akinomyoga/ble.sh/issues/142#issuecomment-950036015), where `bleopt canvas_winch_action` is first introduced. Consider the case that one runs a command that takes a long time to calculate something and outputs a bit long text unfitting in the current terminal window, and then one tries to expand the terminal window to find that the last part of the output is lost forever by `redraw-prev`.
> 
> > with oh-my-posh / oh-my-zsh will cause a lot of problem.
> 
> I understand that replicating the prompts is ugly, but I'm curious what are the other problems. I believe that the loss of the previous command results by `redraw-prev` is more serious than the ugly looking, but if there are real problems with `redraw-here`, I need to think about another solution.
> 
> The root cause of this problem is that the terminal text reflowing really depends on the terminal. I would say not a single terminal behaves exactly the same as another terminal. It is unpredictable on the side of the terminal application unless we implement an algorithm for each version of each terminal emulator. The discussion of text reflowing is also found in [README of powerlevel10k (which is a Zsh plugin)](https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window).

Thanks for the comment, i accept what your saying.
My experience with oh-my-posh and ble.sh have been good for the most part, but sometimes using the `redraw-here` with the autocomplete can cause problems, for example, if the autocomplete cant fit in one line because the window is too small and you get it highlighted and you want to delete the last part of the command or change something in the middle of the command sometimes it starts deleting the oh-my-posh prompt and even goes to delete the last bit of output you had and causes me to delete the whole prompt, clear, resize the window so the command will fit and wont cause this problam and then run it again with the changes, ill try to replicate it for you to investigate this problem, it might not be related to `redraw-here` but it only happens to me while using ble.sh.

**Comment by akinomyoga** [comment]
Does it mean there is no problem that overwrites the oh-my-posh prompt when you use ble.sh with `redraw-prev`? Naively I don't think the auto-complete/editing behavior is changed by `canvas_winch_action` because `canvas_winch_action` only affects the behavior on resizing.

If there is a problem, it might possibly be caused by conflicts between the treatment of the right prompt of Oh My Posh and the layout calculation of ble.sh. Anyway, I'll wait for your next report about the issue. Thank you!

**Comment by akinomyoga** [comment]
@EryX666 I have again adjusted `redraw-here` to go back to the line that can be guessed to be probably safe to overwrite in commit a125187.

The condition is still heuristic and not complete, so there are still cases where we need to print the prompts in new lines. For example, when one uses the *right prompt* (through `bleopt prompt_rps1` or by putting control sequences in `PS1`), it is hard to make sure that the previous lines do not contain the command outputs after the text reflowing. But, unless you use the right prompts, I guess it would work fine in most cases now.

**Comment by akinomyoga** [comment]
> ill try to replicate it for you to investigate this problem, it might not be related to `redraw-here` but it only happens to me while using ble.sh.

@EryX666 May I ask if you are still planning to discuss the above issue here? If not, can I close the issue? I think that is an issue separate from the behavior of `redraw-here`. You can later create a separate Issue when you have time.

**Comment by EryX666** [comment]
> > ill try to replicate it for you to investigate this problem, it might not be related to `redraw-here` but it only happens to me while using ble.sh.
> 
> @EryX666 May I ask if you are still planning to discuss the above issue here? If not, can I close the issue? I think that is an issue separate from the behavior of `redraw-here`. You can later create a separate Issue when you have time.

Closed :)

**Comment by akinomyoga** [comment]
Thanks!
