### ISSUE TITLE
"unbound keyseq: [" on initial load

### ISSUE THREAD

**Issue by miba072** [akinomyoga/ble.sh#28]
**ble version**: 0.3.0+c2a268a
**Bash version**: 5.0.7

When initially starting a new bash session I always get "unbound keyseq: [" followed by ?6c in the terminal, ble.sh continues to work fine but it's annoying having to clear the screen every time. I'm using bash 5.0.7 on Arch Linux with vi-mode enabled in .inputrc.
![2019-07-16-234442_grim](https://user-images.githubusercontent.com/44232850/61332623-00ab6680-a825-11e9-9d2f-ac39b9ea4d2b.png)
![2019-07-16-234500_grim](https://user-images.githubusercontent.com/44232850/61332631-0739de00-a825-11e9-96b5-d68091ce1fd8.png)

**Comment by akinomyoga** [comment]
Thank you for the report. I couldn't reproduce this, but I fixed according to my guess (d793ebd) to recognize `DA1`. I also applied a change which was made in `v0.4.0-devel` to `v0.3.0` (25e8d2f) to ignore entire unrecognized CSI sequences. Could you try the latest version to check if the problem is solved? (You can update `ble.sh` by `ble-update`.)

Actually my guess is your terminal responds with `DA1` (<kbd>ESC [ ? Pm c</kbd>) for `DA2` request (<kbd>ESC [ &gt; c</kbd>). Could I ask what is your terminal?

**Comment by miba072** [comment]
I am using alacritty 0.3.3 and your latest version does indeed fix the bug! :) I tried the previous version in lxterminal and it didn't exhibit the bug so maybe it is a bug in alacritty not responding to the escape sequence properly, maybe a bug report should be made to them too?

Thank you very much for the quick fix.

**Comment by akinomyoga** [comment]
Thank you for the information! I took a glance at the codes of `alacritty`. The <kbd>DA1</kbd> response is issued [here (alacritty/mod.rs)](https://github.com/jwilm/alacritty/blob/9a159a77604e0354f1176b02ff700bc11da19c86/alacritty_terminal/src/term/mod.rs#L1592) which is called from [here (alacritty/ansi.rs)](https://github.com/jwilm/alacritty/blob/9a159a77604e0354f1176b02ff700bc11da19c86/alacritty_terminal/src/ansi.rs#L931). It seems that the `alacritty` doesn't check intermediate bytes of CSI sequences and just sees the last byte to determine the control function associated with the CSI sequence. So `alacritty` cannot distinguish <kbd>DA2</kbd> request (<kbd>CSI &gt; c</kbd>) and even <kbd>DA3</kbd> request (<kbd>CSI = c</kbd>) from <kbd>DA</kbd> / <kbd>DA1</kbd> request (<kbd>CSI c</kbd>).

> maybe it is a bug in alacritty not responding to the escape sequence properly, maybe a bug report should be made to them too?

I'm not sure if it should be regarded as a "bug" of `alacritty` because there is no formal standard for these "private CSI sequences". <kbd>DA</kbd> is defined in so-called "ANSI Standard" (ANSI X3.64, ECMA-48 and ISO/IEC 6429), but the CSI sequences that starts with `<`, `=`, `>`, `?` are designated as "private sequences" and the meaning can be defined by implementations. In this sense, if it's the design of `alacritty`, it's not a bug.

But now ANSI standard is something like archaic documents since the last version (ISO/IEC 6429:1992) was issued in 1992 which is almost 30 years ago. Actually many terminal implementation follows the *de facto* standard formed by DEC VT series. I have to say the behavior of `alacritty` is anomalous among recent major terminals... It's just my opinion, but if it does not support some CSI sequences, it can just ignore them instead of behaving differently from major terminals. I believe such kind of suggestions are completely valid to ask for `alacritty`.

**Comment by miba072** [comment]
The issue has been acknowledged by alacritty and it's expected to be fixed in a future release

**Comment by akinomyoga** [comment]
Thank you very much!
