### ISSUE TITLE
Readonly on single character variables crash command line

### ISSUE THREAD

**Issue by mozirilla213** [akinomyoga/ble.sh#289]
```
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu) [Arch Linux]
ble.sh, version 0.4.0-devel3+46ac426 (noarch) [git 2.39.1, GNU Make 4.4, GNU Awk 5.2.1, API 3.2, PMA Avon 8-g1, (GNU MPFR 4.2.0, GNU MP 6.2.1)]
bash-completion, version 2.11 (hash:2d02f73e803daa87a06e94e33b2a7b3e672a2c0c, 76338 bytes) (noarch)
locale: LANG=C
terminal: TERM=xterm-256color wcwidth=15.0-west/13.0-2+ri, xterm:115 (1;115;0)
```

Running readonly on certain single character variables have various effects, most of them apparently non recoverable. Maybe happens with other non-single character variables but haven't found any
```
> readonly w
# Cannot keep writing
```
```
> readonly q
bash: local: q: readonly variable
bash: local: q: readonly variable
# Cannot keep writing, CPU spikes
```
```
> readonly s  # same with 'j', 'l'
# Cannot keep writing but no prompt appears, CPU spikes
```
```
> readonly x  # same with 'y'
bash: local: x: readonly variable
bash: local: x: readonly variable
bash: x: readonly variable
# Outputs the same on every character typed, cannot keep writing
```
```
> readonly n
bash: local: n: readonly variable
bash: local: n: readonly variable
# Outputs the same on every character typed, cannot keep writing
```
```
> readonly c
bash: local: c: readonly variable  # 22 times
# Cannot keep writing
```
```
> readonly a  # same with 'b', 'p', 'n', 'g'. with 'h' the error shows 4 times
bash: local: a: readonly variable
bash: local: a: readonly variable
# Outputs the same on every character typed, but can keep writing
```
```
> readonly k
bash: local: k: readonly variable
bash: k: readonly variable
bash: local: k: readonly variable
bash: k: readonly variable
# Outputs the same on every character typed, but can keep writing
```
```
> readonly v
bash: local: v: readonly variable
bash: local: v: readonly variable
bash: local: v: readonly variable
bash: v: readonly variable
bash: local: v: readonly variable
bash: local: v: readonly variable
# Outputs the same on every character typed, can keep writing but eventually CPU spikes and cannot write anymore
```
```
> readonly m
[ble: press RET to continue]<ENTER>
[ble: press RET to continue]<ENTER>
[ble: press RET to continue]
```
```
> readonly u
> ... # when typing certain character or randomly, outputs bash: local: u: readonly variable twice. also messes up non-ascii characters
```
```
> readonly t
# Messes up padding on prompts, but apparently nothing else
```

Apparently nothing bad happens with doing it with `z`, `r`, `f`

If case these variables cannot be made readonly, there should probably be at least a safeguard to prevent it, like a `readonly(){ ble/builtin/readonly "$@";}`.

**Comment by akinomyoga** [comment]
Please read [README - Limitation](https://github.com/akinomyoga/ble.sh#limitations). I have to say `readonly` shouldn't be used for global variables generally unless it is for protection for some security or privileges.

Overriding `readonly` with a shell function might be an option. Later I'll consider it if it doesn't cause other problems.

**Comment by mozirilla213** [comment]
Right, I think that at least if ble could prevent a session from dying it should `readonly(){ ble/util/print "readonly disabled" >&2; return 1;}`, rather than having someone finding out in the worst time

**Comment by akinomyoga** [comment]
It seems just overriding `readonly` doesn't complete turn off the effect of `readonly`.

```bash
[murase@chatoyancy 0 ble.sh]$ function readonly { echo xxx; }
[murase@chatoyancy 0 ble.sh]$ readonly a=(1 2 3)
xxx
[murase@chatoyancy 0 ble.sh]$ declare -p a
declare -a a=([0]="1" [1]="2" [2]="3")
```

Also, I wouldn't try to turn off all `readonly` because using `readonly` for local variables is not the problem, and other Bash configurations might use it. The problem is whether it is possible to obtain the original arguments specified to `readonly` when the user uses an array assignment syntax, etc. Maybe it is related to the reason that `readonly -a a=()` first creates an array variable and then calls the overriding function.

Another issue is that `readonly` is not the only way to make variables readonly. `declare -r` can still be used to make global variables readonly. However `declare` creates a variable in the local function scope, so it is not possible to wrap `declare` inside another shell function as it creates the variables inside the wrapper function.

**Comment by mozirilla213** [comment]
How about this?
```bash
function readonly {
 if [[ "${#FUNCNAME[@]}" -eq 1 ]]; then
    ble/util/print "global readonly disabled" >&2
    return 1
  else
    builtin readonly "$@"
  fi
}
```
Regarding declare, I though an alias could help but maybe not. Maybe have ble detect if user is writing `declare -r` in global scope? But maybe that's too costly or would be annoying for the user (although that's not really the issue)

**Comment by akinomyoga** [comment]
I pushed commit 8683c84ac941371ad244cd99e8836ee3bcbbd3a5. I have updated some of the local variable names and added a shell function `readonly`:

https://github.com/akinomyoga/ble.sh/blob/8683c84ac941371ad244cd99e8836ee3bcbbd3a5/src/util.sh#L6791-L6904

These are considerations:

- `${#FUNCNAME[@]}` cannot be used because the scope of a specified variable is unrelated to the caller of `readonly`. One can always call the `readonly` builtin against global variables in function scopes. We need to test each variable specified to `readonly` separately.
- `readonly` is not only used to make variables readonly but can be used to show the readonly variables (`readonly` without arguments), or to show the help message (`readonly --help`), etc., where the warning message should not be shown, and the `readonly` builtin should be called normally.
- Even if the variables should not be made readonly, we want to anyway assign a value because otherwise, it could cause problems in the codes that called `readonly`.
- To avoid flooding with the warning messages, the warning messages are shown only up to ten times.
- I decided to allow making global variables with the name consisting of uppercase letters (plus underscores and digits) except for single-character variable names, common variables, and some variables ble.sh internally uses. The exceptions are maintained by a blacklist.
- I also decided to allow making global variables starting with `_` readonly (but still the variables starting with `_ble_` and `__ble_` are not allowed to make readonly). Other frameworks might want to use constants with the names of the form `_{FrameworkName}_*`. I have changed the existing local variable names starting with `_`.

**Comment by mozirilla213** [comment]
This is a great breakdown of the considerations on this. They all look very sensible and thought-out, and work as expected from what I tested. Another great work @akinomyoga. 🙏

My only concern is if keeping the blacklist updated would be a hassle, or what to do if a framework appears that has constants not starting with `_`, I guess open an issue with them not being compatible with ble.sh.

**Comment by akinomyoga** [comment]
Thank you for testing!

> My only concern is if keeping the blacklist updated would be a hassle,

Yeah, that might be. I have generated the list by using the following command line (where [`grc`](https://github.com/akinomyoga/mshex/blob/master/bin/grc) is one of my personal scripts).

```bash
$ grc -o '\b(_[[:alnum:]_]+|[A-Z0-9_]+)\+?=\b|/assign (_[[:alnum:]_]+|[A-Z0-9_]+)\b' --exclude={memo,wiki,test,make} | sed 's/^.*://' | sort -u | grep -Ev '\b_ble|\b__ble'
```

Maybe I'd automate the list checking later.

> what to do if a framework appears that has constants not starting with `_`,

Yeah, that is also possible. My thinking is that, ble.sh is expected to be used in interactive sessions, so the normal variable names starting with letters are supposed to be reserved for the command-line uses by the user, so I generally expect that global variables internally used by frameworks are prefixed by `_`. I think it is the general convention in any framework I know, but it would be possible that some frameworks could mark *public* global variables readonly. Anyway, as explained in the README Limitations section, it is generally considered bad to make any variables readonly.
