### ISSUE TITLE
PIPESTATUS just captures last exit code in pipeline

### ISSUE THREAD

**Issue by mozirilla213** [akinomyoga/ble.sh#290]
```
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu) [Arch Linux]
ble.sh, version 0.4.0-devel3+46ac426 (noarch) [git 2.39.1, GNU Make 4.4, GNU Awk 5.2.1, API 3.2, PMA Avon 8-g1, (GNU MPFR 4.2.0, GNU MP 6.2.1)]
bash-completion, version 2.11 (hash:2d02f73e803daa87a06e94e33b2a7b3e672a2c0c, 76338 bytes) (noarch)
locale: LANG=C
terminal: TERM=xterm-256color wcwidth=15.0-west/13.0-2+ri, xterm:115 (1;115;0)
```

`$PIPESTATUS` usually captures all exit codes in a pipeline, but doesn't running ble.sh

Expected:
```
> true | false | (exit 30)
> echo "${PIPESTATUS[@]}"
0 1 30
```
With ble.sh:
```
> true | false | (exit 30)
> echo "${PIPESTATUS[@]}"
30
```

**Comment by akinomyoga** [comment]
This is also another limitation. `PIPESTATUS` cannot be set programmatically in Bash.

You could try to assign values to the array, but it will soon then overwritten by the status of the assignment itself. An alternative way is to construct a fake pipeline like '(exit "${PIPESTATUS[0]}") | (exit "${PIPESTATUS[1]}") | (exit "${PIPESTATUS[2]}")' and `eval` it, but I'd like to avoid it because it has a large cost.

Actually, ble.sh saves the values of `PIPESTATUS` in the array `_ble_edit_exec_PIPESTATUS`. I think I can make it a public variable (e.g. `BLE_PIPESTATUS`), but for the time being, could you use `_ble_edit_exec_PIPESTATUS`?

```bash
$ true | false | (exit 30)
$ declare -p _ble_edit_exec_PIPESTATUS
declare -a _ble_edit_exec_PIPESTATUS=([0]="0" [1]="1" [2]="30")
```

**Comment by mozirilla213** [comment]
I see, thanks I didn't know about it, maybe it should be on the readme as well

**Comment by akinomyoga** [comment]
I pushed commit 70d88af54ccd6539a87dc7621b403f3488c292c6. I added `BLE_PIPESTATUS`.

> An alternative way is to construct a fake pipeline like `(exit "${PIPESTATUS[0]}") | (exit "${PIPESTATUS[1]}") | (exit "${PIPESTATUS[2]}")` and `eval` it every time before running the user command, but I'd like to avoid it because it has a large cost.

I implemented this as an option. This is turned off by default. To enable it, use [`bleopt exec_restore_pipestatus=1`](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A74-Editing#user-content-bleopt-exec_restore_pipestatus).

> I see, thanks I didn't know about it, maybe it should be on the readme as well

I added an item in the limitation section.

**Comment by mozirilla213** [comment]
Amazing work! Both features work as expected. Thank you
