### ISSUE TITLE
[ble: exit 148] gets reported for process that is not exited but stopped

### ISSUE THREAD

**Issue by bkerin** [akinomyoga/ble.sh#296]
$ echo $BLE_VERSION                                         
0.4.0-devel3+46ac426
$ echo "$BASH_VERSION ($MACHTYPE)"                         
5.0.17(1)-release (x86_64-pc-linux-gnu)

It's a tiny nit but in this example bc is not exited as ble says but only stopped:

```
$ bc                                                                                                                                                                                                
bc 1.07.1
Copyright 1991-1994, 1997, 1998, 2000, 2004, 2006, 2008, 2012-2017 Free Software Foundation, Inc.
This is free software with ABSOLUTELY NO WARRANTY.
For details type `warranty'. 
^Z
[1]+  Stopped                 bc -l
[ble: exit 148]
$ false                                                                                                                                                                                             
[ble: exit 1]
$ 
```

I think maybe with WIFSIGNALED or whatever the shell equivalent is slightly more accurate output could be produced.

**Comment by akinomyoga** [comment]
This is somehow intentional. `ble.sh` just reports the exit status (`$?`) after the user command regardless of whether any process has exited or not. If you would like to make it more explicit, you can turn off the ble.sh's built-in marker by `bleopt exec_errexit_mark=` and write a code to construct and output a custom marker. [`contrib/config/execmark.bash`](https://github.com/akinomyoga/blesh-contrib/blob/f077c0f0d88325ec6cc54fda31fcc1eed652d4b9/config/execmark.bash#L35-L46) is actually my custom marker where the marker for 148 is rendered as `[ble: SIGTSTP (148)]`.

This is a reduced example. I have also included the solution to #295 (the related part is `ble/string#match "$command" $'^[[:space:]]*#[^\n]+$'`):

```bash
function ble/contrib/config:bkerin-errexit/postexec.hook {
  local command=$_ble_edit_exec_BASH_COMMAND

  if ((_ble_edit_exec_lastexit)) && ! ble/string#match "$command" $'^[[:space:]]*#[^\n]+$'; then
    local sgr=$'\e[;94m' sgr0=$'\e[m' sgrE=$'\e[;91m' ret
    ble/color/face2sgr-ansi varname_number; local sgrN=$ret

    local exit=$_ble_edit_exec_lastexit name=
    if ((exit>=128)) && [[ ${name:=${_ble_builtin_trap_sig_name[exit&127]}} ]]; then
      exit=$'\e[1m'"$name"$'\e[22m'" ($sgrN$exit$sgrE)"
    else
      exit="exit $sgrN$exit$sgrE"
    fi
    local mark=$sgrE'[ble: '$exit']'$sgr0
    ble/util/buffer.print "$mark"
  fi
}
bleopt exec_errexit_mark=
blehook POSTEXEC!=ble/contrib/config:bkerin-errexit/postexec.hook
```

**Comment by bkerin** [comment]
This works nicely thanks, resolved.

**Comment by akinomyoga** [comment]
Thanks!
