### ISSUE TITLE
Typing nix shell nixpkgs# hangs the shell

### ISSUE THREAD

**Issue by Aleksanaa** [akinomyoga/ble.sh#300]
**ble version**: 0.4.0-nightly+a22e145
**Bash version**: 5.2.15(1)-release

When I'm trying to type `nix shell nixpkgs#<some package>`, which is typical for nix users to start a temporary shell with the package, the shell hangs immediately after typing `#`, and I can't type anything or move the cursor.

I've tried with 
```
bleopt complete_auto_complete=0
bleopt complete_menu_complete=0
bleopt complete_menu_filter=0
```
but it doesn't work either.

**Comment by akinomyoga** [comment]
Thank you for the report. Actually, this issue was also reported by @aiotter in https://github.com/akinomyoga/ble.sh/issues/58#issuecomment-1272222143. I was busy at that time so have been left the issue until today. I today took time to reproduce the issue, but I don't seem to be able to reproduce the problem. I have tried the following completion settings, but none seems to reproduce the issue.
- [`hedning/nix-bash-completions` master `/_nix`](https://github.com/hedning/nix-bash-completions/blob/e6db3081fe1f221470a26e345a96855e5f09ddec/_nix)
- [`nix-bash-completions` #17 `/_nix`](https://github.com/hedning/nix-bash-completions/blob/5d28f3de9244ccf679630770b90448a22a65aced/_nix)
- [`nix` master `/misc/bash/completion.sh`](https://github.com/NixOS/nix/blob/37c61907d7111277aeb22d18195c425fe27fed1b/misc/bash/completion.sh)

I'm not familiar with NixOS so might be doing something wrong in using the completion settings.

Could you describe the detailed setup for the completion for the `nix` command?

- **Q1**: Do you have an explicit setting for `nix` in your `~/.bashrc` or other Bash configurations?
- **Q2**: What is the output of the following command?

```bash
$ complete -p nix
```

- **Q3**: What is the output of the following command? Here, I assume that the name of the completion function (which is specified after `-F` in the output of Q2) is `_complete_nix`, but if it's different please replace `_complete_nix` in the following lines with the correct one.

```bash
$ type _complete_nix
$ (shopt -s extdebug; declare -F _complete_nix)
$ ls -l "$(shopt -s extdebug; declare -F _complete_nix | awk '{print $3}')"
```

----

> ```
> bleopt complete_auto_complete=0
> bleopt complete_menu_complete=0
> bleopt complete_menu_filter=0
> ```

By the way, the correct way to turn off these is to specify an empty value (not `0`). (It's designed in this way to leave room for a future extension e.g. accepting detailed specifications as a value instead of merely an integer.) For the present case, the only relevant option is `complete_auto_complete`.

```bash
bleopt complete_auto_complete=
```

**Comment by Aleksanaa** [comment]
Okay I finally figured it out. When running nix command without specifying where the flakes are, it does not use user-specified flakes in /etc/nixos. Rather, it depends on [flake-registry](https://github.com/NixOS/flake-registry), fetches a json file from GitHub nixpkgs repo which tells it what revision should be fetched, and the file is not part of the output of system configuration (So it can be garbage collected).

So what we need is simply issue this option in our flakes:
```nix
nix.registry.nixpkgs.flake = inputs.nixpkgs;
```

This will pin the nixpkgs version in registry to the same as the one in inputs. In this case the nixpkgs repo is always in store and we won't need to fetch it again so the completion won't freeze.

**Comment by Aleksanaa** [comment]
Some issues related to this behaivor: https://github.com/NixOS/nix/issues/7422

**Comment by akinomyoga** [comment]
Thank you for the information! I'd like to add a workaround also at ble.sh's side . I'd appreciate it if you could provide the result of Q2 (and Q3 if possible).

**Comment by Aleksanaa** [comment]
> Thank you for the information!
> 
> I'd like to add a workaround also at ble.sh's side . I'd appreciate it if you could provide the result of Q2 (and Q3 if possible).

It says no completions for that command. You can understand nixos as the superposition of many broken fhs spaces, so it is better to go directly to the source code.

**Comment by akinomyoga** [comment]
> It says no completions for that command.

Ah, OK. This means that the completion is by `bash-completion`. Could you run the command `complete -p nix` after attempting the completion of `nix` at least once?

**Comment by Aleksanaa** [comment]
> > It says no completions for that command.
> 
> Ah, OK. This means that the completion is loaded by `bash-completion`. Could you run the command `complete -p nix` after attempting the completion of `nix` at least once?

Yes.
```
❯ complete -p nix
complete -F _complete_nix nix
```

```
❯ type _complete_nix
_complete_nix is a function
_complete_nix () 
{ 
    local -a words;
    local cword cur;
    _get_comp_words_by_ref -n ':=&' words cword cur;
    local have_type;
    while IFS= read -r line; do
        local completion=${line%%	*};
        if [[ -z $have_type ]]; then
            have_type=1;
            if [[ $completion == filenames ]]; then
                compopt -o filenames;
            else
                if [[ $completion == attrs ]]; then
                    compopt -o nospace;
                fi;
            fi;
        else
            COMPREPLY+=("$completion");
        fi;
    done < <(NIX_GET_COMPLETIONS=$cword "${words[@]}" 2> /dev/null);
    __ltrim_colon_completions "$cur"
}
```

```
❯ (shopt -s extdebug; declare -F _complete_nix)
_complete_nix 1 /run/current-system/sw/share/bash-completion/completions/nix
```

```
❯ ls -l "$(shopt -s extdebug; declare -F _complete_nix | awk '{print $3}')"
lrwxrwxrwx 3 root root 92 Jan  1  1970 /run/current-system/sw/share/bash-completion/completions/nix -> /nix/store/0g2czg46n8r0n1n7asykjwbk3cv3wc0c-nix-2.13.2/share/bash-completion/completions/nix
```

**Comment by akinomyoga** [comment]
Thank you!

**Comment by akinomyoga** [comment]
I have added a workaround. Could you test if it works after running `ble-update`?

If you don't have time, you can just test if the latest version of ble.sh doesn't break the completion with your current setup after the fix described in https://github.com/akinomyoga/ble.sh/issues/300#issuecomment-1454668072.
