### ISSUE TITLE
[macOS] stty: stdout appears redirected, but stdin is the control descriptor

### ISSUE THREAD

**Issue by adoyle-h** [akinomyoga/ble.sh#303]
## Problem

It always print the message `stty: stdout appears redirected, but stdin is the control descriptor` with any command invoked.

![CleanShot 2023-03-14 at 17 34 20@2x](https://user-images.githubusercontent.com/1998490/224958450-e2521967-1944-4f37-8587-c392ed3f5a47.png)

## Versions

ble/widget/display-shell-version:

GNU bash, version 5.2.2(1)-release (aarch64-apple-darwin21.6.0)
ble.sh, version 0.4.0-devel3+6f5604d (noarch) [git 2.38.1, GNU Make 3.81, GNU Awk 5.1.1, API: 3.1 (GNU MPFR 4.1.0-p13, GNU MP 6.2.1)]
bash-completion, version 2.11 (hash:b98b54bb3aed57ebb01ff2822e348330c0b1d7c9, 76339 bytes) (noarch)
fzf key-bindings, version +ee5cdb97 (noarch)
WARNING: fzf integration "integration/fzf-key-bindings" is not activated.
bash-preexec, (hash:5f1208c33e624859eea70e3843bd9b8c9a06819e, 13046 bytes) (noarch)
bash-it, version +66ae9b0d (noarch), alias(), completion(), plugin()
zoxide, version 0.8.3 (/opt/homebrew/bin/zoxide)
locale: LANG=zh_CN.UTF-8 LC_TERMINAL=iTerm2 LC_TERMINAL_VERSION=3.5.0beta10
terminal: TERM=xterm-256color wcwidth=14.0-west/15.0-2+ri, xterm:2500 (41;2500;0)

## ~/.config/blesh/init.sh

```sh
bleopt prompt_status_line=
bleopt prompt_status_align=left
bleopt prompt_eol_mark=
bleopt exec_errexit_mark=
bleopt exec_elapsed_mark=
bleopt complete_auto_delay=150
bleopt complete_limit=50
bleopt term_true_colors=auto
ble-face -s filename_ls_colors        underline
ble-face -s syntax_default            none
function blerc/emacs-load-hook {
  return
}
blehook/eval-after-load keymap_emacs blerc/emacs-load-hook
function blerc/vim-load-hook {
  ((_ble_bash>=40300)) && builtin bind 'set keyseq-timeout 1'
}
blehook/eval-after-load keymap_vi blerc/vim-load-hook
```

**Comment by akinomyoga** [comment]
I'm not sure what causes the issue, but some settings related to TTY on the shell startup could be affecting.

- **Q1**: Does the same error appear with the following command in a ble.sh session?

```bash
$ stty icanon
```

- **Q2**: What are the results of the following commands in a ble.sh session?

```bash
$ declare -p _ble_util_fd_std{in,out,err}
$ declare -p _ble_util_openat_fdlist
$ lsof -p "$$"
```

- **Q3**: Does the problem appear when `ble.sh` is sourced with all the standard streams redirected to `/dev/null`?

```bash
source /path/to/ble.sh < /dev/null &> /dev/null
```

**Comment by akinomyoga** [comment]
- **Q4**: What is the result of the following commands?

```bash
$ type -a stty
$ stty --version
```

**Comment by adoyle-h** [comment]
![CleanShot 2023-03-14 at 19 16 24@2x](https://user-images.githubusercontent.com/1998490/224984888-17898154-e5bf-4e81-9832-e2bd1c624b58.png)

I ran these commands in a shell without tmux.

**Comment by akinomyoga** [comment]
Thanks.

- **Q5**: What is the result of the following command in a plain Bash session (in which *ble.sh has never* sourced*)?

```bash
$ lsof -p "$$"
```

**Comment by akinomyoga** [comment]
Thank you for these results.

- **Q6**: What is the result of the following commands in a plain Bash session?

```bash
$ [[ -t 1 ]]; echo $?
$ [[ -t 2 ]]; echo $?
```

- **Q7**: How do you source `ble.sh` in your setting? For example, do you redirect stderr and stdout when sourcing ble.sh?

**Comment by adoyle-h** [comment]
Q6:

```
[[ -t 1 ]]; echo $?
0
[[ -t 2 ]]; echo $?
0
```

Q7: 

1. The .bashrc use a function `load_mod` to source file A.

     ```bash
      load_mod() {
        # Add prefix for each line of stdout and stderr
        source "$file_a" \
          1> >(sed -E "s|^(.+)|[$file_a]: \1|") \
          2> >(sed -E "s|^(.+)|${RED_ESC}[$file_a]: \1${RESET_ALL_ESC}|" >&2) \
          || load_failed "$?"
      }

      load_failed() {
        local exit_code=$1
        printf '%bFailed to load module "%s" (exit_code=%s).\n%b' \
          "$YELLOW" "$filename" "$exit_code" \
          "$RESET_ALL" >&2
      }
     ```

2. The file A is a symbol link file which points to file B.
3. The file B has only one line: `source $dir/share/blesh/ble.sh`
4. The `$dir/share/blesh/ble.sh` is made by `make -C ble.sh install PREFIX=$dir`

**Comment by akinomyoga** [comment]
Thank you for all of the information. It seems to be caused by the combination of the following three facts:

- In your system, `/dev/tty` is not really a synonym for the current controlling terminal as requested by the POSIX standard. Your `OSTYPE` is `aarch64-apple-darwin21.6.0` which I think implies that you use macOS. It is even strange that the `tty` command is cheated by redirecting stdin/stdout/stderr to `/dev/tty` and outputs `/dev/tty` as the current controlling terminal. For reference, the related description of the POSIX standard reads

> *From [POSIX XBD 10.1](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap10.html)*
> **/dev/tty**
> In each process, a synonym for the controlling terminal associated with the process group of that process, if any. It is useful for programs or shell procedures that wish to be sure of writing messages to or reading data from the terminal no matter how output has been redirected. It can also be used for applications that demand the name of a file for output, when typed output is desired and it is tiresome to find out what terminal is currently in use.

- `stty` in your system seems to complain when stdout and stderr are connected to "different" TTY. First of all, using `stty` with different stderr/stdout is not really restricted by the standard, so I'm not sure whether outputting the warning message is a good behavior here. It might be nicer to print the hints for the users about its usage if `stty` is used in a interactive command line, but the "hints" are just annoying when `stty` is used inside a script.

As far as looking at the error message, `stty` in your system seems to come from that of BSD. I can reproduce the same error message ("stty: stdout appears...") in FreeBSD 13 if I redirect one of stdout or stderr to the TTY of another terminal. However, I cannot reproduce the error message by redirecting to `/dev/tty` because `/dev/tty` seems correctly a synonym for the current controlling terminal in FreeBSD. Opening a file with `/dev/tty` automatically resolves the current controlling terminal of the name `/dev/pts/XXX` or `/dev/ttyvXXX` in FreeBSD. I think BSD `stty` just doesn't take into account the strange behavior of macOS `/dev/tty` because it is primarily designed for use in BSD systems but not in macOS.

- You source `ble.sh` with stdout and stderr being redirected to process substitutions `1> >(...)` and `2> >(...)`. This effectively hides the controlling terminal from ble.sh. For this reason, `ble.sh` needs to somehow find out the current controlling terminal by itself. It can be usually achieved by `/dev/tty`, but it doesn't work in macOS as described above.

In this situation, I'm not sure how to reliably get the correct controlling terminal when it is hidden by the redirections. I would like to experiment more by myself, but I don't have macOS unfortunately.

- **Q8**: Could you see the result of the following command?

```bash
$ (t='\l'; echo "${t@P}") < /dev/tty &>/dev/tty
```

**Comment by adoyle-h** [comment]
I wonder why ble.sh print  the `stty: stdout appears redirected, but stdin is the control descriptor` message when command invoked while no prints when just pressed `<Enter>`.

<img width="989" alt="CleanShot 2023-03-15 at 12 35 15@2x" src="https://user-images.githubusercontent.com/1998490/225207588-163e519d-9595-4e6f-80fd-832cfbef6083.png">

The stdout and stderr being redirected via `1> >(...)` and `2> >(...)`)  happened at `source ble.sh`. But there is no redirection with `ls` command.

---

Q9:

<img width="1352" alt="CleanShot 2023-03-15 at 11 55 31@2x" src="https://user-images.githubusercontent.com/1998490/225202362-1864c843-80bf-481e-b3aa-04d44356001d.png">

---

Additional, these `stty` flags and the manpage of `tty` in MacOS may help you.

```
$ stty -a
speed 38400 baud; 39 rows; 135 columns;
lflags: icanon isig iexten echo echoe echok echoke -echonl echoctl
	-echoprt -altwerase -noflsh -tostop -flusho pendin -nokerninfo
	-extproc
iflags: -istrip icrnl -inlcr -igncr ixon -ixoff ixany imaxbel iutf8
	-ignbrk brkint -inpck -ignpar -parmrk
oflags: opost onlcr -oxtabs -onocr -onlret
cflags: cread cs8 -parenb -parodd hupcl -clocal -cstopb -crtscts -dsrflow
	-dtrflow -mdmbuf
cchars: discard = ^O; dsusp = ^Y; eof = ^D; eol = <undef>;
	eol2 = <undef>; erase = ^?; intr = ^C; kill = ^U; lnext = ^V;
	min = 1; quit = ^\; reprint = ^R; start = ^Q; status = ^T;
	stop = ^S; susp = ^Z; time = 0; werase = ^W;
```

```
$ stty -g
gfmt1:cflag=4b00:iflag=6b02:lflag=200005cf:oflag=3:discard=f:dsusp=19:eof=4:eol=ff:eol2=ff:erase=7f:intr=3:kill=15:lnext=16:min=1:quit=1c:reprint=12:start=11:status=14:stop=13:susp=1a:time=0:werase=17:ispeed=38400:ospeed=38400
```

```
TTY(1)                                           General Commands Manual                                           TTY(1)

NAME
     tty – return user's terminal name

SYNOPSIS
     tty [-s]

DESCRIPTION
     The tty utility writes the name of the terminal attached to standard input to standard output.  The name that is
     written is the string returned by ttyname(3).  If the standard input is not a terminal, the message “not a tty” is
     written.  The options are as follows:

     -s      Do not write the terminal name; only the exit status is affected when this option is specified.  The -s
             option is deprecated in favor of the “test -t 0” command.

EXIT STATUS
     The tty utility exits 0 if the standard input is a terminal, 1 if the standard input is not a terminal, and >1 if an
     error occurs.

SEE ALSO
     test(1), ttyname(3)

STANDARDS
     The tty utility is expected to be IEEE Std 1003.2 (“POSIX.2”) compatible.

HISTORY
     A tty command appeared in Version 1 AT&T UNIX.

macOS 12.2                                             June 6, 1993                                            macOS 12.2
```

**Comment by akinomyoga** [comment]
> Q-a: why ble.sh print the `stty: stdout appears redirected, but stdin is the control descriptor` message when command invoked, while no prints when just pressed `<Enter>`.

The TTY-handler state is different, when the user command is running, from the TTY-handler state when the user inputs the commands into line editors. For example, <kbd>C-c</kbd> means <kbd>C-c</kbd> when the line editor is in front, but it becomes SIGINT when the user command is running. There are many other differences between the two TTY states. In `ble.sh`, the switching between these two TTY states is performed by calling the `stty` commands with appropriate arguments. When ble.sh runs the user command, it needs to switch to "the command mode" before running the command and to "the editor mode" after running the user command. When you just press <kbd>Enter</kbd>, the user command is not being run so there is no need for switching the TTY modes, so ble.sh does not need to call `stty`.

> Q-b: The stdout and stderr being redirected via `1> >(...)` and `2> >(...)`) happened at `source ble.sh`. But there is no redirection with `ls` command. Did ble.sh save the intermediate state when it sourced?

Yes, it saves the file descriptors when it is sourced.

This is related to how ble.sh replaces Readline. Bash doesn't provide an official way to replace Readline, and there is actually no way to completely turn off Readline. When ble.sh is working in front, actually Readline may also output something to stderr/stdout. To suppress the outputs from Readline, ble.sh redirects stdout/stderr of the Bash process to `/dev/null`, but it needs to remember the original stdout/stderr to output what ble.sh wants to output to the terminal and to restore the original stdout/stderr for user commands.

As far as `/dev/tty` is reliable, we should be able to save the desired file descriptors at any stage of the ble.sh initialization even when stdout/stderr are redirected, so ble.sh saves them in the sourcing time as one option. As another option, ble.sh might be able to save the file descriptors at the attaching time, but there is still the same problem even in that case. Technically, `ble-attach` can be called by the user in a context where stdout/stderr are redirected to something else. Actually, saving them on the attaching stage would be more troublesome because in that way, in writing the shell functions, we cannot simply assume the file descriptors are ready for use.

> Q9:

Thank you for the result. So the result means that it is impossible to get the correct name of the controlling terminal even with the syscall `ctermid(3)`.

**Comment by akinomyoga** [comment]
Although I think I wouldn't add any workarounds or fixes to ble.sh for this issue, I have added descriptions in README §1.3 ([`2eadcd5b`](https://github.com/akinomyoga/ble.sh/commit/2eadcd5bba9984fce3b80efc49a4c39be91185b9#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R325)).

**Comment by adoyle-h** [comment]
> Basically, when `source /path/to/ble.sh` and `ble-attach` are performed, standard streams (`stdin`, `stdout`, and `stderr`) should not be redirected but should be connected to the controlling TTY of the current session.

I agree with it. I would find workaround to resolve it.

> Also, please avoid calling `source /path/to/ble.sh` in shell functions.

But I think it's a common case that calling `source /path/to/ble.sh` in shell functions. The user's .bashrc may be complex.
I wrote a plugin system to enable/disable many plugins (including ble.sh).

**Comment by akinomyoga** [comment]
> > Also, please avoid calling `source /path/to/ble.sh` in shell functions.
> 
> But I think it's a common case that calling `source /path/to/ble.sh` in shell functions. The user's .bashrc may be complex. I wrote a plugin system to enable/disable many plugins (including ble.sh).

Sourcing ble.sh from inside shell functions wouldn't cause problems if one correctly sets things up, but it is trickier to explain it in README, which targets a wide spectrum of users from beginners to heavy users. There are two things to care when one wants to source scripts from inside shell functions.

1. Bash 4.0+ has the support for associative arrays with `declare -A`, but in Bash 4.0 and 4.1, it is impossible to define global associative arrays in script files that are sourced from inside a shell function. For this reason, even though ble.sh wants to use associative arrays, it is forced to fall back to an inefficient array implementation when ble.sh is sourced from inside a shell function in Bash 4.0 or 4.1. As far as you use the recent versions of Bash >= 4.2, you don't have to care about it.
2. `source FILE` without additional arguments will inherit the arguments `"$@"` specified to the shell function, i.e., `fn() { source A; }` is effectively equivalent to `fn() { source A "$@"; }`. Since ble.sh interprets arguments specified in the source command, arguments of the caller function could be unexpectedly passed to ble.sh and might cause problems. One way to avoid this is to pass at least one explicit option to `source ble.sh`. Another way is to call `set --` inside the function before sourcing other files.

As far as you are aware of these pitfalls and careful enough to avoid such a situation, you can safely source ble.sh inside shell functions.

Actually, the same limitations apply to any scripts that try to define global variables using `declare` (or `typeset`) or that interpret the arguments specified to `source`. Be careful.

**Comment by adoyle-h** [comment]
I get it. Thank you for the detailed explanation. 👍🏻

**Comment by tessus** [comment]
@akinomyoga I am sorry to resurrect this and I can open a new issue.

I have installed ble the same way as I've done on my MacBook on another macOS (macMini). But when I connect to that machine, I get the same message.

```
stty: stdout appears redirected, but stdin is the control descriptor
```

I use the same `.bashrc` as on the other machine, all settings are the same (using dotbot). I am not redirecting anything and I am majorly confused why this is happening.

**Comment by akinomyoga** [comment]
OK, I tweaked this area in the previous and the second previous pushes, so it should be related to those changes. The related commits are 785267e18c81ada61fb26a346339613a8a8b04e6, b5938192ca588267345dac494fbebc6d2d6fde6b, f940696fde28cfd3952445fe6c3f9d853af7f7b8.

I think you can first check the commit 27e6309ef2344d37a6cec49f37b958c70f660472, which is a version before those changes. I'm now on a Zoom meeting so will reply later in detail.

**Comment by tessus** [comment]
yep, this commit works perfectly. Thanks a bunch.

I can help with whatever info you need, since you don't have a macOS system. I have to check, but I might be able to give you access to a macOS VM as well.
Let me know if this is something that could help you. 

I am about to head to bed, thus I won't be able to reply in the next few hours.

**Comment by akinomyoga** [comment]
@tessus

- **Q1**: Do you have any special setup for sourcing ble.sh?

For example, do you have redirections for `source /path/to/ble.sh`? Or do you source `ble.sh` in a shell function? Or do you source `ble.sh` in a separate file that is sourced from `~/.bashrc` or `~/.bash_profile`?

- **Q2**: Could you provide the output of the following commands in a ble.sh session?

```bash
$ declare -p "${!_ble_util_fd_@}"
$ lsof -p "$$"
```

**Comment by tessus** [comment]
> For example, do you have redirections for source /path/to/ble.sh? Or do you source ble.sh in a shell function? Or do you source ble.sh in a separate file that is sourced from ~/.bashrc or ~/.bash_profile?

Nope. I source it in the `.bashrc` with `. ~/.local/share/blesh/ble.sh`

> Q2: Could you provide the output of the following commands in a ble.sh session?

This was now with the commit you told me to use https://github.com/akinomyoga/ble.sh/commit/27e6309ef2344d37a6cec49f37b958c70f660472. (Where everything works again.)

```
$ declare -p "${!_ble_util_fd_@}"
declare -x _ble_util_fd_null="33"
declare -x _ble_util_fd_stderr="32"
declare -x _ble_util_fd_stdin="30"
declare -x _ble_util_fd_stdout="31"
declare -x _ble_util_fd_zero="34"

$ lsof -p "$$"
COMMAND   PID   USER   FD   TYPE DEVICE SIZE/OFF     NODE NAME
bash    14209 tessus  cwd    DIR   1,17     1760   258594 /Users/tessus
bash    14209 tessus  txt    REG   1,17  1050328 22829928 /opt/local/bin/bash
bash    14209 tessus  txt    REG   1,17    50520 22829745 /opt/local/lib/bash/sleep
bash    14209 tessus  txt    REG   1,17   144384 24333258 /opt/local/lib/libintl.8.dylib
bash    14209 tessus  txt    REG   1,17   331520 22733414 /opt/local/lib/libncurses.6.dylib
bash    14209 tessus  txt    REG   1,17  1155952 22726010 /opt/local/lib/libiconv.2.dylib
bash    14209 tessus    0u   CHR   16,0   0t9578     1253 /dev/ttys000
bash    14209 tessus    1u   CHR   16,0   0t9578     1253 /dev/ttys000
bash    14209 tessus    2u   CHR   16,0   0t9578     1253 /dev/ttys000
bash    14209 tessus   10u   CHR   16,0   0t9578     1253 /dev/ttys000
bash    14209 tessus   30u   CHR   16,0   0t9578     1253 /dev/ttys000
bash    14209 tessus   31u   CHR   16,0   0t9578     1253 /dev/ttys000
bash    14209 tessus   32u   CHR   16,0   0t9578     1253 /dev/ttys000
bash    14209 tessus   33u   CHR    3,2      0t0      341 /dev/null
bash    14209 tessus   34r   CHR    3,3      0t0      342 /dev/zero
bash    14209 tessus   35w   REG   1,17        0 24486740 /private/tmp/blesh/501/14209.exec.time
bash    14209 tessus  255u   CHR   16,0   0t9578     1253 /dev/ttys000
```

This is on the version that didn't work b5938192:

```
$ declare -p "${!_ble_util_fd_@}"
stty: stdout appears redirected, but stdin is the control descriptor
declare -- _ble_util_fd_cmd_stderr="38"
declare -- _ble_util_fd_cmd_stdin="34"
declare -- _ble_util_fd_cmd_stdout="36"
declare -- _ble_util_fd_is_open_stderr="32"
declare -- _ble_util_fd_is_open_stdout="31"
declare -- _ble_util_fd_null="30"
declare -- _ble_util_fd_tty_stderr="39"
declare -- _ble_util_fd_tty_stdin="35"
declare -- _ble_util_fd_tty_stdout="37"
declare -- _ble_util_fd_tui_stderr="39"
declare -- _ble_util_fd_tui_stdin="35"
declare -- _ble_util_fd_tui_stdout="37"
declare -- _ble_util_fd_zero="33"

$ lsof -p "$$"
stty: stdout appears redirected, but stdin is the control descriptor
COMMAND   PID   USER   FD   TYPE DEVICE SIZE/OFF     NODE NAME
bash    14657 tessus  cwd    DIR   1,17     1760   258594 /Users/tessus
bash    14657 tessus  txt    REG   1,17  1050328 22829928 /opt/local/bin/bash
bash    14657 tessus  txt    REG   1,17    50920 22829781 /opt/local/lib/bash/fdflags
bash    14657 tessus  txt    REG   1,17    50520 22829745 /opt/local/lib/bash/sleep
bash    14657 tessus  txt    REG   1,17   144384 24333258 /opt/local/lib/libintl.8.dylib
bash    14657 tessus  txt    REG   1,17   331520 22733414 /opt/local/lib/libncurses.6.dylib
bash    14657 tessus  txt    REG   1,17  1155952 22726010 /opt/local/lib/libiconv.2.dylib
bash    14657 tessus    0u   CHR   16,1    0t982     1255 /dev/ttys001
bash    14657 tessus    1u   CHR   16,1    0t982     1255 /dev/ttys001
bash    14657 tessus    2u   CHR    3,2  0t15517      341 /dev/null
bash    14657 tessus   10w   CHR    2,0   0t3859      340 /dev/tty
bash    14657 tessus   30u   CHR    3,2  0t15517      341 /dev/null
bash    14657 tessus   31u   CHR    3,2  0t15517      341 /dev/null
bash    14657 tessus   32u   CHR    3,2  0t15517      341 /dev/null
bash    14657 tessus   33r   CHR    3,3      0t0      342 /dev/zero
bash    14657 tessus   34u   CHR   16,1    0t982     1255 /dev/ttys001
bash    14657 tessus   35u   CHR   16,1    0t982     1255 /dev/ttys001
bash    14657 tessus   36u   CHR   16,1    0t982     1255 /dev/ttys001
bash    14657 tessus   37u   CHR   16,1    0t982     1255 /dev/ttys001
bash    14657 tessus   38u   CHR    3,2  0t15517      341 /dev/null
bash    14657 tessus   39w   CHR    2,0   0t3859      340 /dev/tty
bash    14657 tessus   40u   CHR   16,1    0t982     1255 /dev/ttys001
bash    14657 tessus   41u   CHR   16,1    0t982     1255 /dev/ttys001
bash    14657 tessus   42w   REG   1,17        0 24486920 /private/tmp/blesh/501/14657.exec.time
bash    14657 tessus  255u   CHR   16,1    0t982     1255 /dev/ttys001
```

**Comment by akinomyoga** [comment]
Thank you for the information. Hmm, nothing seems to be broken for stdout and stdin, but stderr is connected to `/dev/null`. This happens when `ble.sh` is sourced with stderr being connected to `/dev/null` (such as `source /path/to/ble.sh 2>/dev/null`. I'll take a look on the VM you prepared.

**Comment by jon-hotaisle** [comment]
hi there, new to ble, coming from installing atuin and running into this same issue. I've done everything to clear out my bashrc and bash_profile down to the bare minimum. OSX with bash installed from brew.

```
source ~/.local/share/blesh/ble.sh
eval "$(atuin init bash)"
```

If there is anything I can do to help debug this, LMK.

**Comment by akinomyoga** [comment]
It seems the redirection `exec 32>&2` fails under a certain condition in macOS. ble.sh uses something like `N>&2` (where `N` is picked from some unused file descriptors) to save `stderr`, but it's not actually saved. This results in the loss of the original `stderr`. Then, `stty` on macOS seems to check if `stderr` is connected to TTY and produce an error message if not.

I confirmed the same behavior for `stderr` in FreeBSD, though BSD stty doesn't seem to complain about it.

**Comment by akinomyoga** [comment]
This is a reduced test case.

```zsh
% cat reduced2.sh
#!/usr/bin/env bash
exec 51>1.txt
exec 10>&-; { exec 52<&10; } 51</dev/null; exec 51<&52
exec 50>&51
exec 50>2.txt
echo hi >&50
ls -l 1.txt 2.txt
% ./reduced2.sh
-rw-r--r--  1 akinomyoga  staff  3 Feb 23 05:47 1.txt
-rw-r--r--  1 akinomyoga  staff  0 Feb 23 05:47 2.txt
```

I expect that the string `hi` go into `2.txt`, but it goes to `1.txt` on macOS and FreeBSD. This means that the redirection `50>2.txt` fails on macOS and FreeBSD. It works as expected in other operating systems (Linux, Solaris, Minix, Cygwin). I suspect libc of FreeBSD.

**Comment by jon-hotaisle** [comment]
@akinomyoga Confirmed. Thanks so much for the fast response.

**Comment by akinomyoga** [comment]
Thank you for checking the behavior!

> This is a reduced test case.

I somehow thought this test case would work as expected in other operating systems, but this test case seems to fail also in Linux. This seems to be caused by [this "experimental" `if` statement in `redir.c:1288` in the Bash source code](https://git.savannah.gnu.org/cgit/bash.git/tree/redir.c?h=devel#n1288):

```c
  /* experimental:  if we're saving a redirection to undo for a file descriptor
     above SHELL_FD_BASE, add a redirection to be undone if the exec builtin
     causes redirections to be discarded.  There needs to be a difference
     between fds that are used to save other fds and then are the target of
     user redirections and fds that are just the target of user redirections.
     We use the close-on-exec flag to tell the difference; fds > SHELL_FD_BASE
     that have the close-on-exec flag set are assumed to be fds used internally
     to save others. */
  if (fd >= SHELL_FD_BASE && ri != r_close_this && clexec_flag)
    {
      sd.dest = fd;
      rd.dest = new_fd;
      new_redirect = make_redirection (sd, r_duplicating_output, rd, 0);
      new_redirect->flags |= RX_INTERNAL;

      add_exec_redirect (new_redirect);
    }
```

This sets up the "undo redirection" performed after the execution of `exec` ends. The redirection `exec 50>2.txt` is actually performed internally, but it is *undone* after ending the `exec` command. Bash seems to internally use `O_CLOEXEC` to mark some temporary file descriptors, so if a script tries to use `O_CLOEXEC` for its own purpose, it may cause a problem.

This is an even reduced test case:

```bash
#!/usr/bin/env bash

# Please replace the path to the loadable builtin with that in your system
enable -f ~/.opt/bash/dev/lib/bash/fdflags fdflags

exec 50>1.txt
fdflags -s +cloexec 50
exec 50>2.txt
echo hi >&50
ls -l 1.txt 2.txt
```

**Comment by jon-hotaisle** [comment]
@akinomyoga Impressive debugging effort. Will you upstream this to bash?

**Comment by akinomyoga** [comment]
Hmm, I'm not sure if I'm going to report it upstream since Bash seems to use `O_CLOEXEC` for its purpose intentionally. It's not really a bug, but a conflict with the script, though the superficial behavior appears to be broken. This "experimental" code has existed there for more than ten years. The commit [`cac4cdbf5`](https://git.savannah.gnu.org/cgit/bash.git/commit/?h=devel&id=cac4cdbf5) introduced this experimental `if` statement on 2011-10-09. I quickly tried to find out if there was a corresponding discussion on the bug-bash mailing list, but I couldn't find it. There is no corresponding ticket on Savannah either. Maybe we can ask if there is any alternative implementation for this *experimental* code, though I'm not entirely sure what is the original problem this experimental code tries to solve.

**Comment by akinomyoga** [comment]
I asked: https://lists.gnu.org/archive/html/bug-bash/2024-02/msg00188.html
