### ISSUE TITLE
Command duration calculated with PREEXEC and POSTEXEC does not coincide with time/elapsed mark

### ISSUE THREAD

**Issue by gvlassis** [akinomyoga/ble.sh#327]
**ble version**:0.4.0-nightly+0adce7c
**Bash version**: 5.2.15(1)-release (aarch64-apple-darwin22.1.0)

In an effort to have a prompt that is as flexible (i.e. not depend on any utilities) and as customizable as possible, I decided to make my own "elapsed mark" replacement. After reading the manual, I thought that the best way to do this is simply using these two functions:
```bash
function timer_start(){
  timer="$(date +%s%3N)"
}

function timer_stop(){
  duration="$(("$(date +%s%3N)"-"${timer}"))"
}
```
, registering two hooks:
```bash
blehook PREEXEC-+=timer_start
blehook POSTEXEC-+=timer_stop
```
, and adding `\${duration}` to my PS1.  

However, the duration I get this way (leftmost part of prompt) does not coincide with the result from `time`/elapsed mark:
![Screenshot 2023-05-25 at 2 56 15 AM](https://github.com/akinomyoga/ble.sh/assets/74119653/47a44afa-0446-40b3-9976-6b341197e027)

This situation made me wonder about the following things:
1) What is the proper way to do what I tried to do (i.e. which hooks should I use)?
2) What happens exactly (i.e. in the backend) from after I type a command until the prompt is drawn? Documentation on the Internet about this is not that good,  and who is better at answering this than someone who developed a readline replacement from scratch?
3) I benchmarked date itself with `time` and it seems to take 2-3ms. Therefore, how can the elapsed mark of ble.sh (which is written in Bash and I assume uses date behind the scenes) exactly coincide with time (which I suppose is compiled/uses C)?

**Comment by akinomyoga** [comment]
> 1. What is the proper way to do what I tried to do (i.e. which hooks should I use)?

I'd say you are actually doing it in the correct/expected way if you are trying to measure it by yourself.

The time metrics that ble.sh shows by the elapsed mark are tightly bound to the execution model of ble.sh and are not supposed to be modified by the users. But you can access the *results* of the measurements by ble.sh. They are accessible through the following variables in POSTEXEC:

- `_ble_exec_time_ata` (total time duration of the command execution in microseconds, based on `EPOCHREALTIME`)
- `_ble_exec_time_tot` (total time duration of the command execution in milliseconds, based on `time`)
- `_ble_exec_time_usr` (total CPU time in user mode)
  - `_ble_exec_time_usr_self` (CPU time in the main shell process in user mode)
- `_ble_exec_time_sys` (total CPU time in kerne model)
  - `_ble_exec_time_sys_self` (CPU time in the main shell process in user mode)

You can find an example in [`contrib/config/execmark.bash`](https://github.com/akinomyoga/blesh-contrib/blob/3ef03270740b6fbf8d49d40933386039c416b659/config/execmark.bash#L87).

> 2. What happens exactly (i.e. in the backend) from after I type a command until the prompt is drawn?

Many things happen. Major things happen in the following order:

1. history expansion, registering to the command history, etc.
2. [`ble-edit/exec:gexec/.begin`](https://github.com/akinomyoga/ble.sh/blob/0906fd959e6c3f08a63ca1eab815ed6acb9244d3/src/edit.sh#L6655)
3. [`ble-edit/exec:gexec/.prologue`](https://github.com/akinomyoga/ble.sh/blob/0906fd959e6c3f08a63ca1eab815ed6acb9244d3/src/edit.sh#L6693) PREEXEC is invoked here
4. Command execution ... related codes are dynamically generated by [this part](https://github.com/akinomyoga/ble.sh/blob/0906fd959e6c3f08a63ca1eab815ed6acb9244d3/src/edit.sh#L6890-L6896)
5. [`ble-edit/exec:gexec/.epilogue`](https://github.com/akinomyoga/ble.sh/blob/0906fd959e6c3f08a63ca1eab815ed6acb9244d3/src/edit.sh#L6758) POSTEXEC is invoked here
6. [`ble-edit/exec:gexec/.end`](https://github.com/akinomyoga/ble.sh/blob/0906fd959e6c3f08a63ca1eab815ed6acb9244d3/src/edit.sh#L6669) prompt and other rendering is performed inside `ble-edit/bind/.tail` called from this function.

> Documentation on the Internet about this is not that good,  and who is better at answering this than someone who developed a readline replacement from scratch?

I think none other than me. Or *the code* tells you everything. As far as I know, no one has ever read the details of the execution code. There is a related page in the ble.sh wiki, *[Internals · akinomyoga/ble.sh Wiki](https://github.com/akinomyoga/ble.sh/wiki/Internals)*, but the details (e.g. that are sufficient to understand the time measurements) are not written anyway.

> 3. I benchmarked date itself with `time` and it seems to take 2-3ms. Therefore, how can the elapsed mark of ble.sh (which is written in Bash and I assume uses date behind the scenes) exactly coincide with time (which I suppose is compiled/uses C)?

That is just because ble.sh uses `time` to measure the time. `ble.sh` doesn't use `date`, which has a spawn cost. In more detail, ble.sh combines three different ways to measure the times when used with Bash 5.2 (the combination changes depending on the Bash version): 1) The Bash built-in dynamical variable `$EPOCHREALTIME` to measure the high-resolution total time in microseconds. 2) The `time` keyword to measure the information, 3) The `times` builtin to measure the accumulated self/children times.

**Comment by akinomyoga** [comment]
Thank you!

> I use it in an environment where I cannot change my default shell from bash

I see. It is similar to one of the reasons that I developed ble.sh in pure Bash as much as possible.
