### ISSUE TITLE
completion select-by-number selects 1st entry when number > # of available choices is entered

### ISSUE THREAD

**Issue by bkerin** [akinomyoga/ble.sh#354]
GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu) [Linux Mint 20.3]
ble.sh, version 0.4.0-devel4+0906fd9 (noarch) [git 2.25.1, GNU Make 4.3, GNU Awk 5.0.1, API: 2.0 (GNU MPFR 4.0.2, GNU MP 6.2.0)]
bash-completion, version 2.10 (hash:b6da7f7edfc1c3c5196c86c81fb05fce96f83c03, 74550 bytes) (noarch)
locale: LANG=en_US.UTF-8
terminal: TERM=xterm-256color wcwidth=12.1-west/15.0-2+ri, vte:6003 (65;6003;1)

I would expect that when you push e.g. 4 when three options are available you would get a beep or something, or maybe the highest-numbered entry available (not good IMO but reasonable), but you get instead the first entry selected:

For example after tab:

```
$ file foomatic-
  1: foomatic-MWFL5V
  2: foomatic-QaQr7p
  3: foomatic-WVv5aX
```

Then after 4:

```
$ file foomatic-MWFL5V
  1: foomatic-MWFL5V
  2: foomatic-QaQr7p
  3: foomatic-WVv5aX
```

**Comment by bkerin** [comment]
I should have said this is using complete-by-number setup like so:

  bleopt complete_menu_style=linewise
  bleopt menu_linewise_prefix=' \e[1;32m%2d:\e[m '
  for key in {0..9}; do
    ble-bind -m emacs -f "$key" 'append-arg enter-menu'
    ble-bind -m vi_imap -f "$key" 'append-arg enter-menu'
    ble-bind -m menu_complete -f "$key" 'menu/append-arg always'
  done

**Comment by akinomyoga** [comment]
A good behavior in this case is subtle. I first need to tell you that the behavior of `append-arg enter-menu` is constructed as a combination of existing widgets, and its behavior is not designed from scratch. This is intentional. I would like to keep the consistency among different widgets.

The current behavior of `append-arg enter-menu` is that when a menu is open, ble.sh enters the `menu` mode before processing the numeric argument. Otherwise, the numeric argument is processed normally. In the menu mode, the numeric argument doesn't match the index of an existing menu item, it doesn't cause anything. As a result, the first entry is selected, which is the initial state of entering the menu mode. This is the current behavior.

(A) If I change anything of this behavior, one way is to ring a bell instead of doing nothing. In this case, ble.sh would still be kept in the menu mode, i.e., the first entry is selected.

(B) You might request to exit from the menu mode, but I wouldn't like such a behavior. In that case, the state of the editor after pressing the key depends on dynamic conditions. Here, the dynamic condition means the conditions that cannot be uniquely determined by the sequence of keys inputted by the user so far. If it doesn't enter the menu mode or exits from the menu mode when there is no corresponding item, whether it is currently in the menu mode or not cannot be uniquely determined by the key sequence inputted recently. Users usually do not input keys one by one by confirming what happened for each key, but they input keys in a sequence. If the current editor state can change based on a dynamic condition, the key sequences is interpreted in an unexpected way and cause problems.

(C) Another possibility that you suggest is to select the highest-number item. It is also related to the behavior of the existing treatment of numeric arguments in the menu mode:

- To enable the selection of the item of multiple-digit index, ble.sh accumulates the numeric arguments. For example, when the user inputs "9", "8", and "7", ble.sh connects them and internally forms the number "987". If item 987 exists, ble.sh selects it. Otherwise, the oldest digit `9` is discarded and item 87 is checked. If item 87 exists, ble.sh selects it. If the item is still not found, the number is further reduced to "7", and item 7 is selected if it exists. If even item 7 is not found, ble.sh eliminates all the numeric arguments, and thus it doesn't do anything.

To incorporate the idea of selecting the highest-number item in the above procedure, it is non-trivial in what stage we should apply it.

- If we apply the *highest-number-item* strategy from the beginning, it becomes impossible to re-select the item of a different index (unless the user presses another key). For example, after selecting item 12, the user wouldn't be able to use numeric arguments to select another item (say item 16) because it would result in a very big number `1216`, and it would be always considered the highest-number item.
- Applying the highest-number-item strategy only in the last failing case doesn't seem to be so consistent to me.

So currently what I can think is option (A), i.e., change ble.sh to ring a bell leaving all the other current behavior.

**Comment by bkerin** [comment]
Makes sense, sounds like A is indeed the best option here.

**Comment by akinomyoga** [comment]
I added an option `bell` to `menu/append-arg` in commit 3f31be18. You need to update the keybindings as

```bash
for key in {0..9}; do
  ble-bind -m emacs -f "$key" 'append-arg enter-menu:bell'
  ble-bind -m vi_imap -f "$key" 'append-arg enter-menu:bell'
  ble-bind -m menu_complete -f "$key" 'menu/append-arg always:bell'
done
```

**Comment by bkerin** [comment]
Resolved, thanks.

**Comment by akinomyoga** [comment]
I decided to make `bell` the default behavior (bbf3fed3). Now, one needs to specify `nobell` to turn off the bell as before.
