### ISSUE TITLE
In Macos, "option+delete" not able to delete previous word 

### ISSUE THREAD

**Issue by sshresthaEG** [akinomyoga/ble.sh#380]
**ble version**: 0.4.0-devel4+d1a1d538
**Bash version**: 5.2.21(1)-release (x86_64-apple-darwin23.0.0)

"option+delete" not able to delete previous word.
It used to work before installing ble.sh.
I don't have custom settings.
I am also getting `stty: 'standard input': unable to perform all requested operations` on every command.

**Comment by akinomyoga** [comment]
What is your terminal? It depends on the terminal control sequence that your terminal sends when you press "option+delete", but it would probably be `\x1b\x7F` (which is translated to <kbd>M-C-?</kbd>). The default keybinding in ble.sh for <kbd>M-C-?</kbd> is different from that in Readline. In ble.sh, The widget `copy-backward-sword` is bound to <kbd>M-C-?</kbd> and similar key combinations. It is described in [Manual §4.4](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A74-Editing#44-wordwise-movement-and-operation).

To get a similar effect, you can use <kbd>C-w</kbd> instead of <kbd>M-C-?</kbd>.

If you would like to use "option+delete" (such a <kbd>M-C-?</kbd> or <kbd>M-DEL</kbd> depending on the terminal) to delete the previous word, you can change the keybinding using `ble-bind`.

```bash
# blerc

# The key combination depends on the terminal, but you can bind it to all
ble-bind -f 'M-C-?' 'kill-backward-uword'
ble-bind -f 'M-DEL' 'kill-backward-uword'
ble-bind -f 'M-C-h' 'kill-backward-uword'
ble-bind -f 'M-BS' 'kill-backward-uword'
```

For the detailed behavior of determining the word boundaries, you might consider other types of words. Please read [Manual §4.4](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A74-Editing#44-wordwise-movement-and-operation).

----

> I am also getting `stty: 'standard input': unable to perform all requested operations` on every command.

This is an independent issue.

- **Q1**: Is the error message printed after the command or before the command? Or is it printed both before and after the command? By "before/after the command", I mean the following places:

```bash
$ echo hello # This is an example command
<-- (Before the command)
hello
<-- (After the command)
```

- **Q2**: Could you provide the results of the following commands?

```bash
$ declare -p _ble_term_stty_flags_{enter,leave}
$ type ble/bin/stty
```

**Comment by syuraj** [comment]
In any terminal (iterm, warp, vscode integrated terminal) in my macos, I see similar behaviour (option + del) not working.
That `stty` is printed before running the command.

**Comment by akinomyoga** [comment]
Thanks for the information. Could you provide an answer to **Q2** in my previous reply?

**Comment by akinomyoga** [comment]
@syuraj Could you provide an answer to **Q2** in https://github.com/akinomyoga/ble.sh/issues/380#issuecomment-1863457271?

**Comment by syuraj** [comment]
no, I deleted this sh*t

**Comment by akinomyoga** [comment]
It's fine that you stopped using ble.sh and are not willing to continue the discussion, but I'd have appreciated it if you could have informed us of it earlier instead of ignoring the reply for one month and suddenly insulting the project. Also, we are not forcing you to use ble.sh. You can complain about it to the one who forced you to use ble.sh with a polite attitude.
