### ISSUE TITLE
Blinking cursor is distracting

### ISSUE THREAD

**Issue by n87** [akinomyoga/ble.sh#393]
Please put in README how to have normal non blinking cursor (even better, make it default). Also, some people prefer to set their own blinking interval (but that's likely other feature')

**Comment by akinomyoga** [comment]
Thanks for the report, but I cannot reproduce the reported behavior in the latest version of ble.sh. It is possible to force it to use the steady block cursor, but before that I need to confirm the current situation.

- **Q1**: Which version of ble.sh do you use? If you use ble-0.3, please use ble-0.4.

  ble-0.3 sets the cursor to the *terminal's default*, while ble-0.4 doesn't change the cursor style unless it is specified by the user in its configuration `~/.blerc`. Another option is, if your terminal allows it, please change the *terminal's default cursor style* to the one that you want. It depends on the terminal, but some terminals only allow the initial cursor style but not the default cursor style.

- **Q2**: If you use the latest version of ble.sh, does the problem reproduce when you remove all the settings from `~/.blerc`?

**Comment by akinomyoga** [comment]
> Also, some people prefer to set their own blinking interval (but that's likely other feature')

That's not the part the terminal applications (like ble.sh) can control. The blinking is implemented by the terminal, so the terminal needs to provide the configuration. What terminal applications can do is just to specify whether to enable the blinking cursor feature of the terminal.

Which terminal emulator do you use?

**Comment by n87** [comment]
Tested with activation using `source ble.sh/out/ble.sh`.

VT: blinking regardless of ble.sh
Alacritty: no blinking before and after sourcing
Alacritty with tmux: blinking if i `source ble.sh` from inside tmux. In opposite order (source, then launch tmux) there is no blinking

Now that I see how to avoid blinking, feel free to close the issue (or investigate this weird interaction with tmux if you have time).

**Comment by akinomyoga** [comment]
> (or investigate this weird interaction with tmux if you have time).

If this is the behavior observed in ble-0.3, it's already fixed in ble-0.4 so that's fine. However, if this happens with ble-0.4, I need to investigate it. Could you answer **Q1**? If you are not sure, can you provide the result of the following command?

```bash
$ echo $_ble_version
```

**Comment by n87** [comment]
answer for both: I've just cloned it from git today, so the version  is 0.4 (`400`). And there is no `.blerc`.

I've also just tried to reproduce in `wezterm` and there is no blinking.

**Comment by akinomyoga** [comment]
Thank you for those answers! So it means that there is still a problem with ble-0.4.

> Alacritty with tmux: blinking if i `source ble.sh` from inside tmux. In opposite order (source, then launch tmux) there is no blinking

Thanks for this information! I tried to reproduce the problem with this setup, but the blinking cursor doesn't seem to reproduce in my environment. The Alacritty version I tested is 0.12.3. Tmux version says `next-3.4` (though I'm not sure what is `next`). Hmm.

**Comment by akinomyoga** [comment]
I also tried other tmux versions, `3.3a`, `3.2a`, and `3.1`, but the blinking cursor doesn't seem to reproduce.

- **Q3**: What is your tmux version?

```bash
$ tmux -V
```

I'd like to check the possibility of interference with other configurations.

- **Q4**: Do you have any other settings in bashrc? With the minimal bashrc with ble.sh, does the problem reproduce?

**Comment by n87** [comment]
Q3: tmux 3.3a
Q4: after trying to isolate the problem, seems I have found something close to the root cause.

```
tmux -f /dev/null new-session "env -i TERM=screen-256color bash --noprofile --init-file src/ble.sh/out/ble.sh"
```

This will make cursor blink. With `TERM=alacritty` (default) there is no blinking.
My `tmux.conf` sets TERM to `screen-256color` as part of `tmux-sensible` setup. I don't remember what will break if I don't use this.

**Comment by akinomyoga** [comment]
Thank you. Now I can reproduce the behavior in my environment, though I'm not sure what causes this issue.

**Comment by akinomyoga** [comment]
I've identified the issue and fixed it in commit f9b9aea8. Could you update ble.sh by running `ble-update` and see if the problem doesn't arise?

----

Here's the summary: The terminal's control sequence for hiding/revealing the cursor was interfering. ble.sh tries to use the terminfo database if it is available, but terminfo doesn't have entries for *purely* hiding/revealing the cursor even though terminals support it. The terminfo entries `civis`, `cnorm`, and `cvvis` are related, but there is no entry to purely revert the effect of hiding the cursor. Here, ble.sh tries to guess the control sequences for hiding/revealing the cursor based on `civis`, `cnorm`, and `cvvis`.

The problem was that `ble.sh`'s guess contains the special treatment for the terminfo results that are typically returned by `screen` (GNU Screen) was not correct. I don't remember what was my consideration on that special treatment, but according to my note then, I think I was confused by the man page of GNU Screen saying that mode 34 is "Normal Cursor Visibility". However, mode 34 seems to be typically the blinking cursor, and GNU Screen doesn't seem to translate 34 to a proper "Cursor Visibility" for the outside terminal. So it didn't work either in GNU Screen.

I decided to update the entire guess to a more conservative one.

**Comment by n87** [comment]
No blinking now, thanks! I appreciate you taking time to solve this tricky issue

**Comment by akinomyoga** [comment]
Thank you for the confirmation! Thank you again for the report!
