### ISSUE TITLE
vim insert mode: `C-RET` doesn't work for multiline commands

### ISSUE THREAD

**Issue by 10b14224cc** [akinomyoga/ble.sh#405]
**ble version**: 
**Bash version**: 
```
GNU bash, version 5.2.26(1)-release (x86_64-pc-linux-gnu) [Arch Linux]
ble.sh, version 0.4.0-devel4+27e6309e (noarch) [git 2.43.0, GNU Make 4.4.1, GNU Awk 5.3.0, API 4.0, PMA Avon 8-g1, (GNU MPFR 4.2.1, GNU MP 6.3.0)]
starship, version 1.17.1 (rustc 1.75.0 (82e1608df 2023-12-21) (Arch Linux rust 1:1.75.0-1), 2024-01-03 07:54:53 +00:00)
zoxide, version 0.9.2 (/usr/bin/zoxide)
atuin, version 17.2.1 (/usr/bin/atuin)
locale: LANG=en_US.UTF-8 LC_TIME=en_DK.UTF-8
terminal: TERM=xterm-kitty wcwidth=15.0-west/15.1-2+ri, kitty:0 (1;4000;32)
```
1. Set up ble.sh to use vim mode
2. Enter insert mode
3. Copy-past a multi-line command like [this](https://github.com/DreamMaoMao/hycov?tab=readme-ov-file#using-meson-and-ninja)
4. Press `CTRL-RET`. The cursor goes on to a new line, a newline is created, but the commands are not run. This is against [documented behavior](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A76-Vim-Mode#621-insert-mode-vi_imap)
5. Press `CTRL-j`. The commands are correctly executed in their order.

**Comment by akinomyoga** [comment]
Thanks, indeed I find an inconsistency between the documentation and the actual default binding. I don't remember which one is the one that I originally intended.

I checked the change history. When the vi mode implementation was first introduced, <kbd>C-RET</kbd> seems to have meant the history expansion (*history-expand-line*) ([`f82cbc4`](https://github.com/akinomyoga/ble.sh/commit/f82cbc4bb2a30d33b82266a6f1a29aee04445574#diff-132d7ae879e190d76a39ea80380e23eccbb6640fff757b73b468eb32433ebb80R36)), which inherited the binding in the emacs mode ([`c68412b`](https://github.com/akinomyoga/ble.sh/commit/c68412b488589925e7fefb98c7153ff36a322189#diff-7b16f48e021587bd7b2f849491e3e274d8a3398fe398d61be02141f322ac9417R2226)). I soon changed it to mean the insertion of a newline (*newline*) ([`4b68c1c`](https://github.com/akinomyoga/ble.sh/commit/4b68c1cdc9d1ae8379b3f67a343b6312cc8a8497#diff-132d7ae879e190d76a39ea80380e23eccbb6640fff757b73b468eb32433ebb80R1364)). I later decided to change it to mean the forcible execution of the command (*accept-line*) ([`2bc1a83`](https://github.com/akinomyoga/ble.sh/commit/2bc1a838ae06e8f95dc8fa9520cd956671c6f1db#diff-132d7ae879e190d76a39ea80380e23eccbb6640fff757b73b468eb32433ebb80R6817)) in `vi_imap` together with other keymaps. However, it was reverted to *newline* in commit [`2b20c88`](https://github.com/akinomyoga/ble.sh/commit/2b20c880f945c422380ac72c7593846e3c6391d3#diff-132d7ae879e190d76a39ea80380e23eccbb6640fff757b73b468eb32433ebb80), which doesn't seem to be intentional. Also, <kbd>C-RET</kbd> in `vi_map` is inconsistent with other keymaps. I think I should change it back to *accept-line*.

Thank you for the report. I'll later update the default keybinding of `vi_imap`.

I'm currently working on other parts of ble.sh, so I'll apply the fix later. Until I push the fix, could you temporarily bind <kbd>C-RET</kbd> to the original one in your `~/.blerc`?

```bash
# blerc

ble-bind -m vi_imap -f C-RET accept-line
```

**Comment by 10b14224cc** [comment]
Well I can use`C-j` for the time being :)

**Comment by akinomyoga** [comment]
I pushed a fix 0b18f3c254d7bc16728f840f94447cff957ecd46. Could you check the behavior?

**Comment by akinomyoga** [comment]
@10b14224cc Have you checked this? Can I close the issue?

**Comment by 10b14224cc** [comment]
Now `RET` creates a new line and `CTRL-RET` execute the whole command

**Comment by akinomyoga** [comment]
Thanks for the confirmation!
