### ISSUE TITLE
[MAC][iTerm2] Ctrl+d does not exit, disables backspace

### ISSUE THREAD

**Issue by gregwalters** [akinomyoga/ble.sh#416]
**ble version**: 0.4.0-devel4+b593819
**Bash version**: 3.2.57(1)-release (arm64-apple-darwin23)

I just setup atuin and ble.sh on my mac with iTerm2 using bash instead of whatever the default is and I can no longer use the ctrl+d sequence to exit a bash session. Typing "exit" and pressing enter works. After a failed ctrl+d the backspace key no longer works but ctrl+c will still get me a new prompt.

**Comment by akinomyoga** [comment]
Could you install the latest version of Bash (for example through `brew`)?

I actually have never tested Bash 3.2 on macOS. `ble.sh` with Bash 3.2 seems to be currently working in Linux and on MSYS1/Windows, but it is challenging to support Bash 3.* in various systems. In addition, I don't have macOS, so it is unlikely to be able to debug the phenomena.

Even if I managed to fix the problems or identify necessary workarounds, `ble.sh` is *extremely slow* and some important features such as autosuggestions cannot be supported in Bash 3.2 because Bash 3.2 has severe limitations in its feature set.

**Comment by gregwalters** [comment]
`5.2.26(1)-release (aarch64-apple-darwin23.2.0)`

Issue resolved. Thanks for the quick response!

**Comment by akinomyoga** [comment]
Thanks!
