### ISSUE TITLE
Simplify README

### ISSUE THREAD

**Issue by guettli** [akinomyoga/ble.sh#453]
I came here because `atuin` links to ble.sh.

Up to now ble.sh was new to me.

The README is a bit long for newcomers.

Maybe it makes sense to move parts about building ble.sh do a second document?

**Comment by akinomyoga** [comment]
Thanks for trying ble.sh.

That part is just my small attempt to counter the arguments by some people who even without trying ble.sh declared that they "cleverly" knew *I don't have an ability and ble.sh is broken* just by `make` on README or the language char of the repository. I could remove that part, or, actually, I'm thinking of switching the primary installation method to the nightly version at some point.

However, even if that part is removed, I think the essential length of README wouldn't be changed. All the descriptions in README are related to something frequently asked by users or something I anticipate that the users might face in their first uses of ble.sh. Since ble.sh is doing something non-trivial and affects many parts of the shell, it might cause unexpected behaviors in certain environments. I feel we should still put an intentional barrier. If the lengthy README would be a dealbreaker for that user, I wouldn't recommend the user to use ble.sh.

**Comment by guettli** [comment]
I use the bash since more than twenty years. But today is my last day.

I had a look at how many people contribute to ble.sh, and I see that is mostly only you.

I don't want to pressure you with my ideas and feature requests. I always have ideas, and I usually tell them via feature requests.

Looked at alternatives, and the Fish shell looks good.  I moved my bashrc config to fish in just a few minutes.

Of course, I will keep on writing bash scripts, but I think for interactive usage I will stick to Fish.

Sorry for the noise, but maybe you are interested in that.

Thank you very much for trying to improve the interactive experience with Bash.

**Comment by akinomyoga** [comment]
I'm not how I should take your comments, but from an objective point of view, I have to say users who want those features should normally use Zsh or Fish. `ble.sh` would be useful for the users who need to log in to many different hosts where Zsh or Fish is not always available, or the users who are used to the detailed behavior of Bash and want to use Bash constructs in their interactive sessions.

The reason that essential parts of the code is mostly written by me is not that I had rejected all the feature requests and pull requests, but just because I haven't received an essential amount of the pull requests so far. I think this is normal for projects that are not known well. Feature requests and suggestions are always welcome, but that doesn't mean I'll accept every request. Just as you have *ideas*, I have more concrete ideas for this project that have been accumulated for ten years.

I'm always looking at the features in Zsh and Fish but am not interested in Fish for my personal interactive use. As written in README, ble.sh is largely motivated by Zsh and Fish. There are my own reasons that I don't just use them.
