### ISSUE TITLE
Unknown widget `-'.

### ISSUE THREAD

**Issue by dylankb** [akinomyoga/ble.sh#46]
**ble version**: 0.4.0-devel2+0d9d867
**Bash version**: 5.0.16(1)-release,x86_64-apple-darwin18.7.0

I recently started getting this error whenever I start a new terminal session. It's a bit odd since as far as I can remember I did not change any dot files configuration (`.blerc`, `.bashrc`, etc.) or update ble around the time it started happening. Any ideas what might be cause this or tips for debugging?

```
ble-bind: Unknown widget `-'.
ble-bind: Unknown widget `-'.
$ ble-bind: Unknown widget `-'.
```

**Comment by akinomyoga** [comment]
Thank you... Does it reproduce with the option `--noinputrc` (which is the option on sourcing ble.sh as follows)?

```bash
# bashrc
source ble.sh ... --noinputrc
```

**Comment by akinomyoga** [comment]
It seems it is related to the readline functions that `ble.sh` doesn't support. I fixed error messages 91bdb64. Can you check the error messages with the latest commit?

**Comment by dylankb** [comment]
I updated my `.bashrc` file and received the same type of output. This is the line I changed.

```
[[ $- == *i* ]] && source .../ble.sh --noattach --noinputrc
```

After updating ble these are now the error messages I'm getting.

```
ble.sh (bind): unsupported readline function 'emacs-editing-mode' for keymap 'vi_nmap'.
ble.sh (bind): unsupported readline function 'emacs-editing-mode' for keymap 'vi_imap'.
ble.sh (bind): unsupported readline function 'vi-editing-mode' for keymap 'emacs'.
```

I recently updated my Mac laptop's OS, so perhaps that's related to this issue somehow.

**Comment by akinomyoga** [comment]
OK, thank you for the details! `emacs-editing-mode` and `vi-editing-mode` wasn't supported by `ble.sh`. I newly added support for these widgets 0c6c76e.

Considering that you have updated the system recently and `--noinputrc` doesn't solve the problem, I guess some new configurations that use these widgets are added to somewhere `/etc/bashrc` or `/etc/profile.d/*`. Now you can remove `--noinputrc` in the argument of `ble.sh` (because it is actually a deprecated option).

**Comment by dylankb** [comment]
That fixed the issue. Thanks so much!

**Comment by akinomyoga** [comment]
Thank you for your check!
