### ISSUE TITLE
Brace Expansion

### ISSUE THREAD

**Issue by orionalves** [akinomyoga/ble.sh#482]
**ble version**: 0.4.0-devel3+32277da
**Bash version**: 5.2.15(1)-release (x86_64-pc-linux-gnu)
GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu) [Debian GNU/Linux 12 (bookworm)]
ble.sh, version 0.4.0-devel3+32277da (noarch) [git 2.30.2, GNU Make 4.3, GNU Awk 5.1.0, API: 3.0 (GNU MPFR 4.1.0, GNU MP 6.2.1)]
bash-completion, version 2.11 (hash:aefcfdd4b924e8b03db0d49be8bdb5881ad7d0cd, 77084 bytes) (noarch)
locale: LANG=pt_BR.UTF-8
terminal: TERM=xterm-256color wcwidth=15.0-west/15.0-2+ri, wt:0 (0;10;1)

I cant do a simple brace expansion
```
echo {1..10000000000000000}
{1..10000000000000000}
```

I cant write "echo {1..10000000}", crash my system, but I can paste "echo {1..10000000000000000}" and execute, but dont work for me.

**Comment by akinomyoga** [comment]
Thanks for the report, but I'm not sure what we should do then. What would you expect?

If you explicitly request a large number for a brace expansion that the machine cannot handle, of course, the machine cannot handle it. Maybe the limit is lowered by a factor by using ble.sh, and that limit is triggered in the input stage with ble.sh. However, the limit exists even with the plain Bash on the execution stage, and Bash crashes without ble.sh in such a case.

**Comment by orionalves** [comment]
Thanks for the explanation. But ble won't allow to me write. It crashes while I write. Bash dont crash while I write.

**Comment by akinomyoga** [comment]
> But ble won't allow to me write. It crashes while I write. Bash dont crash while I write.

That is because ble.sh needs to expand the words for syntax highlighting, completions, etc. while the user inputs the characters. For example, to determine the color of the word based on whether the word matches the filename, it needs to first expand the word to obtain the actual value that may match a filename. For another example, to generate the autosuggestions, ble.sh needs to expand the current word to get the prefix string that is used to filter the candidates.

Bash doesn't crash while you input characters because Readline (i.e. the default line editor of Bash) doesn't perform the expansion of words, and that is because Readline doesn't offer features that require word expansions.

I will later try to improve the situation by tweaking the related codes, but I have to say it is impossible to *completely* remove the problem as far as ble.sh performs word expansions while keeping the current useful features. For example, you might suggest disabling brace expansions in processing the words inside ble.sh, but ble.sh performs brace expansions because it is useful in improving the user experience (as far as the size of brace expansions input by the user is a realistic one). So here is a tradeoff: "usefulness in realistic cases" vs "safety in unrealistic cases", where I choose the former in the present case.

In general, if we start to care about unrealistic cases too much, it would impose unrealistic restrictions on the implementation and the feature set. Then, the question is why you would have a chance to input an extremely large number in the brace expansions if it would never be executed. Is that a realistic situation?

If you *crafted* those examples just to show that ble.sh can be broken, I'm not sure if avoiding this pattern would actually satisfy you because you will be able to craft another unrealistic pattern that can kill `ble.sh`. It'd be endless.

**Comment by orionalves** [comment]
Thanks a lot.

**Comment by akinomyoga** [comment]
In commit 6833bdf88c719256856a6f9948e6590cf2ea6eba, I added a new option [`bleopt highlight_eval_word_limit`](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A72-Graphics#user-content-bleopt-highlight_eval_word_limit) and set a limit 200 by default for the number of words that are processed for highlighting a single word. This would make the response of ble.sh significantly lighter than before (in the range about `{1..100000}`).

However, the expansion itself is still performed, so if you try to input e.g. `{1..10000000}`, it would still use the excessive memory of the system. The second example `{1..10000000000000000}` would never be processed because it requires at least about 300 petabytes of RAM.
