### ISSUE TITLE
Tab completion fails when there is no match in the directory, but there is a history match

### ISSUE THREAD

**Issue by nolanl** [akinomyoga/ble.sh#493]
**ble version**: 0.4.0-devel4+70a325f9
**Bash version**: 5.2.15(1)-release (x86_64-pc-linux-gnu)

ble.sh + starship + atuin

It seems like tab completion completes to the first dirent in $PWD if there is a partial prefix match to something in the history. For example:

```
…/pyinfra-examples $ ls
deploy-functions  inventory-functions  LICENSE.md  python-web-app  README.md  utils.sh
[ main]
…/pyinfra-examples $ cd python-web-app/
[ main]
…/pyinfra-examples/python-web-app $ ls
deploy.py  docker-start.sh  docker-stop.sh  group_data  inventories  README.md  tasks  templates
[ main]
```

At this point, typing `cd py` and hitting `<TAB>` results in instant completion to `cd deploy.py`. Notable, there is no dirent starting with "py" in $PWD.

**Comment by akinomyoga** [comment]
That is the design. It's not the completion based on the history, but the completion based on ambiguous matching. The TAB completion doesn't perform any history completion.

In the above case, the completion undergoes the following processes: First, no completions are generated by the cd completion setting. Then, `ble.sh` next attempts a fallback completion for the general filename matching. Since there is no filenames starting with `py`, it next attempts to find filenames that contain `py` as a *substring*. Then, only `deploy.py` matches, so `deploy.py` is inserted.

If you want to disable the fallback completion, you can turn off the builtin `cd` completion by `unset -f ble/cmdinfo/complete:cd`, and you can write a completion setting for `cd` by yourself, where `compopt +o ble/default` can be called inside a completion function. An easy way to implement such a completion function is to run `compopt +o ble/default` and then call the completion function provided by `bash-completion`.

**Comment by nolanl** [comment]
Thanks for the explanation and the workaround!
