### ISSUE TITLE
Get rid of (arg: X) and (XX.X% processing input...) message

### ISSUE THREAD

**Issue by digitalguy99** [akinomyoga/ble.sh#497]
Every time I type `Esc+-` or some other unbound key sequences that start with `Esc`, I would end up with a 
(arg: X) message underneath the command line. Additionally, when I perform a left click on it, I would have the (XX.X% processing input...) message pop up at the same place. You can see how they look like below:

https://github.com/user-attachments/assets/a14e5b5d-acb8-490e-95b3-cb3f87cad4d3

I have looked all over the manuals and could not find anything about them. Hence, I would really appreciate it if you could guide me on how to remove those messages.

**Comment by akinomyoga** [comment]
> Every time I type `Esc+-` or some other unbound key sequences that start with `Esc`, I would end up with a (arg: X) message underneath the command line.

This is intensional behavior, and the behavior is similar even without `ble.sh`. When you press <kbd>M--</kbd> (i.e., <kbd>Esc</kbd>+<kbd>-</kbd>), `ble.sh` (and also Readline) start the mode to prefix a digit argument to the next editing function. Inside that mode, both `ble.sh` and Readline show the current digit argument in the terminal.

What is the purpose for you to press "Esc+-"? If you expect some other behavior by pressing "Esc+-", you need to configure it using `ble-bind`. If you don't expect nothing to happen when you input "Esc+-", please just bind it to the "nop" widget:

```bash
# blerc

ble-bind -f 'M--' nop
```

----

> Additionally, when I perform a left click on it, I would have the (XX.X% processing input...) message pop up at the same place.

Which terminal do you use? Also, what is the result of the following command?

```bash
$ ble/widget/display-shell-version
```

What I suspect is that when you click somewhere in the terminal below the command line, your "terminal" sends a long sequence of cursor keys [such as <kbd>right</kbd><kbd>right</kbd><kbd>right</kbd><kbd>right</kbd>... x (as many as the terminal width + α)] to *attempt to move* the cursor to the clicked position. This would cause the terminal to send a large data to `ble.sh`. `ble.sh` may take a long time to process such a *large* data, so it shows the progress of processing the large input.

If you don't want that behavior, you should turn off the terminal's feature through the terminal's configuration. `ble.sh` is not responsible for this behavior of the terminal.

If you want to keep the feature to move the cursor to the clicked position while at the same time, you want to suppress the large input, you need to find a way to configure the terminal so that the terminal doesn't mistakenly recognize the next line as a part of the command line.

**Comment by digitalguy99** [comment]
> This is intensional behavior, and the behavior is similar even without ble.sh. When you press M-- (i.e., Esc+-), ble.sh (and also Readline) start the mode to prefix a digit argument to the next editing function. Inside that mode, both ble.sh and Readline show the current digit argument in the terminal.

I see, I didn't realize that. 

> What is the purpose for you to press "Esc+-"? If you expect some other behavior by pressing "Esc+-", you need to configure it using ble-bind. If you don't expect nothing to happen when you input "Esc+-", please just bind it to the "nop" widget:

I just want it so that Esc+anything not show any messages. So thank you for the solution, I was able to do what I want by using the following:
```bash
ble-bind -k 'ESC' nop
```

> Which terminal do you use? Also, what is the result of the following command?
> 
> ```shell
> $ ble/widget/display-shell-version
> ```

I use Windows Terminal and the result of the command you have given is as follows:
```
GNU bash, version 5.2.26(1)-release (x86_64-pc-msys)
ble.sh, version 0.4.0-devel3+e3cdb9d (noarch) [git 2.34.1.windows.1, GNU Make 4.3, GNU Awk 5.0.0, API: 2.0 (GNU MPFR 4.1.0, GNU MP 6.2.1)]
oh-my-bash (pzq-shell_integration), version 1.0.0+6d62b33e (noarch), aliases(general), completions(git composer ssh), plugins(git bashmarks)
locale: LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8
terminal: TERM=xterm-256color wcwidth=15.0-west/15.0-2+ri, wt:0 (0;10;1)
```

>What I suspect is that when you click somewhere in the terminal below the command line, your "terminal" sends a long sequence of cursor keys [such as rightrightrightright... x (as many as the terminal width + α)] to attempt to move the cursor to the clicked position. This would cause the terminal to send a large data to ble.sh. ble.sh may take a long time to process such a large data, so it shows the progress of processing the large input.

Yes, it seems like it is just as you said. But, I'm still wondering if there is a way to not have the (XX.X% processing input...) message displayed while ble.sh is processing the data.

**Comment by akinomyoga** [comment]
> But, I'm still wondering if there is a way to not have the (XX.X% processing input...) message displayed while ble.sh is processing the data.

You can use the following settings:

```bash
# blerc

_ble_decode_show_progress_hook=
_ble_decode_erase_progress_hook=
```

However, it should be noted that even if the message is not shown, `ble.sh` is still blocked while it processes the input.

**Comment by digitalguy99** [comment]
Thank you very much, that's exactly what I needed. You can close the issue now.
