### ISSUE TITLE
Project is not buildable from git archive

### ISSUE THREAD

**Issue by LecrisUT** [akinomyoga/ble.sh#509]
Small suggestion, how about using `.gitattributes` in order to save the commit reference instead of using `git format` command in:
https://github.com/akinomyoga/ble.sh/blob/32f290df78554e22d7ff779d34f1dfec271c16df/ble.pp#L79

You can see an example in:
https://github.com/scikit-build/scikit-build-core/blob/main/.git_archival.txt
https://github.com/scikit-build/scikit-build-core/blob/main/.gitattributes

I think one option would be to package a similar `.git_archival.txt` and read the file for the commit hash, and if that fails use the `git format` approach (or vice-versa)

**Comment by akinomyoga** [comment]
Thanks for the hint, but I'm wondering how this should be used.

As far as I read the documentation of the `export-subst` attributes at [`export_subst` - gitattributes](https://git-scm.com/docs/gitattributes#_export_subst) and [`export_subst` - git-archive](https://git-scm.com/docs/git-archive/2.29.0#Documentation/git-archive.txt-export-subst), it affects the result of `git archive`. However, even if the git commit hash is solved with the suggested `export-subst`, the git archive still doesn't build because it is missing the contents of the submodule.

Is there a way to use `export-subst` other than `git archive`? Or is there a way to make `git archive` include the contents of the submodule recursively?

**Comment by LecrisUT** [comment]
Re: submodules, one recommendation was to use [`git-archive-all`](https://github.com/Kentzo/git-archive-all). It's been a while since I've looked into these, but I remember there being some nuance regarding reproducible archiving.

Original this issue regards Fedora packaging where we would get the git archive of each submodule and then just move them inplace where they are expected.

Regarding how to use `export-subst`, basically any text under `$...$` will be replaced using the format flags, but it is sufficient to consider only `$Format:%H$` which expands to the git commit, although quite a useful one is `$Format:%(describe:tags=true,match=*[0-9]*)$` which expands to the `git describe` text. Using this within `ble.pp` would be a bit too much, but if you keep a `.git_archival.txt` file than you can simply query the info there and substitute it manually in the makefile.

**Comment by akinomyoga** [comment]
The use cases seem minor (compared to `git archive` if it were working), but I'll consider it as a fallback of the `commit_hash` resolution.

**Comment by LecrisUT** [comment]
> I'll consider it as a fallback of the `commit_hash` resolution.

That would be perfect for us. For reference, here are the changes I am proposing in the Fedora review to make it buildable:
```console
$ rm -rf contrib
$ tar -xf %{SOURCE1}
$ mv blesh-contrib-* contrib
$ sed -ie 's/| \.git.*//' GNUmakefile
$ sed -ie 's/#%%\[commit_hash =.*/#%%[commit_hash = "fedora"]/' ble.pp
```
(`SOURCE1` is the path to `blesh-contrib` git archive, we need to remove the `.git` requirement in the GNUmakefile, and we are changing the `commit_hash` calculation (here I was considering "fedora" just because I was thinking it is only used for display and it would be a better indicator))

**Comment by blackteahamburger** [comment]
Related: I use [this patch](https://github.com/microcai/gentoo-zh/blob/bcbc6f6204749467abdb789affef2c8837119d82/app-shells/blesh/files/blesh-0.4.0_pre3-no-git.patch) to entirely get rid of git.

**Comment by akinomyoga** [comment]
@LecrisUT @blackteahamburger I updated `GNUmakefile` in commit 31f264adb120e92e6bb1c90b8542018ea407232f. You'll probably need to adjust your patches/packaging scripts when you switch to the latest version.

@LecrisUT Although I updated it to use `export-subst`, it's not sufficient to make `ble.sh` *buildable from git archive* (as in the issue title) as we already discussed. I actually don't plan to make `git archive` just work partly because it is not a way that I recommend the users. Of course, users are allowed to attempt using `git archive`, but such users would be supposed to adjust it 
by themselves (as you did). Would that be fine?

**Comment by LecrisUT** [comment]
Thanks for working on this :). I'm not good with Makefiles, so could you help me a bit decipher some of the changes?
- The change around `GIT_VERSION` means that if the variable `GIT_VERSION` is not actually used, the `git --version` command would not run right? Is it possible to also override this value by passing it in the `make` command?
  (this is not critical, we can work around it seemingly easy)
- The logic around `BLE_GIT_COMMIT_ID` is that: Check if `.git` is present (if so use `git` commands) -> otherwise check that `make/.git-archive-export.mk` has been expanded (if so source the make file) -> otherwise error.
- What part of the `git archive` does not work? Just the submodule not being included?
- Afaiu, the changes in the Fedora recipe after this change is now just the first part to copy the submodule files in the appropriate directory?
  ```console
  $ rm -rf contrib
  $ tar -xf %{SOURCE1}
  $ mv blesh-contrib-* contrib
  ```

**Comment by akinomyoga** [comment]
> * The change around `GIT_VERSION` means that if the variable `GIT_VERSION` is not actually used, the `git --version` command would not run right?

Partially yes, and partially no. If *the value* of `GIT_VERSION` is unused, `git --version` is not run.

> Is it possible to also override this value by passing it in the `make` command?

It is already possible.

You first need to understand that those assignments `var = xxx`, `var := xxxx`, and `var += xxxx` in `Makefile` define **the default value** of the variable, and it can always be overridden by specifying `make var=yyy`. Next, you need to understand the difference between `var = xxx` and `var := xxx`; `var = xxx` defines a template where the expansions `$(...)` in the right-hand side are kept as is and will be expanded *on the evaluation stage* of `var`, while `var := xxx` performs the expansions in the right-hand side *on the assignment stage* and retains the expansion result as a value. Here, we use the form `var = xxx` for `GIT_VERSION`, so the expansion of `$(shell git --version)` is not performed on the assignment stage, and if `GIT_VERSION` is overridden through an argument, `$(shell git --version)` will never be expanded.

> * The logic around `BLE_GIT_COMMIT_ID` is that: Check if `.git` is present (if so use `git` commands) -> otherwise check that `make/.git-archive-export.mk` has been expanded (if so source the make file) -> otherwise error.

Yes.

> * What part of the `git archive` does not work? Just the submodule not being included?

At least, the submodule doesn't work. I haven't further tried to make it work because I don't think it's worth it unless the submodule is solved. So I haven't checked whether other problem arises, and I don't think we need to do it. As I have written,

"such users would be supposed to adjust it by themselves"

which means that I would not investigate and test what you need to do to make it work.

 > * Afaiu, the changes in the Fedora recipe after this change is now just the first part to copy the submodule files in the appropriate directory?

Could you test that in your environment? I don't have the environment. What I can tell *without investigation and testing* is that I currently don't recognize anything that blocks it except for the submodule.

**Comment by LecrisUT** [comment]
Cool, thanks for the clarifications. Indeed we (the packagers) will be responsible for making it work within our own environment's limitations. Just for context, the limitation of using the direct git archive source is due to the whole `xz-util` saga. If anything new comes up in our packaging process, we'll give you as much of a reproducible environment as we can (I usually construct a simple dockerfile to reproduce).

For now I will close this issue, unless @blackteahamburger needs to reopen it further?

The final part is when can we expect a new release, or what issues should we track for it?

**Comment by akinomyoga** [comment]
Thanks!
