### ISSUE TITLE
MacOS arrange window shortcuts

### ISSUE THREAD

**Issue by nitko12** [akinomyoga/ble.sh#516]
Hi,

I've just installed ble.sh and it's an awesome project!

But I've noticed that new MacOS window arranging features seem to clash with the defaults.

The used binds are ^Home, ^End, ^Page Up, ^Page Down (control + fn + arrows)

I've tried disabling bind using ble-bind but can't find which ones clash, I've also disabled binds in iTerm2 terminal emulator and it worked before installing.

Any help would be appreciated :)

**Comment by akinomyoga** [comment]
Thanks for trying out `ble.sh`. Could you describe what you want to achieve in a bit more detail?

- **Q1**: In particular, do you want to call the macOS window arrange features by these keybindings? Or do you want to call ble.sh's features by them?

> The used binds are ^Home, ^End, ^Page Up, ^Page Down (control + fn + arrows)

- **Q2**: If I'm not mistaken, do you mean <kbd>Control+Home</kbd>, <kbd>Control+End</kbd>, <kbd>Control+PageUp</kbd>, <kbd>Control+PageDown</kbd> by these caret notation? Is my understanding correct?

> I've tried disabling bind using ble-bind but can't find which ones clash,

- **Q3**: What do you mean by "disabling bind"? Do you try to disable the binding of macOS window arrangement using `ble-bind`? I'm not a user of macOS, but ble.sh's `ble-bind` only configures the keybindings for ble.sh. There should be a system interface for the keybindings for the macOS window arrangement. If you try to disable ble.sh's keybindings, I suspect it is unneeded because the system keybindings should take a higher priority than ble.sh's, so you can just configure the macOS window arrangement in the system interface.

- **Q4**: If you tried some keybindings with `ble-bind`, could you provide the actual commands you tried? Maybe I can point the problem. Some hints:
  - The list of bindings can be obtained by `ble-bind -P`.
  - In ble.sh's *keyspec* notation, <kbd>Control+Home</kbd> corresponds to `C-home`, <kbd>Control+End</kbd> corresponds to `C-end`, <kbd>Control+PageUp</kbd> corresponds to `C-prior`, and <kbd>Control+PageDown</kbd> corresponds to `C-next`.

**Comment by nitko12** [comment]
Thanks for the quick reply, sorry for a bit unclear issue, so

A1: I would like those keybinds to call default macOS window arranging behavior (those are default system keybinds) but they seem to be captured in terminal, those are the default mac keybinds which arrange windows.

A2: Yes, ^ is control, I've seen that caret notation in iTerm settings :)

A3: By "disabling bind" I'd like to disable any ble.sh functionality associated with those keybinds, for some reason the deafult system binds for arranging windows don't work with ble.sh in iTerm, while they function correctly in other apps, even in iTerm+bash without ble.sh.

A4: I've now tested running `ble-bind -m 'emacs' -f 'C-home' ''` and it does disable jumping to the start of the line but the keybind now displays `unbound keyseq: C-home` in the upper right corner and still doesn't move the window to the left.

I'd also say that it makes sense the system keybinds take higher priority but for some reason it seems thats not the case 🤷

**Comment by akinomyoga** [comment]
Thank you for explaining the situation. I think I now understand the situation.

To receive the detailed key input information, ble.sh turns on the `modifyOtherKeys` mode of the terminal if the terminal supports it. iTerm2 supports `modifyOtherKeys`, so ble.sh turns it on in iTerm2. Maybe, this mode changes iTerm's behavior so that it prevents the system keybindings.

- **Q5**: To confirm this, could you see if the situation changes with the following setting for [`bleopt term_modifyOtherKeys_internal`](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A73-Key-Binding#user-content-bleopt-term_modifyOtherKeys_internal)? Please restart the terminal to test this.

```bash
# blerc

bleopt term_modifyOtherKeys_internal=
```

**Comment by nitko12** [comment]
This fixes it, thank you!

I'll close this now :)

**Comment by akinomyoga** [comment]
OK, then iTerm's `modifyOtherKeys` is somehow interfering with the system keybindings.

----

I was searching for a similar issue with iTerm2, and I found this:

- [Problem with macOS Sequoia window tiling : r/iterm](https://www.reddit.com/r/iterm/comments/1fnpclq/problem_with_macos_sequoia_window_tiling/)

It means that iTerm2 does interfere with the system keybindings. If iTerm2's `modifyOtherKeys` would override all the keybindings including the system ones, I think it should provide a way to disable `modifyOtherKeys` for specific combinations of the keys, so the users can specify the system keybindings that they want to preserve.

----

> This fixes it, thank you!
> 
> I'll close this now :)

It works if you are fine with disabling `modifyOtherKeys`, but it should be noted that with `modifyOtherKeys` disabled, some of ble.sh's keybindings are not available with this settings. In the classical keyboard protocol (which is used when `modifyOtherKeys` is disabled), ble.sh doesn't have a way to differentiate the key inputs such as <kbd>Control+Enter</kbd> and <kbd>Enter</kbd>. If you are interested, you can read [§3.6](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A73-Key-Binding#user-content-sec-modifyOtherKeys). If you want to still use some key combinations without turning on `modifyOtherKeys`, you can also configure it one by one as described in [§3.6.4](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A73-Key-Binding#user-content-sec-modifyOtherKeys-manual). You might also find [this comment](https://github.com/akinomyoga/ble.sh/issues/33#issuecomment-573400356) useful (if the relevant part of iTerm2's configuration interface is unchanged since then).

**Comment by nitko12** [comment]
Thanks for the tips, I'll add them manually when I learn more keybinds and if they don't work as expected,

as for the iTerm I'm not sure should we ask for this as a feature request maybe?

Also can I mention this issue on the Reddit post you linked, I'd also explain what I've changed in iTerm itself?

**Comment by akinomyoga** [comment]
> as for the iTerm I'm not sure should we ask for this as a feature request maybe?

Maybe. Or there might already be a way to avoid this.

@gnachman In iTerm2, when a terminal application turns on XTerm's `modifyOtherKeys` keyboard protocol, the system keybinding of macOS (such as `^Home`, `^End`, `^PageUp`, and `^PageDown` for window tiling) seem to be disabled when iTerm2 is in the front. One seems to be able to avoid a similar behavior observed without `modifyOtherKeys` by unbinding iTerm2's corresponding keybindings. With `modifyOtherKeys` turned on, I guess every key combination is consumed by the `modifyOtherKeys` feature so that it doesn't fall back to the system keybindings. Is there a way to configure iTerm2 to avoid this (e.g. by disabling `modifyOtherKeys` for specific combinations of keys)?

> Also can I mention this issue on the Reddit post you linked, I'd also explain what I've changed in iTerm itself?

Sure!

**Comment by gnachman** [comment]
Control-pageup is handled in modifyOtherKeys, and actually sends a control sequence. What does control-pageup do for you and how did you configure it that way? That is not a default system shortcut as far as I'm aware. I'd like to experiment with this but I need to reproduce it locally first.

**Comment by akinomyoga** [comment]
Thank you for your reply. I'm actually not a macOS user, so @nitko12 will explain the details.

Here, I described what I understand now (without actually trying, so it might contain some misunderstandings). @nitko12 wants to use the window tiling feature of macOS through these keybindings even while `modifyOtherKeys` is turned on. The window tiling feature of macOS seems to have been [introduced in macOS 15 (Sequoia)](https://www.computerworld.com/article/3550352/how-to-use-window-tiling-with-macos-sequoia.html) released last month. [This Apple-Support page](https://support.apple.com/en-bw/guide/mac-help/mchl9674d0b0/mac) lists the shortcuts, where Control-PageUp is included as "Fn-Control-Up Arrow". I'm not sure whether the keyboard shortcuts for window tiling is enabled by default, but [this page](https://support.apple.com/en-om/guide/mac-help/mchl118087b0/mac) describes the location of the window tiling settings, and I see the "[Shortcuts...]" button at the bottom in the screenshot on that page.

**Comment by gnachman** [comment]
Please try 3.5.6beta1, which I just released. It fixes a number of issues related to window tiling. The distinction between Fn-Control-Up Arrow and Control-PageUp is so subtle as to be incomprehensible, so @nitko12 please let me know if the problem remains and if so send me a debug log!
