### ISSUE TITLE
don't format dirname differently than basename

### ISSUE THREAD

**Issue by simonLeary42** [akinomyoga/ble.sh#518]
example of `/dev/null`:
<img width="220" alt="image" src="https://github.com/user-attachments/assets/7ce33022-83b4-4a45-b4e8-87d055424470">

I'd prefer if the entire path was formatted as the word "null" is formatted.

<img width="936" alt="image" src="https://github.com/user-attachments/assets/ea845c59-4021-4118-841a-16658e78483c">

**Comment by akinomyoga** [comment]
Is there an actual problem with the current behavior of highlighting each path segment? Would this become a deal breaker for you? Or is this just a preference?

If it is just a preference, I'm afraid to say that *I wouldn't add a configuration for every tiny preference* because the current set of options is already too large. Otherwise, it would end up with thousands of options. Instead, I'd recommend the users who want to tweak the detailed behavior to modify ble.sh by themselves. Since it is implemented in a set of shell functions, users can overwrite the relevant functions. In the present case, the highlighting of the path segments is controlled by the shell function `ble/progcolor/highlight-filename/.pathspec.wattr`.

https://github.com/akinomyoga/ble.sh/blob/32f290df78554e22d7ff779d34f1dfec271c16df/lib/core-syntax.sh#L7209-L7241

You can modify this function. For example, you can use `ble/function#advice` (undocumented, though Japanese code documentation is [here](https://github.com/akinomyoga/ble.sh/blob/32f290df78554e22d7ff779d34f1dfec271c16df/src/util.sh#L2517-L2545)) to slightly modify the behavior of the function as follows:

```bash
# blerc

ble-import lib/core-syntax \
  -C 'ble/function#advice before ble/progcolor/highlight-filename/.pathspec.wattr "ADVICE_WORDS[2]+=:no-path-color"'
```

It should be noted that the target function is defined in module `lib/core-syntax`, whose loading is deferred, so the function needs to be overwritten after module `lib/core-syntax` is loaded. In the above example, this is achieved by the `ble-import -C` callback (see `ble-import --help`).

It should also be noted that this configuration might be broken in the future because this modifies an internal function and the function can be subject to change (though I currently don't have any plan to change the function).

**Comment by simonLeary42** [comment]
oh, I chose "feature request" when I was making the issue but in retrospect it doesn't really look like a feature request. It's just a preference.

That `.blerc` one liner works, thanks!
