### ISSUE TITLE
[Tilix] Can't paste multiline commands

### ISSUE THREAD

**Issue by KaKi87** [akinomyoga/ble.sh#544]
```console
GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu) [Debian GNU/Linux 12 (bookworm)]
ble.sh, version 0.4.0-nightly+546499b (noarch) [git 2.47.1, GNU Make 4.3, GNU Awk 5.1.0, API: 3.0 (GNU MPFR 4.1.0, GNU MP 6.2.1)]
bash-completion, version 2.11 (hash:aefcfdd4b924e8b03db0d49be8bdb5881ad7d0cd, 77084 bytes) (noarch)
zoxide, version 0.9.6 (/home/linuxbrew/.linuxbrew/bin/zoxide)
locale: LANG=en_US.UTF-8
terminal: TERM=xterm-256color wcwidth=14.0-west/16.0-2+ri, vte:6800 (65;6800;1)
options: +extglob +histappend -hostcomplete +inherit_errexit +login_shell
```

Hello,

Trying to paste multiline commands results in multiple errors that don't occur when ble.sh is disabled :

![](https://github.com/user-attachments/assets/03168764-83d4-4e2f-b724-da018b4f1365)

Thanks

**Comment by akinomyoga** [comment]
Which terminal do you use? This seems like the terminal's quirk that sends the raw pasted data without converting the newlines to <kbd>RET</kbd> properly.

**Comment by KaKi87** [comment]
This is Tilix, a popular terminal emulator for GNOME.

But you're right, the issue doesn't occur on Konsole, the popular terminal emulator for KDE.

**Comment by akinomyoga** [comment]
It seems to call [`vte.pasteClipboard`](https://github.com/gnunn1/tilix/blob/5289686c66fea93a285eb34f3877e8271178f39f/source/gx/tilix/terminal/terminal.d#L1495)., but I don't find this function either in [the Tilix codebase](https://github.com/search?q=repo%3Asteveniemitz%2Ftilix%20%2F%5CbpasteClipboard%5Cb%2F&type=code) and [VTE](https://gitlab.gnome.org/search?group_id=8&nav_source=navbar&project_id=1893&repository_ref=master&search=pasteClipboard&search_code=true). Maybe this is defined in another library or in an old version of VTE. I'll later investigate them.

**Comment by akinomyoga** [comment]
It seems to be processed in this function call chain.

- [`Terminal::copyClipboard` - /generated/vte/vte/Terminal.d - GtkD](https://github.com/gtkd-developers/GtkD/blob/35fb7efcbd3760a0e0f034507104c708f1438ebb/generated/vte/vte/Terminal.d#L122-L125)
  - [`vte_terminal_copy_clipboard` - /src/vtegtk.cc- vte](https://gitlab.gnome.org/GNOME/vte/-/blob/a5ca69e49b6ad7020d997e7125f15ce55279ef0a/src/vtegtk.cc#L3864-3870)
    - [`Terminal::emit_copy_clipboard` - /src/vte.cc - vte](https://gitlab.gnome.org/GNOME/vte/-/blob/a5ca69e49b6ad7020d997e7125f15ce55279ef0a/src/vte.cc#L948)
      - [`signals[SIGNAL_COPY_CLIPBOARD]` - /src/vtegtk.cc - vte](https://gitlab.gnome.org/GNOME/vte/-/blob/a5ca69e49b6ad7020d997e7125f15ce55279ef0a/src/vtegtk.cc#L2221)
        - [`VteTerminalClass::copy_clipboard` - /src/vtegtk.cc - vte](https://gitlab.gnome.org/GNOME/vte/-/blob/a5ca69e49b6ad7020d997e7125f15ce55279ef0a/src/vtegtk.cc#L1611)
          - [`vte_terminal_real_copy_clipboard` - /src/vtegtk.cc - vte](https://gitlab.gnome.org/GNOME/vte/-/blob/a5ca69e49b6ad7020d997e7125f15ce55279ef0a/src/vtegtk.cc#L339-344)
            - [`Widget::copy` - /src/widget.hh - vte](https://gitlab.gnome.org/GNOME/vte/-/blob/a5ca69e49b6ad7020d997e7125f15ce55279ef0a/src/widget.hh#L497-498)
              - [`Terminal::widget_copy` - /src/vte.cc - vte](https://gitlab.gnome.org/GNOME/vte/-/blob/a5ca69e49b6ad7020d997e7125f15ce55279ef0a/src/vte.cc#L7113)

However, it seems to copy the current selected terminal content *to* the clipboard. What is relevant now is `Terminal::widget_paste` in the same file as `Terminal::widget_copy`:

- [`Terminal::widget_paste` - /src/vte.cc - vte](https://gitlab.gnome.org/GNOME/vte/-/blob/a5ca69e49b6ad7020d997e7125f15ce55279ef0a/src/vte.cc#L6127-6134)
  - [`vte::terminal::pastify_string` - /src/pastify.cc - vte](https://gitlab.gnome.org/GNOME/vte/-/blob/a5ca69e49b6ad7020d997e7125f15ce55279ef0a/src/pastify.cc#L43)

The conversion from LF (`\n`, `\x0a`) to CR (`\r`, `\x0d`) is properly performed on [this line](https://gitlab.gnome.org/GNOME/vte/-/blob/a5ca69e49b6ad7020d997e7125f15ce55279ef0a/src/pastify.cc#L82-83). I thought the possibility that this conversion is added recently, so I traced back the change history in the vte codebase:

- [`f93a093`](https://gitlab.gnome.org/GNOME/vte/-/commit/f93a093fb2a4029ea365b24f5105b8f45a14bcd7) 2021-11-28
- [`7daaabb`](https://gitlab.gnome.org/GNOME/vte/-/commit/7daaabbc6d8c217b01f94e28c43656fad1170391) 2021-11-28
- [`235eb0c`](https://gitlab.gnome.org/GNOME/vte/-/commit/235eb0cbc11e306ddaf6468cbe6e2f89dcf39dd2) 2015-12-01
- [`05c680a`](https://gitlab.gnome.org/GNOME/vte/-/commit/05c680acb0c5a875947db6072717d97ac7d072f9) 2015-10-13
- [`0501b07`](https://gitlab.gnome.org/GNOME/vte/-/commit/0501b07d2d288846a0e2d3c77304187cda3680e0) 2002-08-07
- [`a062c63`](https://gitlab.gnome.org/GNOME/vte/-/commit/a062c6306732e1cfc034c0c49f416b09b93d63d0) 2002-08-03 introduced

However, this conversion was introduced in 22 years ago.It is unlikely that your Tilix uses a 23-year-old version of `vte`.

**Comment by KaKi87** [comment]
What does this mean then ?

**Comment by akinomyoga** [comment]
There are three possibilities currently in my mind.

- Tilix doesn't use `vte`'s pasting utility, but it instead implements the pasting in its own code, where the conversion is missing.
- Tilix or some other library performs the conversion of the opposite direction after `vte` performs it.
- Tilix configures the pseudo-terminal handler to perform the conversion of CR to LF.

**Comment by KaKi87** [comment]
Okay, what's the next step ?

**Comment by akinomyoga** [comment]
There is actually a suspicious piece of code:

https://github.com/steveniemitz/tilix/blob/d317dc8137a1eaa702e34a3e9aab63a2541d607b/source/gx/tilix/terminal/advpaste.d#L122-L133

I'm going to check how this function is used.

**Comment by akinomyoga** [comment]
@KaKi87 I guess `SETTINGS_ADVANCED_PASTE_REPLACE_CRLF_KEY` implies that Tilix has a setting of "Convert CRLF and CR to LF" in its configuration. Can you find it? If so, could you try turning off it and see if the behavior changes?

**Comment by KaKi87** [comment]
Here's what I found :

![](https://github.com/user-attachments/assets/4f87f21b-cfcc-48eb-9874-2f286e34799c)

This option was enabled, and the issue no longer occurs after disabling it.

That said, it would be nice for ble.sh to work regardless as normal bash does.

Thank you

**Comment by akinomyoga** [comment]
- [/source/gx/tilix/terminal/terminal.d:1441](https://github.com/steveniemitz/tilix/blob/d317dc8137a1eaa702e34a3e9aab63a2541d607b/source/gx/tilix/terminal/terminal.d#L1441)
  - [/source/gx/tilix/terminal/advpaste.d:145](https://github.com/steveniemitz/tilix/blob/d317dc8137a1eaa702e34a3e9aab63a2541d607b/source/gx/tilix/terminal/advpaste.d#L145)
    - [/source/gx/tilix/terminal/advpaste.d:127](https://github.com/steveniemitz/tilix/blob/d317dc8137a1eaa702e34a3e9aab63a2541d607b/source/gx/tilix/terminal/advpaste.d#L127)
- [/source/gx/tilix/terminal/terminal.d:1449](https://github.com/steveniemitz/tilix/blob/d317dc8137a1eaa702e34a3e9aab63a2541d607b/source/gx/tilix/terminal/terminal.d#L1449)
  - [/src/vte.cc:4858](https://gitlab.gnome.org/GNOME/vte/-/blob/a5ca69e49b6ad7020d997e7125f15ce55279ef0a/src/vte.cc#L4858)

So this bypasses the conversion by `vte`.

**Comment by akinomyoga** [comment]
> This option was enabled, and the issue no longer occurs after disabling it.

Thanks for the confirmation.

> That said, it would be nice for ble.sh to work regardless as normal bash does.

This is a bug of Tilix, which fails to implement the correct terminal protocol for pasting. When the option is enabled, it should convert CRLF and LF to CR for the terminal protocol (instead of converting them into LF as it does now).

The behavioral difference between Readline and ble.sh is due to the support for the multiline editing mode in `ble.sh`. Readline/Bash doesn't offer a fully-capable multiline editing mode (though one could insert a newline character by <kbd>C-v C-j</kbd> or <kbd>C-q C-j</kbd>). Readline/Bash instead provides a way to delimit the multiline editing mode by its parser state. On the other hand, `ble.sh` allows users to control and edit multiline commands, where <kbd>C-j</kbd> is used to execute the command. This follows the behavior of the Lisp interaction mode in Emacs.

Here, of course, ble.sh behaves differently from Readline. As far as you request exactly the same behavior of the line editor for the multiline editing mode, we cannot support any multiline mode. In particular, it is unreasonable to break or limit the multiline editing mode just to reproduce the Readline behavior for broken data fed by an unusual terminal protocol.

**Comment by KaKi87** [comment]
I'm sorry I don't understand where the difficulty is : if bash can consider all of CR/LF/CRLF as newlines, why couldn't ble.sh ?

If I was gonna do this in JS for example, I would just replace `split(/\r+/g)` with `split(/[\r\n]+/g)`.

Thanks

**Comment by akinomyoga** [comment]
In short, ble.sh assigns a different feature to <kbd>C-j</kbd> for the multiline editing mode. We cannot assign two functions to a single key.

**Comment by KaKi87** [comment]
But I'm not using this shortcut, I'm just pasting something from my browser.

**Comment by akinomyoga** [comment]
> But I'm not using this shortcut, I'm just pasting something from my browser.

Yes, then the necessary conversion should have been made by Tilix.

**Comment by KaKi87** [comment]
But that's where my question is : why couldn't ble.sh accept all of CR/LF/CRLF as bash does ?

**Comment by akinomyoga** [comment]
Actually, you can configure ble.sh so that it treats the raw LF (the terminal representation of <kbd>C-j</kbd>) the same as CR (the terminal representation of <kbd>C-m</kbd>) by the following setting:

```bash
ble-bind -f 'C-j' 'accept-single-line-or-newline'
```

In this case, you need to bind another key to `accept-line` so that you can run a command from the multiline editing mode.

**Comment by akinomyoga** [comment]
This seems to be already reported in Tilix at https://github.com/gnunn1/tilix/issues/1959.

**Comment by KaKi87** [comment]
I see, so all programs rely on terminal emulators to send only one type of newline format.

**Comment by akinomyoga** [comment]
> I see, so all programs rely on terminal emulators to send only one type of newline format.

Yes, or the terminal application needs to use a special terminal mode called the bracketed paste mode. The communication between the terminal and the terminal application is not just plain text, but various types of key combinations, application messages, events, etc. are also transmitted there. Then, everything needs to be encoded properly.

There are two ways to send the text containing newlines: one is to convert everything to CR, or the other is to quote the entire text with the bracketed-paste-mode begin/end markers (when the terminal detects the support by the application). However, the Tilix sends the raw plain text directly to the terminal application. It is like putting `{data: Hello, terminal world!}` in a JSON file (instead of the correctly quoted `{data: "Hello, terminal world!"}`).

**Comment by akinomyoga** [comment]
@KaKi87 I'm now trying to debug Tilix. I could build and launch Tilix from the source on my machine after solving several problems. However, I have trouble reproducing the reported behavior. How can I paste a text into the terminal so that the problem reproduces?

I've found that the context menu, which pops up when I right-click the terminal display area, has an item "Paste". However, this correctly pastes the text; it quotes the pasted text within the bracketed paste markers, or when the bracketed paste mode is disabled, it correctly converts all the newline characters to CR as far as I observe. This is probably the pasting feature `vte` provides.

From what I observe in the Tilix source code, I guess Tilix has a special UI for pasting text with a dialog or a pane with a textbox, buttons, etc. However, I so far cannot identify how to call the UI. Do you have an idea?

**Comment by akinomyoga** [comment]
OK, I could reproduce the problem. I needed to turn on the option of the advanced pasting dialog in the settings.

**Comment by akinomyoga** [comment]
To paste any texts, we should call vte's `vte_terminal_paste_text`. The D binding (GtkD) offers the interface [`vte.pasteText`](https://github.com/gtkd-developers/GtkD/blob/35fb7efcbd3760a0e0f034507104c708f1438ebb/generated/vte/vte/Terminal.d#L1054-L1057), but this interface doesn't seem to have been released, so Tilix cannot call this `vte` interface. The interface was added in GtkD in commit https://github.com/gtkd-developers/GtkD/commit/43060ab8b88c34be7e617a89bcb41c0e6e3f4637 about 2.5 years ago, but [the last release of GtkD, 3.10.0, is about three-year-old](https://github.com/gtkd-developers/GtkD/tags), and Tilix [references this 3.10.0](https://github.com/gnunn1/tilix/blob/5289686c66fea93a285eb34f3877e8271178f39f/dub.json#L10). I decided to add a code to manually replace CR to LF, with code comments describing the situation with the GtkD version.

I submitted a PR at https://github.com/gnunn1/tilix/pull/2248. However, it seems the pull requests in Tilix are [not processed at all](https://github.com/gnunn1/tilix/pulls?q=is%3Apr) recently. I anticipate it would take time for Tilix to be finally fixed.

@KaKi87 If https://github.com/gnunn1/tilix/pull/2248 is not merged soon (and that's likely), one option is to pull and compile the fixed version of Tilix, [`akinomyoga:stop-pasting-raw-data`](https://github.com/akinomyoga/tilix/tree/stop-pasting-raw-data), by your self. To compile Tilix, one needs to first install the D building system, `dub`. One also needs to install a D compiler `dmd` (Digital Mars D) or `ldc` (LLVM D compiler). According to README, `gdc` (GNU Compiler Collection - D support) is unsupported by Tilix. Then, you can clone the repository `git@github.com:akinomyoga/tilix.git` and check out the PR branch `stop-pasting-raw-data`. You can run `dub build --build=release` inside the directory. If it is successful, a binary `tilix` should be created.

In my case, it didn't compile with `ldc` (in Fedora). I needed to fix `dub.json` in the Tilix repository as follows:

```diff
diff --git a/dub.json b/dub.json
index 45f6e0c6..905d9d6c 100644
--- a/dub.json
+++ b/dub.json
@@ -4,7 +4,7 @@
     "copyright": "Copyright 息 2016, Gerald Nunn",
     "authors": ["Gerald Nunn"],
     "mainSourceFile": "source/app.d",
-    "dflags-ldc": ["-disable-linker-strip-dead","-link-defaultlib-shared=false"],
+    "dflags-ldc": ["-disable-linker-strip-dead","-link-defaultlib-shared=true"],
     "dependencies": {
         "gtk-d:gtkd": {
             "version": "3.10.0"
```

**Comment by KaKi87** [comment]
Oh wow, I didn't expect you to invest so much !

In fact, I was planning to investigate switching to another terminal emulator on Pop OS, like Ptyxis. :sweat_smile:
