### ISSUE TITLE
[apt completion] `E: read, still have 1 to read but none left`

### ISSUE THREAD

**Issue by KaKi87** [akinomyoga/ble.sh#545]
```console
GNU bash, version 5.2.21(1)-release (x86_64-pc-linux-gnu) [KDE neon 6.2]
ble.sh, version 0.4.0-nightly+1764652 (noarch) [git 2.47.1, GNU Make 4.3, GNU Awk 5.1.0, API: 3.0 (GNU MPFR 4.1.0, GNU MP 6.2.1)]
bash-completion, version 2.11 (hash:9abb523dbcb688e7fae4b87f5fc9d155b658d9ba, 76898 bytes) (noarch)
zoxide, version 0.9.6 (/home/linuxbrew/.linuxbrew/bin/zoxide)
locale: LANG=en_US.UTF-8 LC_ADDRESS=fr_FR.UTF-8 LC_IDENTIFICATION=fr_FR.UTF-8 LC_MEASUREMENT=fr_FR.UTF-8 LC_MONETARY=fr_FR.UTF-8 LC_NAME=fr_FR.UTF-8 LC_NUMERIC=fr_FR.UTF-8 LC_PAPER=fr_FR.UTF-8 LC_TELEPHONE=fr_FR.UTF-8 LC_TIME=fr_FR.UTF-8
terminal: TERM=xterm-256color wcwidth=15.0-west/16.0-2+ri, konsole:220380 (1;115;0)
options: +extglob +histappend -hostcomplete +inherit_errexit
```

Hi,

It's me again, with yet another bug : this error is output while typing the `apt policy` command.

It doesn't start while typing the first character of a package name, but after typing the second one, and then gets rethrown after every additional character typed.

The issue, of course, doesn't occur when not using BLE.

![](https://github.com/user-attachments/assets/1a2c2ce3-62f1-478c-9a0f-02c59bddcdea)
![](https://github.com/user-attachments/assets/aa17d4e9-4d42-4081-ae72-319d2642bb45)
![](https://github.com/user-attachments/assets/0978420e-0020-4259-9ffc-c22989802621)

Also, the issue doesn't occur on other APT subcommands, such as `install`.

Thanks

**Comment by akinomyoga** [comment]
> It's me again, with yet another bug : this error is output while typing the `apt policy` command.

I'm not convinced that another one is a bug of ble.sh. That is clearly due to broken implementation of Tilix. It's not just the Tilix fails to convert the newlines properly, but the Tilix also bypasses the modifications based on the bracketed paste mode even though vte supports it.

> It doesn't start while typing the first character of a package name, but after typing the second one, and then gets rethrown after every additional character typed.

Those errors are printed by the completion settings for the `apt` command.

This type of issue is [explained here](https://github.com/akinomyoga/ble.sh/wiki/Reporting-Issue#error-of-external-completion-settings). Recently I needed to do the same explanations too many times, so I decided to document it and ask the reporter to read it. @KaKi87 Could you first read the above document for better understanding of the situation?

> The issue, of course, doesn't occur when not using BLE.

The reason that the issue doesn't happen with every key input is because Readline doesn't offer the auto completion. @KaKi87 Could you check if the problem arises with the TAB completion with ble.sh and without ble.sh?

The error message implies that the completion for the `apt` command tries to read something from the standard input. Do you have an idea about why it needs to read data from stdint? Does it show an extra user interface requiring the user's inputs (when the TAB completion is attempted in plain Bash without ble.sh)? In general, if a completion setting would try to steal the user's input, it would be a problem. In particular, the user's inputs would start to be lost randomly if such a completion setting were called inside `auto-complete` with its stdin connected to the terminal. For this reason, ble.sh redirects stdin of completion settings.

> Also, the issue doesn't occur on other APT subcommands, such as `install`.

Thanks for the information.

**Comment by KaKi87** [comment]
> That is clearly due to broken implementation of Tilix

Actually that's Konsole (KDE's default terminal app).

**Comment by KaKi87** [comment]
> Could you check if the problem arises with the TAB completion with ble.sh and without ble.sh?

Oh, it does indeed, so that's unrelated to ble.sh, sorry

**Comment by akinomyoga** [comment]
> > That is clearly due to broken implementation of Tilix
> 
> Actually that's Konsole (KDE's default terminal app).

I was talking about #544 because you implied #544 to be a bug by writing "yet another bug" here. I think you've written the issue of #544 happened in Tilix but not in Konsole.

**Comment by akinomyoga** [comment]
> > Could you check if the problem arises with the TAB completion with ble.sh and without ble.sh?
> 
> Oh, it does indeed, so that's unrelated to ble.sh, sorry

Thanks for checking the behavior! Are you going to report this to apt?

**Comment by KaKi87** [comment]
> you implied https://github.com/akinomyoga/ble.sh/issues/544 to be a bug by writing "yet another bug" here

Well, from my end user point of view, it does look like a bug, because of breaking a workflow that worked fine with bash without any configuration change. Regardless though, this is either the second or the third bug, but not the [first](https://github.com/akinomyoga/ble.sh/issues/535), so "yet another" works.

That said, I didn't mean to add any subtext by using this phrase, I only mentioned it as a reference to [an episode of my favourite TV show](https://www.imdb.com/title/tt4679172/).

> Are you going to report this to apt?

As APT didn't receive an upgrade recently and this issue didn't occur ever before, I doubt APT is the source of the issue. I'll ask on communities first.

**Comment by akinomyoga** [comment]
> That said, I didn't mean to add any subtext by using this phrase, I only mentioned it as a reference to [an episode of my favourite TV show](https://www.imdb.com/title/tt4679172/).

Hmm, I didn't know that TV show.

> > Are you going to report this to apt?
> 
> As APT didn't receive an upgrade recently and this issue didn't occur ever before, I doubt APT is the source of the issue. I'll ask on communities first.

OK, thanks for the information.

For #544, I'm now trying to investigate if Tilix could be fixed. Something unfortunate is that Tilix seems lack maintainers, so we likely need to fix it by ourselves and submit a PR. I think we could basically use `pasteText` instead of `feedChild`, but I need to first set up the development environment for the D language.
