### ISSUE TITLE
[Question] How to disable syntax highlighting?

### ISSUE THREAD

**Issue by pjmp** [akinomyoga/ble.sh#61]
Thank you so much for this, i love it.
However sometime i want to disable syntax highlighting and i could not find a way to completely disable it, help is much appreciated.

**Comment by akinomyoga** [comment]
Thank you for the question! In the commit 0116f8b, I added new options to enable/disable the highlighting.

- [`bleopt highlight_syntax`](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A72-Graphics#236-bleopt-highlight_syntax-emptynon-empty-v04)
- [`bleopt highlight_filename`](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A72-Graphics#237-bleopt-highlight_filename-emptynon-empty-v04)
- [`bleopt highlight_variable`](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A72-Graphics#238-bleopt-highlight_variable-emptynon-empty-v04)

To turn off the highlighting based on syntax, please put the following line in your setting:

```bash
bleopt highlight_syntax=
```

Instead, you can turn off some parts of syntax highlighting. With the following setting, you can turn off the highlighting of command names and file names based on its existence and type.

```bash
bleopt highlight_filename=
```

The highlighting based on the variable type can also be turned off by the following setting:

```bash
bleopt highlight_variable=
```

It should be noted that in the above settings, only the syntax highlighting will be turned off. The highlighting of auto-complete, selection, menus, etc. is not turned off. If you want to remove every colors, you can use the following setting, but I do not recommend it because the transient texts inserted by auto-complete and other features cannot be distinguished with this setting.

```bash
# Note: the following order is important
_ble_term_color=1
bleopt term_true_colors=none
```

**Comment by pjmp** [comment]
Thank you so much, i tested it and it works well

I wanted disable highlighting to improve performance, i feel like it is performing better now (although no benchmarks to prove :stuck_out_tongue: ).
 
You rock!
