### ISSUE TITLE
[mc] Issues when using ble.sh with Midnight Commander file manager

### ISSUE THREAD

**Issue by onelittlehope** [akinomyoga/ble.sh#62]
**ble version**: 0.3.2+2423f4d
**Bash version**: 4.4.20(1)-release, x86_64-pc-linux-gnu
**GNU Midnight Commander:** 4.8.19

I have the following line at the end of my .bashrc: `source $HOME/.ble-0.3.2/ble.sh`

When this line is present and I've opened a terminal (KDE's Konsole), ble.sh operates perfectly on the command line.

However, if I try to launch the Midnight Commander file manager via the `mc` command, there is a 10 second pause before the file manager's main screen comes up.

This behaviour is consistently reproducible.

This file manager has the ability to launch a sub shell by pressing Ctrl+O. When ble.sh is active, pressing the key combination results in a blank screen (no output) and no shell being launched.

When I remove the line from the .bashrc which sources ble.sh, both the above symptoms disappear.

One other piece of information: If I have no line in the .bashrc which sources ble.sh, and I launch a terminal and at the prompt, I enter the following lines:

```
# Activate ble.sh
source $HOME/.ble-0.3.2/ble.sh

# Launch the file manager
mc
```

I do not get the 10 second pause before the main window of the file manager is displayed and pressing Ctrl + O inside Midnight Commander correctly launches a subshell (which doesn't seem to have ble.sh enabled) and it operates fine.

Is there any information I can provide which could help diagnose this issue?

**Comment by akinomyoga** [comment]
Thank you for the report! Fix is in `master` (version 0.4) e97aa07.

I tried with `mc` and could reproduce the problems. It seems `mc` is implemented by hacky techniques. It turned out that the problem was caused when `mc` tries to change Bash's settings by sending [some inputs](https://github.com/MidnightCommander/mc/blob/master/src/subshell/common.c#L786-L788) to Bash. Here `mc` tries to insert a new line by the key binding <kbd>C-j</kbd>( `\n`), but `ble.sh` changes the behavior of <kbd>C-j</kbd> so that `mc` fails to insert a new line. This is the same problem as the one reported [here](https://bbs.archlinux.org/viewtopic.php?pid=1040104#p1040104). As far as `mc` is relying on this hack, one should keep the key binding of <kbd>C-j</kbd> for `mc`. I changed `ble.sh` to detect `mc`'s hack and emulate the behavior of the original Bash for `mc`'s hack.

Also, I added several other workarounds for `mc` including

- Work around failure of prompt string identification caused by `mc`'s assumption that there is no output from shell after printing prompt, which is not tur in `ble.sh` session.
- Work around broken layouts caused by `mc`'s assumption that the prompt line is on the last line of the screen, which is not true in `ble.sh` sessions.
- Turn off right prompt ([`bleopt prompt_rps1`](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A74-Editing#user-content-bleopt-prompt_rps1)) and other sub-prompts which might confuse `mc`.
- Do not add `mc`'s initialization commands to the command history.

Could you try if everything works fine now? (Note: you need to switch to the devel version on `master` branch.) Thank you!

**Comment by onelittlehope** [comment]
Thank you for the thorough investigation in the matter.

I can confirm that everything works fine now.

Many thanks.

**Comment by akinomyoga** [comment]
Thank you for the report and confirmation!

**Comment by mooreye** [comment]
I just had this problem and searching to me here.
It seems the issue resurfaced, I have newest ble.sh updated just now.
There is a long delay before `mc` launches.

**Comment by akinomyoga** [comment]
@mooreye What is your ble.sh version? Could you paste the result of the following command in a ble.sh session?

```bash
$ ble/widget/display-shell-version
```

**Comment by mooreye** [comment]
```
GNU bash, version 5.2.15(1)-release (x86_64-redhat-linux-gnu) [Fedora Linux 38 (Thirty Eight)]
ble.sh, version 0.4.0-devel4+a24435d3 (noarch) [git 2.41.0, GNU Make 4.4, GNU Awk 5.1.1, API: 3.1 (GNU MPFR 4.1.1-p1, GNU MP 6.2.1)]
bash-completion, version 2.11 (hash:1a7f5634b4c9816716b69a7824e0b51cfde2bca3, 76332 bytes) (noarch)
fzf completion, (hash:9474ea03117b565f340ee8dacb438260b29e0021, 10334 bytes) (noarch)
WARNING: fzf integration "integration/fzf-completion" is not activated.
locale: LC_COLLATE=en_DK.UTF-8 LANG=en_US.UTF-8 LC_ADDRESS=en_DK.UTF-8 LC_CTYPE=en_DK.UTF-8 LC_IDENTIFICATION=en_DK.UTF-8 LC_MEASUREMENT=en_DK.UTF-8 LC_MESSAGES=en_DK.UTF-8 LC_MONETARY=en_US.UTF-8 LC_NAME=en_DK.UTF-8 LC_NUMERIC=en_US.UTF-8 LC_PAPER=en_DK.UTF-8 LC_TELEPHONE=en_DK.UTF-8 LC_TIME=en_GB.UTF-8
terminal: TERM=xterm-256color wcwidth=15.0-west/15.0-2+ri, vte:7202 (65;7202;1)
```

**Comment by akinomyoga** [comment]
OK, I confirmed that the problem doesn't arise with mc-4.8.28 but arises with mc-4.8.29.

**Comment by akinomyoga** [comment]
@mooreye I pushed fixes for mc-4.8.29 in the `master` branch. In addition to the one you reported, there were multiple other issues, which took time to fix and work around. Could you check the behavior?

**Comment by sooslaca** [comment]
Hi @akinomyoga , I would like to report same slow start with `mc` as others mentioned before, and also weird behavior like empty line, pressing enter gives this:
```
root@server:~# mc

root@server:~# bash: syntax error: unexpected end of file

```

It's a fresh empty Ubuntu 25.10 install with default mc from apt.

```
root@qotom:~# ble/widget/display-shell-version
GNU bash, version 5.2.37(1)-release (x86_64-pc-linux-gnu) [Ubuntu 25.10]
ble.sh, version 0.4.0-devel4+b99cadb (noarch) [git 2.51.0, GNU Make 4.4.1, GNU Awk 5.3.2, API 4.0, PMA Avon 8-g1, (GNU MPFR 4.2.2, GNU MP 6.3.0)]
bash-completion, version 2.16.0 (hash:480ffcc6a751e55621ec526eb5dea7a0d86d9e72, 17877 bytes) (noarch)
locale: LANG=en_US.UTF-8
terminal: TERM=xterm-color wcwidth=16.0-west/16.0-2+ri, xterm:136 (0;136;0)
options: +extglob +histappend -hostcomplete +inherit_errexit +login_shell
root@qotom:~# mc -V
GNU Midnight Commander 4.8.33
Built with GLib 2.85.4
Built with S-Lang 2.3.3 with terminfo database
Built with libssh2 1.11.1
With builtin editor and aspell support
With subshell support as default
With support for background operations
With mouse support on xterm and Linux console
With support for X11 events
With internationalization support
With multiple codepages support
With ext2fs attributes support
Virtual File Systems:
 cpiofs, tarfs, sfs, extfs, ext2undelfs, ftpfs, sftpfs, shell
Data types:
 char: 8; int: 32; long: 64; void *: 64; size_t: 64; off_t: 64; uintmax_t: 64;
```

Workaround is that I'm disabling blesh, but that's not a long term fix and also I cannot enjoy it under mc subshell which is sad.
```
[[ $- == *i* && -z $MC_SID ]] && source -- /opt/blesh/ble.sh --attach=none
```

**Comment by akinomyoga** [comment]
OK, I confirmed the issue with mc-4.8.33. The issue doesn't happen with 4.8.32. Honestly, it is a pain to continue to support mc. It is broken too frequently in various aspects.

**Comment by akinomyoga** [comment]
The previous workaround for mc-4.8.29 was 2c4194a2.
