### ISSUE TITLE
Multi-user environments

### ISSUE THREAD

**Issue by johnyaku** [akinomyoga/ble.sh#69]
Will ble.sh work in multi-user environments?
That is, can multiple users source ble.sh simultaneously?
Or are there shared temporary files etc that will lead to conflicts?
よろしくお願いします

**Comment by akinomyoga** [comment]
Thank you for the question! Although I haven't tested it intensively in multi-user environments, `ble.sh` should work in multi-user environments without problems. Multiple Bash instances of multiple users can source the same `ble.sh` simultaneously.

Temporary files are not shared among users for security reasons. There are two different types of temporary files that `ble.sh` uses: cache files and runtime temporary files. The former is placed in one of the directories `$XDG_CACHE_HOME/blesh`, `$HOME/.cache/blesh`, and `/path/to/blesh/cache.d/$UID` (where `/path/to/blesh` is the directory of `ble.sh`). The latter is placed in one of the directories `$XDG_RUNTIME_DIR/blesh`, `/run/user/$UID/blesh`, `/tmp/blesh/$UID`, and `/path/to/blesh/tmp/$UID`. As far as the environment variables `$HOME`, `$XDG_CACHE_HOME`, `$XDG_RUNTIME_DIR` and `$UID` is correctly set up to have user-specific values, the temporary files will not be shared with other users. Also, the filenames of Bash-session-specific temporary files contain `$$` (i.e., the process ID) as a prefix so that multiple Bash sessions of a user can source `ble.sh` simultaneously.

If you have any problems in multiuser environments, please feel free to report them here. Thank you!

**Comment by johnyaku** [comment]
Perfect! I've found ble.sh very useful, and I will promote it actively!
どうもありがとうございました！

**Comment by akinomyoga** [comment]
Thank you!
