### ISSUE TITLE
Autocomplete places backslash on program options, causes further completion to fail

### ISSUE THREAD

**Issue by 3ximus** [akinomyoga/ble.sh#77]
Hello, its me again.
So I have noticed this behavior for some programs, when autocompleting options that have an equals sign an escape bar is placed, like so:
![print](https://user-images.githubusercontent.com/9083012/102020590-025ac000-3d72-11eb-9baf-6c9005b23037.png)
This still works for these programs without any issue, however for others it fails to keep giving autocompletion. Like here on scp:
![print_000](https://user-images.githubusercontent.com/9083012/102020630-3d5cf380-3d72-11eb-9912-5a75a3ceacb9.png)
It suggests my aliased server name but with an escaped colon, if i start asking for autocompletions from the remote server (for example I know I have a folder named downloads)
![print_001](https://user-images.githubusercontent.com/9083012/102020658-801ecb80-3d72-11eb-8768-0294d166eba0.png)
This happens when hitting `TAB`
![print_002](https://user-images.githubusercontent.com/9083012/102020664-a0e72100-3d72-11eb-9fc9-e2de1e891367.png)
The program would still work with the escape bar before the collon, it just doesn't serve me the correct completions as it would if I remove the escape bar
![print_003](https://user-images.githubusercontent.com/9083012/102020745-10f5a700-3d73-11eb-8b41-a0e2791b5dfe.png)

Could this be fixed by never placing the backslash in the first place ?
Thank you for your time !
Cheers !

**Comment by akinomyoga** [comment]
Thank you for your report again!

### Quoted `=` and `:`

> Could this be fixed by never placing the backslash in the first place ?

In d82535e, I changed so that `=` and `:` in completions won't be quoted with a certain condition.

Actually, the problem is not that simple because `ble.sh` tries to modify/improve the behavior of the programmable completion of the original Bash. There are still some strange behaviors in some cases (e.g., when the programmable completion generates completions that are already quoted), but I fixed it not to cause problems in the reported cases.

### Vanishing hostnames separated by `\:`

> ![print_001](https://user-images.githubusercontent.com/9083012/102020658-801ecb80-3d72-11eb-8768-0294d166eba0.png)
> This happens when hitting `TAB`
> ![print_002](https://user-images.githubusercontent.com/9083012/102020664-a0e72100-3d72-11eb-9fc9-e2de1e891367.png)

It seems this behavior that the prefix `centec\:` is lost is the problem of `bash-completion`. Even without `ble.sh`, the behavior reproduces.

**Comment by 3ximus** [comment]
Thank you, yeah adding this exception for non filenames seems enough. It is working nicely :)

I have another question, don't know if you want me to open another issue, but sometimes I get this output after some program finishes:
![print_001](https://user-images.githubusercontent.com/9083012/102081554-57491580-3e08-11eb-931b-60d9371df58a.png)
In this case it is colored because the last thing I wrote ''-e", but usually it isn't.
I haven't been able to find exactly when it happens. Maybe you can tell me or I can see if I figure it out the times it happens and report again. Either way, it's not really that big of a deal.

And once again, thank you so much !

**Comment by akinomyoga** [comment]
> sometimes I get this output after some program finishes:
> ![print_001](https://user-images.githubusercontent.com/9083012/102081554-57491580-3e08-11eb-931b-60d9371df58a.png)

OK, thank you for your additional report. It doesn't reproduce at my side.

> I haven't been able to find exactly when it happens. Maybe you can tell me

Hmm, I currently don't have an idea what causes these messages. It should be related to some background commands started by something like `unset i &`, but there is no such a command like `unset i` inside `ble.sh`. So, maybe it is caused by an interference with other shell settings.

> or I can see if I figure it out the next times it happens and report again.

OK! If you could get additional information on the next time it happens, that would be helpful!

I have a few questions regarding this phenomena:

- **Q1**. Do you remember whether you have input and executed any commands containing `unset i` before the above screen capture?
- **Q2**. What is the result of the following command just after Bash started?

```bash
$ declare | grep -v ^_ble_history | grep 'unset i'
```

**Comment by 3ximus** [comment]
No I never ran `unset i` before, 
![print](https://user-images.githubusercontent.com/9083012/102088495-e824ee80-3e12-11eb-8c40-fed81efd7cbf.png)
And the only unset I have in files sourced by bash are these, which don't seem like a problem...
![print_000](https://user-images.githubusercontent.com/9083012/102090200-160b3280-3e15-11eb-96e0-3b5eef139930.png)
I don't have any idea where its coming from... And it doesn't follow an apparent pattern.
Well, I'll just stay aware and see if I find more about this issue and I feel it can be related with ble.sh I'll let you know.
Thanks again! Cheers !

**Comment by akinomyoga** [comment]
> Well, I'll just stay aware and see if I find more about this issue and if I feel it can be related with ble.sh I'll let you know.

OK! Thank you. Cheers!
