### ISSUE TITLE
[VSCode] Wrong background color in VSCode integrated terminal

### ISSUE THREAD

**Issue by jmederosalvarado** [akinomyoga/ble.sh#95]
**ble version**:  0.4.0-devel3+0506df2
**Bash version**:  5.0.17(1)-release, x86_84-pc-linux-gnu

Background color under current cursor position in vscode's integrated terminal is gray. This is not the case when using another terminal app (Windows Terminal). The cursor in vscode's terminal looks as if it was set to block, when it is actually set to line.

Here is how it looks within vscode
![Screenshot (15).png](https://user-images.githubusercontent.com/46798594/113498836-a497e280-94de-11eb-82d5-c78ae59614ed.png)

Here is how it looks in windows Terminal
![Screenshot (16).png](https://user-images.githubusercontent.com/46798594/113498855-c3967480-94de-11eb-930b-890ac07c6d0b.png)

This is the output of `ble-color-show` for vscode and windows Terminal respectively.

![Screenshot (18).png](https://user-images.githubusercontent.com/46798594/113498882-f50f4000-94de-11eb-842c-fe2d90e8e3d2.png)
 
![Screenshot (17).png](https://user-images.githubusercontent.com/46798594/113498894-05bfb600-94df-11eb-9266-0963505c31b5.png)

**Comment by akinomyoga** [comment]
Thank you for the report!

This seems to be a quirk of the VSCode terminal for the terminal control function `DECSCUSR`. `ble.sh` assumes that <kbd>ESC SP q</kbd> or <kbd>ESC 0 SP q</kbd> changes the cursor shape to the default one, but the VSCode terminal changes it to the block style regardless of the current setting of the default cursor shape. You can see the differences among terminals by the following commands (in the plain Bash without `ble.sh`):

```bash
$ printf '\e[ q'
$ printf '\e[0 q'
$ printf '\e[1 q'
$ printf '\e[3 q'
```

The backend of the VSCode terminal seems to be [xtermjs/xterm.js](https://github.com/xtermjs/xterm.js). I checked the documentation of `xterm.js`. In its implementation, [falsy values (i.e., empty and 0) are treated as 1](https://github.com/xtermjs/xterm.js/blob/233b78d258417e9d6c107eb54fc4c753e1625911/src/common/InputHandler.ts#L2666). In [a Wiki page of `xterm.js`](https://github.com/xtermjs/xterm.js/wiki/VT-features#set-cursor-style), this behavior is explicitly documented.

In the original DEC implementation of [`DECSCUSR`](https://vt100.net/docs/vt510-rm/DECSCUSR.html), the parameters `empty` and `0` meant the block style, but this is just because the default cursor shape of VT series couldn't be configured so was always the block style. I believe it is more natural to interpret the parameters `empty` and `0` as the current default setting of the cursor shape because the parameters `empty` or `0` typically mean the *default setting* for other terminal control functions. The same discussion can be found in the comment of libvte ([`GNOME/vte/src/vteinternal.hh`](https://github.com/GNOME/vte/blob/f728689e89ef4f6b83527c9a0d340ee52b7d0cf0/src/vteinternal.hh#L178-L180)). In fact, most terminals seem to interpret the parameters `empty` and `0` as the default setting rather than the block style. Here are the terminals I checked/tried:

- **Changes to default**: Windows Terminal, mintty, Alacritty, RLogin, GNOME Terminal (libvte), contra
- **Always changes to block**: VSCode Terminal (xterm.js)
- **Changes to default/block** (default is fixed to block): VT, xterm

I think first we should contact with `xterm.js` about whether the behavior of VSCode Terminal (xterm.js) could be changed. @Tyriar @jerch What do you think of the behavior of <kbd>DECSCUSR()</kbd> and <kbd>DECSCUSR(0)</kbd>?

**Comment by akinomyoga** [comment]
`DECSCUSR` is included in [Terminal WG !8 Feature Reporting](https://gitlab.freedesktop.org/terminal-wg/specifications/-/blob/45c1c6c46e0de498064e826f63e1daf3ab400f82/proposals/feature-reporting/index.md#decscusr), but the parameter 0 seems to be unspecified (What does `No support` actually mean)? Maybe we should also discuss it in Terminal WG later, but this should be discussed as a separate Terminal WG Merge Request because I don't want to further delay Terminal WG !8 which has been already blocked for a too long time.

**Comment by jmederosalvarado** [comment]
Thank you so much for the response. It is a great project this one.

I believe I understood what you explained. However I'm a bit lost on the details. Is there a way for me to change the cursor manually, maybe in bashrc or in the blerc file ???

**Comment by jerch** [comment]
> I think first we should contact with xterm.js about whether the behavior of VSCode Terminal (xterm.js) could be changed. @Tyriar @jerch What do you think of the behavior of DECSCUSR() and DECSCUSR(0)?

Hmm good question. Maybe first some background on this on a general note - in the early days there was a so called ZDM* (zero default mode), which would tell the sequence parser that any `functionXY()` is equivalent to `functionXY(0)`, meant as `default value`. This is what xterm.js' parser does atm. It works so far for all implemented DEC related features.
Later on that mode was removed from ECMA-48 with the note, that a parameter of `0` does not not mean `default value` anymore, but should stand for a numercial value `0` instead. Most sequence functions never applied that updated meaning for older models (e.g. cursor movement sequences still follow the default meaning as in `CSI A` == `CSI 0 A` == `CSI 1 A`). But without ZDM a missing parameter should mean `default value`, while `0` get its zero meaning (thus `CSI A` == `CSI 1 A` != `CSI 0 A`).

For the sequence at hand I see a simple fix (since we have a default cursor style in the terminal options I wasnt aware of):
- DECSCUSR() - switch to default value from settings
- DECSCUSR(0) - switch to default value from settings
- DECSCUSR(1) - steady block

This would be still in line with ZDM, but correctly map to the overwritten default in settings instead.

[*] As far as I know ZDM was completely removed from VTE.

**Comment by akinomyoga** [comment]
@jerch Thank you for the reply!

> For the sequence at hand I see a simple fix (since we have a default cursor style in the terminal options I wasnt aware of):
> - DECSCUSR() - switch to default value from settings
> - DECSCUSR(0) - switch to default value from settings
> - DECSCUSR(1) - steady block
>
> This would be still in line with ZDM, but correctly map to the overwritten default in settings instead.

Yes, this is what the other terminals (that allow to configure the default cursor) do and what I expect. (But `DECSCUSR(1)` is not the steady block but the blinking block).

By the way, I noticed other strange behaviors of the VSCode terminal. Are these behaviors intentional?

- The setting by `DECSCUSR` isn't reflected in the screen until the cursor first moves after the `DECSCUSR`. All the other terminals (with the `DECSCUSR` support) change the cursor shape immediately on `DECSCUSR`. I've tested with `mintty`, `xterm`, `mlterm`, `alacritty`, `terminology`, `urxvt`, Windows Terminal, and also my terminal `contra` using the following code:
  ```bash
  $ for i in 1 3 5 0; do printf '\e[%d q' $i; sleep 1; done
  ```
- The blinking setting by `DECSCUSR` isn't reflected at all. The blinking always follows the default configuration of VSCode terminal regardless of `DECSCUSR`, and therefore <kbd>DECSCUSR(1)</kbd> and <kbd>DECSCUSR(2)</kbd> always behave the same.

> Feel free to create an issue about the default handling of DECSCUSR as well.

OK, I think I'll create issues later.

**Comment by akinomyoga** [comment]
@jmederosalvarado I added a workaround for this one (79d671d); I changed not to emit DECSCUSR when the user doesn't set up any cursor shape settings inside `ble.sh`.

Could you check whether the terminal settings of cursor shape is preserved with the latest version of `ble.sh`? (You can update and reload `ble.sh` by `ble-update` command.) Thank you.

----

In the same commit, I also added a new setting to control the cursor shape inside `ble.sh` (instead of inside the terminal configuration). In typical terminals, you can put one of the following lines in your `~/.blerc`:
```bash
# blerc

ble-bind -m emacs --cursor 1 # blinking block
ble-bind -m emacs --cursor 2 # steady block
ble-bind -m emacs --cursor 3 # blinking underline
ble-bind -m emacs --cursor 4 # steady underline
ble-bind -m emacs --cursor 5 # blinking vertical line
ble-bind -m emacs --cursor 6 # steady vertical line
```

**Comment by jmederosalvarado** [comment]
> @jmederosalvarado I added a workaround for this one (79d671d); I changed not to emit DECSCUSR when the user doesn't set up any cursor shape settings inside `ble.sh`.
> 
> Could you check whether the terminal settings of cursor shape is preserved with the latest version of `ble.sh`? (You can update and reload `ble.sh` by `ble-update` command.) Thank you.
> 
> ----
> 
> In the same commit, I also added a new setting to control the cursor shape inside `ble.sh` (instead of inside the terminal configuration). In typical terminals, you can put one of the following lines in your `~/.blerc`:
> ```bash
> # blerc
> 
> ble-bind -m emacs --cursor 1 # blinking block
> ble-bind -m emacs --cursor 2 # steady block
> ble-bind -m emacs --cursor 3 # blinking underline
> ble-bind -m emacs --cursor 4 # steady underline
> ble-bind -m emacs --cursor 5 # blinking vertical line
> ble-bind -m emacs --cursor 6 # steady vertical line
> ```
> 
> 

Thank you. I'll give it a try later and I'll get back to you.

**Comment by jmederosalvarado** [comment]
> @jmederosalvarado I added a workaround for this one (79d671d); I changed not to emit DECSCUSR when the user doesn't set up any cursor shape settings inside `ble.sh`.
> 
> Could you check whether the terminal settings of cursor shape is preserved with the latest version of `ble.sh`? (You can update and reload `ble.sh` by `ble-update` command.) Thank you.
> 
> ----
> 
> In the same commit, I also added a new setting to control the cursor shape inside `ble.sh` (instead of inside the terminal configuration). In typical terminals, you can put one of the following lines in your `~/.blerc`:
> ```bash
> # blerc
> 
> ble-bind -m emacs --cursor 1 # blinking block
> ble-bind -m emacs --cursor 2 # steady block
> ble-bind -m emacs --cursor 3 # blinking underline
> ble-bind -m emacs --cursor 4 # steady underline
> ble-bind -m emacs --cursor 5 # blinking vertical line
> ble-bind -m emacs --cursor 6 # steady vertical line
> ```
> 
> 

It's working fine. Thank you.

**Comment by akinomyoga** [comment]
Nice! Thank you for testing! I close this issue.
